---
title: "Evolution Earth: Ice (S1E4)"
---

## Online Access

[Link to PBS Series](https://www.pbs.org/show/evolution-earth/)

:::{.column-screen-inset}

<div class="pbs-viral-player-wrapper" style="position: relative; padding-top: calc(56.25% + 43px);"><iframe src="https://player.pbs.org/viralplayer/3083229494/" allowfullscreen allow="encrypted-media" style="position: absolute; top: 0; width: 100%; height: 100%; border: 0;"></iframe></div>

:::

## Transcript

♪ [Shane Campbell-Staton] At the frozen extremes of this world, temperatures are rising 4 times faster than anywhere else on the globe.

♪ Here, nature's resilience is hinting at mysteries that can help us understand our future.

In the Arctic, polar bears are turning up where they aren't supposed to be... [Growls] but if we follow them, they can tell us things about our planet that we just can't see on our own.

♪ [Thunder] ♪ My name's Shane Campbell-Staton.

I'm an evolutionary biologist.

I'm here to tell you stories from filmmakers, scientists, and local experts across the globe about a pulse of change.

The entire planet is shifting.

The climate is changing at an incredible 170 times faster than it should be.

We can't always see it, we're so caught up in our own thing, you know, but the signs are everywhere.

♪ The entire tree of life is whispering to us.

We just have to pay attention.

Out there, things aren't what you expect.

You'll see.

♪ [wind blowing] [snow crunching] In Canada, this female polar bear is migrating to the Hudson Bay with her cubs.

♪ She has spent 4 months inland during the summer, and in that time, she hasn't eaten once.

♪ It's the longest fast of any land mammal.

Chewing on dead leaves is not gonna cut it.

♪ She needs to be out on the ice, hunting seals, but the ice hasn't formed yet.

♪ [woman] They haven't had sea ice for months already.

Uh, polar bears have been fasting for already 3 to 4, sometimes 5 months.

When we're taking notes on bears, we are looking at, well, first, can we tell if it's male or female?

We can't always tell.

Um, how old does it look?

Is it an adult?

Is it a cub?

Is it a sub adult maybe?

And then we're looking at its body condition.

So how fat is it?

We rate them on a scale between 1 and 5, with 5 being the fattest.

And kind of how does their belly hang?

Uh, can we see their shoulder blades?

[Shane] When you talk to Alysa McCall about polar bears... [Alysa] Kind of how fat overall are they?

Now, the best way to do that is to feel polar bears... [Shane] you get the impression she's got a lot to say.

[Alysa] but, um, if we can see ear tags, if there's a unique scar, uh, where the bear's kind of going or what they're doing can all be interesting data.

[Shane] I get it.

She's just one of those people who has found her passion.

She's a world expert in tracking polar bears, following where they go and seeing how they are dealing with our warming world.

[Alysa] We do have a mom with cubs in the area, which is neat because we can figure out who she is.

Uh, let's pull in right here and see what we can see.

♪ She is a 10-year-old female.

Her unique identification number is X33570.

[Shane] X33570 has got a problem.

[Alysa] There's not enough food on land, there's not enough calories for polar bears on land.

They need the high-calorie seal blubber, and they can only get that on the sea ice.

There's a seal taunting a polar bear, and the polar bear just can't get to it, you know.

[Shane] Ordinarily, the bears would be getting ready to hunt those seals.

[Alysa] Yeah.

You could really tell that bear wished it had sea ice to go get that seal.

Yeah.

[Shane] But climate change means the freeze is coming later and later each year.

♪ They're starving.

There's nothing they can do but wait.

♪ Alysa has spent the last 10 years tagging the bears with trackers that can beam their GPS positions straight back to her computer.

Truly only GPS data can give us that.

Uh, so, right now, all the bears have already moved to the coast.

[beeping] We just see these little clusters of bears.

They're all along the coast.

They're just waiting for that ice.

[Shane] Polar bears are usually solitary, but now they find themselves trapped on the coast, crowded together, waiting for the big freeze.

None of them have eaten all summer.

Now, I get hangry after, like, 4 hours, let alone 4 months.

[growling] Cramped on the beach, tempers start to fray.

[growling] They challenge each other, trying to dominate through height.

[growling continuing] You wouldn't want to stand toe to toe with these guys.

They are measuring in at about 10 feet tall... and those 4-inch claws, they'll give you the business.

♪ It's not the time for this kind of fighting.

There are no females in heat, there's no food around.

They're just ornery, and they're wasting valuable energy.

[Alysa] These polar bears are on land 4 weeks longer than polar bears were in the 1980s, so we really are starting to push polar bears to their limits.

They're losing weight.

They lose up to about a kilogram of body weight a day, and that really adds up over time.

[Shane] They can lose over 400 pounds while stuck on land.

Each day, they seem to test the ice, but still no luck... and it's not like this is an easy life in the first place.

[Alysa] Their habitat is so crazy to me.

Like, it's like being on another planet.

To live in a place where it's freezing cold, it's dark, it's windy.

It's literally moving beneath your feet all the time.

It's crazy that polar bears live the life they do, even at the best of times.

and now we're making it even harder for them to be out there.

[Shane] If they're going to be able to hunt, the floating ice needs to be about a foot thick.

♪ [ice cracking] [splashing] ♪ The melting Arctic is not just altering the bears' movements.

It's changing their physiology.

♪ [Alysa] We've seen the bears get a little smaller.

They're having fewer cubs, and that is closely tied to the changes in their sea ice habitat.

[Shane] These bears are on the front line of our changing climate.

[Alysa] We do call them the white, hairy canaries in the coal mine.

[Shane] For females, it's a race against time.

They need to fatten up for the next breeding season.

Up to 70% of them won't gain enough weight to be able to have cubs.

For someone who loves bears so much, it's a hard thing to watch.

People are getting pissed.

I think that's part of it.

Yeah.

I'm getting pissed.

Ha ha ha!

♪ [Shane] Just when we thought they would never get out on the ice, the bay finally starts to freeze.

[computer beeping] The bears' GPS data show movement.

[Alysa] The bears are in line for this buffet that they've been waiting to open for 5 months.

[Shane] Our mama and her cubs can finally get on with their lives.

It's game time now.

[Alysa] The bears are like "Let's go, let's go, let's go!"

[rapid beeping] ♪ [beeping] ♪ [helicopter starting] [Shane] The bears go, and Alysa follows.

♪ [Alysa] Oh, I think we have a bear out at our, uh, 3 o'clock there if you look that way.

This one is a female.

She's got a cub.

The body condition scale is 1 to 5.

Uh, it looks like about a 3, pretty average this time of year.

A lot of the bears we're seeing this year are a 3.

She is, uh, a collared bear, so we can see her on the map.

[Shane] Climate scientists use satellite imagery to track the freezing ocean.

What satellite images can't show is the thickness of the ice as it forms, but collared bears could help us monitor the state of the ice... each bear acting as a sentinel, testing the formation of the ice as they move across the Hudson Bay.

[beeping] Tracking the bears could help us understand the timing of when and where the ice is thin and patchy... [growling] and where it's becoming thicker.

[Alysa] Polar bear collars have much finer resolution than the satellite data, so the ice data is important, but the collars are really giving us the information about what's going on out there.

[beeping] By watching what polar bears are doing, they're telling us a lot about what's going on with the sea ice and the changes that they're experiencing.

♪ [Shane] Sometimes, it's only through the drama of a struggle to survive that we can really appreciate how much our planet is changing.

In this way, their story shows us the changes taking place in their environment.

♪ Like this mountain hare.

Her connection to the environment is etched into her DNA.

She has evolved to change from white to brown just in time from when the snowmelt happens in the spring... but now the snow is melting earlier each year... and the hares can't keep up.

Each year, she finds herself without camouflage for 35 days and counting.

Her fur is signaling how much things are out of whack.

In her white winter coat, she must brave a brown world.

She's basically nature's lunchbox right now.

[bird screeching] And she is being stalked... ♪ by a male suitor on the hunt for a mate.

♪ To test his speed, she runs away.

♪ He may be fast, but how strong?

She adds a boxing match to this date.

♪ For thousands of years, these lovers had their hookups on the down-low, camouflaged by their white fur against the snow.

Now, their mismatched coats are putting all their business out there, telling a story of a changing world they cannot keep up with.

It's the most graphic demonstration I know that shows the shifting connections between an animal and the environment they call home.

Understanding how the environment of these frozen worlds is shifting is vital research... but these inhospitable places are often the most difficult to reach.

[snow crunching] It takes a special person to live here long enough to witness the creeping baselines of change.

[device beeping] [interviewer] Is that your phone that beeped?

I turned my phone off, not that I ever get many calls, but... [Shane] There's not a lot of reception up in the Rocky Mountains, where we met billy barr.

[billy] This'll be my 50th winter out here.

[Shane] He's been out here for a while then.

[billy] Yeah, I got here in '72.

[Shane] And there aren't a whole lot of people up here.

[billy] I'm here all by myself, just talking to myself.

"How you doing?"

"Fine."

"How you doing?"

"Ah, I'm not doing so good."

See, I do that every day.

[Shane] I mean, sometimes you've just got to check in with yourself.

But 50 winters all alone is not why billy has achieved oracle status.

That comes from a very particular skill.

You see, billy's not a scientist.

He is an accountant.

High in the Rocky Mountains, billy started accounting for... snow.

[billy] So I started writing it down just because I had the time.

I've always kept track of numbers, so--I mean, I'm an accountant.

[Shane] At his homemade weather station, he recorded what he found.

[billy] And as I did that year after year, it started to become more and more interesting... especially looking at long-term trends.

This was in, uh, late April 1974.

[Shane] And he started charting everything.

[birds chirping] [billy] And so if you look over here, it shows that it snowed 26 inches overnight.

[Shane] As with all bookkeeping enthusiasts, he got a bit carried away with the details.

Cloud cover, wind strength, temperature.

Daily snowfall, depth of snow, the water content and weight of that snow... and so it went on.

Nothing went unobserved.

[billy] I had this great graph once that showed the amount of snow in the winter as compared to my chocolate consumption.

[Shane] While billy satisfied his sweet tooth, the ledgers mounted up.

A 50-year record of exactly how the snow and nature interact on a day-by-day basis.

Amazingly, it wasn't until the 1990s that scientists got ahold of billy's records.

Only then did they realize these data were showing a creeping change.

[billy] These are the birds I saw each day.

Uh, the first tree swallow, the first yellow-bellied sapsucker.

They're not even called that anymore.

The first butterfly.

And here is the first hummingbird and the first glacier lily on that same day.

[Shane] One key flower that billy tracks is the glacier lily.

The glacier lilies are the first flowers to emerge when the snow melts in the spring.

[billy] This area here is where there's a glacier lily population, and since I go by this every day, I used that as the indicator of when they first start to flower.

[Shane] He told us we should come back.

[billy] If you come out in spring, you'll get to see it.

[Shane] So we did.

[birds chirping] [water flowing] [insects buzzing] The importance of billy's records was really brought home by the timing of this flower and its intimate connection with an animal, one that has undertaken a gargantuan cross-continental migration.

Traveling over 1,500 miles to get here from Mexico... ♪ on wings beating 50 times a second... the broad-tailed hummingbird lives life in the fast lane, and this little dude is absolutely desperate for food.

[chirping] The glacier lily is perfectly timed for his arrival, providing a crucial source of nectar... but billy's data shows a clear mismatch between flower and bird... and the connections are getting more and more out of sync each year.

The flowers now bloom nearly 3 weeks earlier.

[billy] So the glacier lilies are past prime flower when the hummingbirds get here.

[Shane] Some have wilted before the birds even arrive.

billy's data showed that in just 20 years from now the hummingbirds will miss the flowers entirely.

They come to these mountains to breed.

Without the flowers, this will be impossible.

♪ Take it from me.

You can only see long-term shifts like these with the kind of dedicated work billy's put in, but we wondered how much longer would billy stay here?

[billy] I honestly don't know how many more years I'll be out here.

I'm hoping for 10 more, but, you know, it's cold and it's windy.

It's difficult.

[Shane] billy's detailed data reveals a microcosm in flux, showing intricately evolved rhythms of life.

His recordings are now considered to be some of the most significant long-term data on climate change ever collected.

♪ [loud cracking] Recently in Antarctica, the temperature has risen 3 times faster than the rest of the planet.

What we really need is a billy barr here... but no one lives here permanently.

All the more reason to look to the animals to help us understand the changes taking place here.

Like the polar bears in the north, penguins can be sentinels too.

This time, the animals aren't suffering.

♪ These gentoos are bucking the trends and positively flourishing.

In the last few decades, their population has tripled.

Penguins out feeding are ocean samplers.

What these penguins have in their stomachs can help monitor the state of the seas.

♪ After a long day spent hunting, they are coming home, carrying dinner back for their young chicks... ♪ [chattering] but on these mean beaches, gangs of older kids lie in wait, ready to mug any adult of her precious cargo.

[squawking] ♪ They want a payoff if they're gonna let her through.

♪ To save her hard-earned catch, she heads back to the sea.

These crooks don't yet have waterproof feathers for swimming.

She makes a break for it.

♪ Luckily, these guys aren't so nimble on their feet.

She manages to lose the raiders in the colony.

[squawking and cheeping] Finally, she can feed her own chick.

Though some species of penguin need ice floes to nest, gentoos prefer to rock it out on bare earth, and with 150 billion tons of ice melting in Antarctica, they've got plenty of real estate to roll with.

What makes the penguins important messengers of the changing ocean environment is not just the growing size of the colonies but also how they look.

[squawking] The clues are written on the ground in dookie.

I mean, I love nature just as much as everybody, probably more than most, and that's still hard to look at.

It's like a water gun.

The color of this penguin poop can tell us a lot.

The gentoos should be eating krill, making their poop pink, but krill need sea ice to breed... and there ain't much of that to go around here anymore, so the poop here is all... white... because these climate change winners are adapting to hunt fish and squid instead.

Their success painted with over a ton of poop, stains so big, they can be tracked from space.

♪ Researchers are now using satellite images to track penguin populations and the state of the ocean around them.

♪ Checking the satellites in this way led the poop detectives to a massive pink stain... signaling a huge colony of almost a million penguins.

[squawking] Not gentoos, but their cousins, Adélies.

Adélies need ice to survive.

With sea ice retreating in recent years, scientists have recorded extinctions of entire colonies, but here, they're thriving, and the pink color shows there are plenty of ice-loving krill around for them to feed on.

In fact, the ice sheet here is growing, not shrinking.

Is this climate change in reverse?

Scientists have been working to solve this Antarctic riddle for over 10 years.

It's even been adopted by climate change deniers.

So what the hell is going on?

Well, you're gonna have to wait to find out because first, I want to take you on a journey of another animal with one of the greatest love stories on the planet... followed by Sally Poncet, who has spent a lifetime studying the private lives of these birds.

[Sally] There were 3 or 4 wanderers earlier, but they've just disappeared for the moment, but all these--ha ha ha!

Here they come.

[Shane] She's been tracking the health of the wandering albatrosses for over 30 years.

[Sally] I started counting the wandering albatross many, many decades ago.

[Shane] To really appreciate Sally's relationship with these birds, we need to rewind the clock a little.

Ah, very long story.

Heh heh.

[Shane] She was only 21 when she first visited the Antarctic.

[Sally] I first came here on a sailing boat.

Our plan was to go to the Antarctic Peninsula, spend a winter there.

[Shane] That was the plan, but a surprise was the arrival of a baby out here.

[Sally] Our first child was born in South Georgia, and we had two more children.

They grew up on the boat.

Yeah, for them they're really good childhood memories.

[Shane] Sally was living on a boat with 3 kids in one of the most dangerous oceans on the planet.

The tiny island of South Georgia, over a thousand miles off the coast of South America, was one of the few places she set foot on dry land.

[Sally] We went to South Georgia every summer, and I was just really interested in the birds in this place, and I started counting them.

[Shane] And she's returned every year since, although these days she's on a much more impressive boat.

She's not gonna stop checking in on this population anytime soon.

I still want to be able to understand how it works.

I haven't quite figured it out.

Over the years, I've been able to return every summer and-—-and continue those counts.

I've built up a picture of what's happening long term.

[Shane] This is where the love story comes in.

[albatrosses grunting] [low trilling] [Sally] This could be the beginning of a life-long pairing.

[Shane] Albatross mate for life and usually only split if one of them dies at sea.

They can spend up to 50 years together.

[Sally] I can't really imagine anything more intimate than what you can see here.

[Shane] Not that they don't have the odd marital tiff.

[chattering] He's really not happy.

Ha ha!

Telling-- uh, telling him to move on.

[albatross screeching] Wow!

You just take the time to see what they're doing instead of rushing round and counting.

It's just wonderful.

You have these moments just like this one here.

Just very peaceful.

We're all looking at the trends and trying to figure out what it is that makes the populations stay stable.

We haven't finished the counts at the moment, so we'll know that in another hour or so.

I've got to get up and start counting again to do that.

[Shane] We better let Sally get on with it.

The albatrosses are getting fitted with GPS trackers.

[chattering] It might be easy to think of these birds as big seagulls, but then you get close, and, man, are they huge.

Shh.

OK, buddy.

OK. Shh!

Shh!

I know.

[Shane] They swap out this female's egg for a decoy so it doesn't get damaged in the process.

Kind of sneaky, but she'll get it back.

3 feathers.

[Shane] This tracker is a bit like the ones you use when you go running, just a bit more high-tech.

There.

[Shane] They show where the albatrosses go when they leave land, and they go far.

♪ They can circle the globe in 32 days.

The first birds were tagged from Crozet Island, and they sent back data that surprised scientists.

These birds were flying faster than they ever had before... which meant that they were feeding better and raising more chicks.

The albatross colony was thriving.

The idea that they were able to fly faster around the world was kind of odd and seemed too good to be true, and it was.

The birds were not changing.

The planet was.

Climate change is altering the planet's wind patterns, and it looks like increased heat and pressure are causing stronger, faster winds to be pushed south to Antarctica.

Tracking the flight of the albatrosses gives us a graphic demonstration of just how much these winds have strengthened.

They are now over 15% stronger than they were just 40 years ago.

[squawking] The discovery about these changing winds explains the mystery of the Adélie penguins and their growing ice sheet.

It was not climate change in reverse at all.

The more powerful westerly winds are hitting the Ross Ice Shelf, causing a freezing effect.

The Crozet albatrosses are hitching a ride on the winds of our changing planet and coming out winners.

Birds back in South Georgia, however, have a different story to tell.

They are under pressure from a growing wave of fishing boats pushing closer to these waters... but there's a twist.

These animal messengers are becoming undercover cops.

Researchers from the British Antarctic Survey are adapting the birds' tags with radar sensors.

This means when they fly close to a fishing vessel, the tags can identify any suspicious boats and send their location back to HQ.

Through their changing behavior, animals are mapping the changes in the ice worlds... charting the shifting planet through their movement.

In the Arctic, there is another animal drama with a whole lot more to it than meets the eye... and it's highlighting crucial new insights into changes happening to the tundra... changes that could have important consequences for us all.

♪ Very few animals are tough enough to cut it here year-round.

Below ground, lemmings' burrows are insulated from the Arctic winds.

Their predator, the Arctic fox, has evolved to survive on these windswept plains... and withstand temperatures as low as -58 degrees.

He has dark, heat-absorbing skin and multi-layered fur that even grows over his feet.

His hearing can target a lemming through a foot of snow... but this ice world specialist is having to deal with an invader, whose presence signals a problem for our planet.

♪ The new arrival is a wily cousin... the red fox.

♪ [Arctic fox yelps] He, too, is no slouch when it comes to catching lemmings... [sniffing] ♪ and he does it in style.

♪ He's bigger and more aggressive, and he bullies the smaller Arctic fox out of his territory... ♪ but this competition is not as simple as it seems.

Unlike the Arctic fox, the red fox is not so well adapted to survive the blistering icy winds of the Arctic plains... but he does not come alone.

♪ He's backed up by a force much more powerful than himself.

♪ Moving north with him is an army... a wall of trees.

Warming temperatures are allowing the forest to move north, invading the Arctic, lending enough shelter for the red fox to take over this territory.

Now typically, we think of trees as having a positive impact on the climate, but out here they don't have the effect you might expect.

Snow reflects up to 80% of the sun's rays... but the trees darken the tundra, canceling this reflective quality, so the land absorbs more of the sun's heat.

Trees have been found to raise the temperature in the Arctic by nearly two degrees... and this heating effect is a feedback loop.

The more the land warms, the more the trees advance, accelerating climate change as they go.

It's not just snow on the surface that is thawing.

It's the ground below.

Permafrost is soil that remains frozen all year-round.

If it melts, large quantities of greenhouse gases like CO2 and methane are released, further accelerating the warming of our planet.

Change at this speed is a sickness, and we need a cure.

♪ In northernmost Scandinavia, the native Sámi community think the animals of the tundra can play a key role in helping save the region from climate meltdown.

The Sámi have lived on the tundra for 10,000 years.

Traditionally, they were nomadic reindeer herders, following the reindeer on their migrations, but nowadays, human development is encroaching on the wilderness.

With less land available for moving with the reindeer, a more sedentary way of life has taken over.

[reindeer grunting] Nils Ole, like his ancestors before him, has always worked with reindeer.

[Nils] It's a couple of hundred here inside this fence.

They're in good condition.

[Shane] He now rotates his herds.

Though some remain in the wild, many of his animals are penned in the winter to make sure they can all get enough food... and they seem to be pretty into their breakfast.

[Nils] Special made pellets for-—-for the reindeers.

It's a new thing.

It's 20 years ago they start making this reindeer food for them.

[Shane] Nils doesn't want to keep them penned up like this.

[Nils] Before, they were more free, but now we have more lines, where we have to be inside when we have the reindeer.

Of course, I want to have the reindeer free in the nature-- in the nature way, but, uh, when I can't do that, I--—I have to take another option.

So it's easier for me to feed them here inside the fence when there is nothing outside there to find.

[Shane] Nils told us their limited grazing land has been degraded by climate change.

[Nils] I believe so.

What else can it be?

The old people used to say before we didn't have so much rainy days middle of the winter--winter months, and it looks like the winter getting more and more bad.

[Shane] The accelerating pace of climate change here means more rain falls in the winter instead of snow.

Rain freezes, turning the ground to solid ice, making it hard for reindeer to dig for grass and lichen under the snow.

They are literally between a rock and a hard place here.

For many Sámi, the old love of reindeer herding is getting lost to the pull of the city.

There's no sign of that love disappearing here, though.

[Nils] Simba, Simba, Simba.

Simba.

Simba, Simba, Simba.

[Shane] Heh heh heh!

Simba, Simba, Simba, Simba.

[Shane] Oh, man.

[speaking Sámi] Of all the things I was expecting to come around the corner, a reindeer was not on that list.

Ha ha ha!

[speaking Sámi] [Nils, voice-over] Simba--he's like a family now.

Yeah.

He's my best friend.

[Shane] It turned out, they're pretty close.

Yeah, I love him.

[Shane] OK. Really close.

Amazing.

[Shane] He's certainly got a healthy appetite.

[speaking Sámi] [both speaking Sámi] [Shane] I'm not sure his uncle thinks this is the right place for a reindeer.

It's not just the reindeer that are changing around here.

He agrees that the climate isn't the same as it was back in the day.

Everything is changing.

I used to say if my grandfather was living now I think he would get a shock how we-- how we work with the reindeers.

[Shane] Not all the old ways have vanished.

[reindeer grunting] Nils said we should film with his wild herd... and see the power of these animals on the move.

♪ Nils works with the reindeer, herding them to find the best places to go.

♪ With Nils, we followed the animals to the edge of the forest.

This is where he wanted us to see the extent to which wild reindeer can help halt climate change.

As soon as they get amongst the young trees, the reindeer start eating the shrubs and branches.

♪ [Nils] If you see around here, here you can see reindeer eating the fresh-- the fresh sticks and also the bark from the trees.

[Shane] Just like where the foxes are fighting it out in the Canadian Arctic, here, too, the trees are advancing north, over 130 feet per year... a creeping baseline that changes the ecology of the land the reindeer rely on, and, like in Canada, the dark branches absorb the warmth of the sun and interrupt the reflective power of the white snow, accelerating climate change.

The reindeer are fighting back, trimming back shoots, keeping the advancing tree line under control.

It's a revelation in how rewilding an area can help prevent further warming.

They're eating us out of trouble.

[Nils] The reindeer are saving the Arctic here.

You don't believe me?

Ha ha ha!

Then you have to be here to see what's happening.

The--you know, the Sámi people, we live with nature, so we know what's happening because we have to have them in the nature.

It's very important, and I think a lot of people don't know that.

[Shane] The Sámi community have always known that the tundra needs the reindeer... and now scientists are starting to listen.

They measured the reflectance of the snow across Northern Europe... and they compared where the reindeer were restricted to where they were allowed to graze freely.

The effect was staggering.

Where reindeer were herded year-round, the snow reflected double the sun's radiation and warmth, keeping the ground colder and holding the snow for longer.

♪ With help from herders like Nils, the reindeer can preserve the tundra, holding back the changes here and preventing further warming.

[Nils] You know, some years, it can be very tough to be a reindeer herder, but it's something in your heart.

You know, you still work with this, you fight for this.

You--you do everything to protect the reindeer.

♪ [Shane] When nature is allowed off the leash to be fully functioning, it can have an awe-inspiring resilience.

These powers of nature shouldn't be underestimated.

If we can listen to the animals and help maintain these ice worlds... they could help secure the future of our entire planet.

♪ ♪ Next time... grasslands.

♪ Where animals have the power... to transform our world.