---
title: "Human Footprint: Strangers in Paradise (S1E1)"
---

## Online Access

[Link to PBS Series](https://www.pbs.org/show/human-footprint/)

:::{.column-screen-inset}

<div class="pbs-viral-player-wrapper" style="position: relative; padding-top: calc(56.25% + 43px);"><iframe src="https://player.pbs.org/viralplayer/3080628586/" allowfullscreen allow="encrypted-media" style="position: absolute; top: 0; width: 100%; height: 100%; border: 0;"></iframe></div>

:::

## Transcript

Shane, voice-over: It was a crisp March morning in 1890 when Eugene Schieffelin walked through these arches... carrying cages full of noisy, glossy blackbirds never before seen in North America.

Schieffelin was the chairman of the American Acclimatization Society, an organization dedicated to bringing European plants and animals to the United States.

♪ As he opened the cages, 60 European starlings flew into the wintry New York sky for the first time.

They soon found other starlings released elsewhere, and their population exploded, creating impacts on our ecosystems and economy that still reverberate today... but this isn't a story about starlings or any of the other invasive species spreading across the planet.

It's a story about one species that moves others around the globe like pieces on a chessboard.

The problem is, depending on where they land, sometimes those pieces start playing their own game.

Welcome to the age of humans, where one species can change everything and what we do reveals who we truly are.

This is "Human Footprint."

[Ship's horn blows] Humans are a cosmopolitan species, one of the few, and wherever we go, we bring other species with us, sometimes on purpose, sometimes without even knowing.

When the conditions are right, it's a bonanza for these alien species.

They multiply, spread, and wreak havoc in their new environments.

These biological invasions have cost the global economy $1.4 trillion, and after habitat destruction, they're the leading cause of species extinctions... but are invasive species really the villains?

After all, when an arsonist starts a fire, no one blames the match.

Maybe instead of vilifying the species that succeed where they don't belong, we should take a closer look at why they're there in the first place and how our species is handling the fallout.

[Insects chirping] You're out here searching for dragons.

♪ Woman: You're looking for something almost that looks like a frog.

Shane: Something like a frog with a lot more attached to it.

Ha ha!

Shane, voice-over: In South Florida, one invasive species is transforming an entire ecosystem.

Woman, voice-over: Once I see it, adrenaline starts pumping, and you know the game's on.

Man: ♪ It's about that time ♪ Man 2: ♪ Yo, what you know about going out ♪ ♪ Head west, red Lex, TV's all up in the headrest ♪ ♪ Try and live it up, ride true, a bigger truck ♪ ♪ Peeps all glittered up, stick up can, they go what?

♪ Woman: ♪ Bad, bad boy ♪ ♪ You make me feel so good ♪ Woman: I've caught on full moons.

I've caught below 75.

I've caught on windy days, so, you know, you just got to be out here.

You never know when a python's going to be out here moving around.

Man: ♪ Where would I be without my baby?

♪ Shane, voice-over: In 2017, Donna Kalil quit her job in real estate to become a full-time Burmese python hunter.

Whoo hoo!

Ha ha ha!

[Hissing] Another monster gone.

Yeah.

Oh, my gosh!

Shane: I'm loving the--loving this.

The snake leather's nice and supple right there.

Yeah.

I love the trim.

It helps my volunteers, you know, remember what you're looking for out there.

Ha ha ha!

What made you decide to take up the mantle of python wrangler?

I know how to catch snakes.

I've known how to all my life, and I knew that I can make a difference to the environment that I love.

What is the largest python you've caught?

Largest I've caught was 16 even.

Oh, wow.

These guys didn't sprout wings and fly over from Southeast Asia.

We brought 'em here, so we made the problem.

We gotta--we gotta fix it.

Shane, voice-over: One way Florida is trying to fix the problem is by paying folks like Donna to capture and kill the pythons.

So far, she's brought in more than 600 of them.

[Insects chirping] So if you do see something on the road, yell, "Python!"

and then we're good to go, and we're gonna go get him.

Awesome.

Let's ride.

All right.

♪ See, this is a big part of the story and why there are so many of them out here.

It's so hard to find them, and, yeah, when you're looking down into that water there, there could be a 14-footer sitting in here, and, again, if we blink, we'll miss it.

Looking for a needle in the haystack, right?

Ha ha!

A really big-ass needle.

Ha ha ha!

Yep.

Oh, we got a snake on the road right there.

This here's a brown water snake.

How many wild animals can you think you could do that with?

Not many.

Ha ha ha!

Right?

It's always good to see some natives moving around.

Good to go?

Shane: Yep.

All right.

Let's go get a python or two or 3, heh.

[Insects chirping] [Tape fast-forwarding] I so highly respect these things 'cause they're in an environment that they were put in, and they took over.

We're never going to catch 'em all... Yeah.

but we are trying to slow that expansion.

Oh, will you stop?

Back up just a little bit.

Got something?

Stop.

Uh... Let me go check.

It was down by the trees?

When they feel vibrations coming at them, when they think that there's something's coming at them, they're gonna take off.

♪ There is a gator right there.

You definitely saw a python, though?

♪ If it was a python, it got to the water before we got to it.

♪ Shane, voice-over: To understand how the python problem started, you need to understand the Florida pet trade.

Some of the snakes Donna and I were looking for came from stores a lot like this one in Palm Beach County.

We had a 22-foot reticulated python named Heather.

We named her after my sister, ha ha.

Ha ha ha!

I never really had a fear of big snakes.

[Cash register chimes] Man: ♪ Hey, hey ♪ ♪ OK, let it be known ♪ ♪ I'm workin' hard when I ain't on the phone ♪ ♪ This ain't a huh, this ain't a fold ♪ Shane, voice-over: Hillary Dupont took over the store from her parents, who started it in the nineties.

Man: ♪ Hopefully you understand he already made me ♪ ♪ This cold, I'm talking like no degrees, this ain't a fluke... ♪ Shane, voice-over: Her dad was a herpetologist and zookeeper, so Hillary's been around exotic animals her whole life.

So I grew up back in the day.

I have pictures where my Dad used to bring home the lions and the chimpanzees from Lion Country, back when that was "OK." Man: ♪ ...you in the mood, I been running ♪ ♪ Came out gunning, stop the fronting on ya word ♪ Shane, voice-over: Hillary's bringing up her children in this world, too, and, from what I can see, they're into it.

I mean, really, what kid wouldn't love growing up with all these animals in the family?

[Horse neighs] [Sheep bleats] [Rooster crows] Did a lot of Burmese pythons come through this store?

Were they sold here?

Yeah.

We did.

We had a lot of Burmese pythons come in and out, and people would buy them, and then, of course, when they got to a certain size, they were like, "Oh, where are we going to keep this?"

Where are we going to put this?"

and they would bring 'em back.

Shane, voice-over: But not everyone took their pythons back to the store.

Many dumped them into the closest wetland.

Hillary: Yes.

We're 100% at fault for contributing to that back in the day, but that's where I'm redeeming myself.

Yeah.

Florida Fish and Wildlife called us and said, "Do you want to be a drop center?"

and we said, "Absolutely," and so that's when they started getting dropped to us.

Shane, voice-over: Wildlife drop centers provide a safe place for people to bring unwanted pets, so Hillary's store is a rare place where you can see Burmese pythons kept legally in Florida.

Can I see one of these guys?

You wanna go see one of them?

OK.

I'll bring you over there.

Come on, darling.

Oh, my goodness.

Come on.

Boy's got body, as they say.

Uh-huh.

Ha ha!

Ha ha ha!

This is Satan.

This is Satan?

I know.

It's a horrible name.

Ugh!

He's kind of heavy and lanky.

All right, Satan.

Let's say hello to everybody.

How long is Satan?

He's around 8 feet.

OK, and how old is the Prince of Darkness?

We've had him for around 5 or 6 years.

OK. Shane, voice-over: In a glass cage, these snakes seem harmless, but when they were released into a new environment, the results were devastating.

[Indistinct conversation] Scientists are still trying to understand just how large of an impact they're having.

The animal is a challenge like no other.

There's a lot of surprises.

Yeah.

Shane, voice-over: This is ecologist Kristin Hart of the U.S. Geological Survey.

When she's not chasing personal bests, she's chasing down pythons.

Kristin and Matt McCollister of the National Park Service are part of a team that's trying to learn everything they can about how these snakes live in the Florida swamps.

Today on the to-do list is to check two of our transmitted females.

OK. She was around 125 pounds when she was caught about this time last year.

OK, so how much junk is in the trunk is what we're going out here to figure out.

And collect blood.

OK. OK. [Static] Kristin: This is a basic radio tag.

OK.

It goes actually in the body in a surgery, and then we feed the antenna also right under the skin, and so you can hear it.

Shane, voice-over: The team has radio-tagged over 60 pythons, but they're still learning the most basic facts about this species' biology, like how long they live, how far they move, and how many babies they have, because to control them, we've got to understand them.

And then back in the pine.

Yeah.

Kristin, voice-over: I think they're adapting very well and very quickly here in South Florida.

It is a landscape-scale phenomenon.

[Static] Shane, voice-over: This is not an easy environment to get around in, much less find a snake that doesn't want to be found.

♪ Shane: It makes me realize how large I am as a human being, not exactly built for stealth, but I'm trying my best.

If it was easy, it would have been done before.

Ha ha ha!

Ha ha!

♪ Kristin, voice-over: Burmese pythons are very cryptic.

They are in the canals.

They are on the levees.

They can be up in trees and underground.

[Indistinct conversation] I believe it's right here, just off the signal.

Now, you know, the animal's close to 16 feet long, so it could be in a few places, but if she's in a ball, it's likely right here... Shane: OK. just off where the signal feels hot.

Proves once again why they have been able to conquer this habitat.

Believe it or not, there's a snake here.

Shane, voice-over: The radio tag doesn't lie.

There's a 16-foot python right under our feet.

We just can't get to it.

Unfortunately, y'all have received the typical track experience... [Laughter] and we will have to try another one.

Kristin, voice-over: I mean, I think it's like an alien thing, like, right?

I mean, they lose teeth, and they grow them back.

They have regenerative organ growth, so they can actually-- Like, their heart can shrink, their stomach can shrink, and then they can grow it back.

This is a vast wilderness with lots of prey.

We've seen everything in their diet-- mammals, birds, gators.

Shane: Once gators are on the menu, you've reached official gangsta status.

It's just unbelievable.

Shane, voice-over: Burmese pythons eat prey as small as mice and as large as deer, and in some parts of the Everglades, these mammal populations have dropped by more than 90% from their pre-python numbers.

Matt: She's at the base of this squash myrtle.

Kristin: I see her, I think.

You see it in there?

I do.

Matt: Go and get your blood stuff out.

Kristin: It's moving.

I see it.

You see it in there?

Get the camera right in there.

You see it?

Wanna let her move out?

You ready?

Yeah.

Nah.

She wiggled out.

OK. She's out.

Here's a head.

Head.

Kristin: You stay still.

Stay still.

Back up.

Yep.

Yep.

♪ Want to get blood?

Yep.

Can you give me [indistinct] Matthew?

That's it.

[Hissing] Kristin, voice-over: To touch this animal and feel how muscular the whole thing is...

Giving me all kinds of presents back here.

Kristin: Ha ha!

Kristin, voice-over: you appreciate the beauty of it, but it's also like, "This cannot be out there," I mean, but it is.

You wanna go and cinch?

Cinch the drawstring?

20.1, tare the bag.

Shane, voice-over: It's hard to believe that this 10-foot snake is the smallest python we tracked today.

After taking measurements and collecting blood, the team releases the snake back into the wild.

For Kristin, that's a necessary evil.

It is a big ask to put them back, right, because you have an invasive in your hand-- just put it down; get it out of the system-- but if we do that, we lose the ability to learn.

It is like driving the car while you're building it in many ways.

The rule book is not there for these animals.

Shane, voice-over: The better we understand these snakes, the more likely we are to find a weakness that we can exploit to control them and reduce their impacts.

What is the outlook?

Is the goal, like, eradication?

Is that beyond what is possible now?

Trying to manage and mitigate the impacts that they're having is sort of the shifting, shared goal, I think.

Kristin, voice-over: I love the Everglades.

I have to work on this issue.

Like, I can't back away, as hard as it gets or as frustrating it gets sometimes.

Shane, voice-over: It's too soon to know the ending of this story, but at least most folks agree pythons should go, however daunting that sounds.

Once an invader proves that it's here to stay, the question becomes, what now?

♪ What do you do for a living?

I am a professor at Princeton.

Oh, really?

Yeah.

How'd they trick ya into doin' this?

Shane, voice-over: This is the Redneck Fishing Competition, an event that's quintessentially American, centered around a fish that's definitely not.

We're official.

We're in it, in it to win it.

[Shouts] Woman: ♪ O'er the land of the free and the home... ♪ Shane, voice-over: My guide is Lance Gregerson, a local fisherman.

Lance: And we're off, off like a herd of turtles.

Do you consider yourself a redneck?

Hell yeah!

You proud to be a redneck?

Yeah!

OK!

Shane, voice-over: The goal here is simple-- catch as many carp as possible in mid-air.

You see, when the carp hear a boat, they launch themselves right out of the water, so you could be cruising along, minding your own business, and wind up like this.

Oh!

That was a beamer.

I've been commercial fishin' since I was about 14 years old for catfish and a few other of the normal species that we have around here until these carp showed up.

Shane: Yeah.

That changed everything.

When these became more abundant, what was it like for the local fishermen?

There was nothin' anybody could do with 'em because they're just a pain in the butt to clean.

Shane, voice-over: In the U.S., we like our fish with as few bones as possible, making the bony Asian carp hard to sell as food.

Without a market, carp have overrun these waterways and transformed the lives of people who work and play in the river, but, as always, people adapted.

You get him?

Ha ha!

Good shot.

Hell of a good time.

Shane, voice-over: The tournament's become an annual ritual, but it won't even make a dent in the carp population.

Asian carp reproduce quicker, grow faster, and generally outcompete every other fish in the river.

Today they make up 60% to 70% of the Illinois River's biomass, but how did this fish jump across the Pacific and land here in the first place?

Hey, Andrew.

What's happening, man?

Not too much.

How you doing?

Just went to a redneck fishing tournament, got smacked in the face by a carp.

Ha ha ha!

Shane, voice-over: Andrew Reeves is a Canadian journalist who spent 10 years learning to ride a bike.

Oh, wait.

I read that wrong.

He spent 10 years writing a book about Asian carp.

We have this umbrella term of "Asian carp," but it really doesn't do the individual species justice.

Shane, voice-over: 4 species were imported from Asia to American waters--black, grass, bighead, and silver carp.

Andrew: They were perhaps one of the last invasive species that were actually, like, brought over with the full-throated support of government and the scientific community.

Shane, voice-over: Each species was brought here with a specific job to do, and let's just say the silver carp drew the short straw.

Andrew: You can't just dump solid waste into your local waterway anymore.

You can use these fish to be able to clean up those sewage lagoons.

Just so I'm clear, they wanted to use the carp to eat human waste.

That's right, and around that time, someone also had the idea of, "Could we also eat them if they're eating nothing but, like, human waste?"

Nobody wants to eat poop fish.

No, and this was it, and so they've kind of had this, like, trash-fish reputation.

Shane, voice-over: If the carp had just stayed in their sewage lagoons, we might not be having this conversation, but politics gave the fish an unexpected opportunity.

I would like to have a crusade today, and it would be one to take government off the backs of the great people of this country.

Andrew, voice-over: Ronald Reagan slashed the number of regulations that the EPA could enforce, and essentially all the research that was being done on silver and bighead just evaporated overnight.

All of a sudden, they had tens of thousands of fish and nothing to do with them, so some people essentially opened the sluice gates on their properties, and we're still suffering the consequences of that today.

Shane, voice-over: In just a few decades, carp had spread through the Mississippi River and most of its tributaries.

Today the front lines of the war on carp are just south of Chicago.

Well, what does the fish say when it runs into something in the river?

"Dam"!

Ha ha!

Shane, voice-over: I met Scott Whitney at the Brandon Road Lock and Dam.

Scott isn't just a purveyor of bad puns.

He's also been fighting invasive species for decades with the Army Corps of Engineers.

Scott's marching orders-- use whatever means necessary to stop the carp from entering the Great Lakes, where scientists worry their impact could be catastrophic.

Man: ♪ Let me be your shield, let me be your shield ♪ ♪ Let me be your shield, let me be your shield ♪ Scott: We have one chance to stop that movement at this point.

Shane, voice-over: The Great Lakes wouldn't be at risk if carp were just spreading up the historic Illinois River.

The problem is, we've re-engineered the river, connecting it with Lake Michigan through a massive system of canals and locks.

Now, thanks to us, the Great Lakes are connected to the Mississippi River and its tributaries, all the way to the Gulf of Mexico.

Before Scott and his team build any carp barriers in the real world, they have to test them in the lab.

We have a series of technologies-- sound, bubbles, electricity, and a flushing lock... Like they're literally running a gauntlet.

none of which by itself is a 100% guarantee, but layering them together provides a variety of challenges to overcome.

[Beep beep] They have a unique characteristic between their air bladder and their inner ear.

I call it the echo chamber.

That sound is amplified into their inner ear in a way that causes them to leap out of the water.

You know, they react to noise.

Shane, voice-over: Like, say, the noise of an outboard motor at a one-of-a-kind fishing tournament.

Shane: How much did it cost to build the infrastructure?

Scott: This particular project has about an $800 million price tag right now.

It's a tall order, but the investment right now is the least costly it's ever gonna be.

It's only gonna get bigger from here on.

Shane, voice-over: Time will tell if Scott and his team can keep Asian carp out of the Great Lakes, but in many American waters, they're already a fact of life, so we're getting creative, hence the Redneck Fishing Tournament.

These fish are gonna be turned into fertilizer, but the State of Illinois hasn't given up on carp as food.

As they like to say, if you can't beat 'em, eat 'em.

The new name for Asian Carp is copi.

That's C-O-P-I.

It's short for copious, which is exactly what this fish is.

To test the waters, Illinois is cooking up carp-- I mean, copi-- for one population that's always hungry-- college students.

Shane: You should do the hard part.

I don't want to show you up on TV, so you do the hard part.

Even the hard part I have a hard time, prepping, too, so-- Ha ha ha!

Shane, voice-over: This is Chef Soohwa Yu.

He's got a green thumb, and he's a magician in the kitchen, transforming carp into something folks here on campus actually like to eat.

Man: ♪ We gonna take it to the sky ♪ ♪ Can we give 'em just a little bit more ♪ ♪ Cookin' up that stew... ♪ ♪ Yeah, let it cook... damn slow... ♪ Soohwa: I will show you how to cut, filet this one.

OK.

So, you got to be careful.

There's some bones right here.

It's really heavy bone right here you gotta-- Shane: OK, so you're working around the bone.

Yeah.

That's a thick bone, jeez.

There's a really hard bone right there.

Then you follow the bone, and then you're gonna hear this.

One, two... [Crunch] That's bone.

Shane, voice-over: Chef Yu really knows his way around those bones.

There you go.

Oh, wow.

I've been hearing, like, people talk about how bony the fish is.

Shane, voice-over: Chef Yu has been busy for over half a decade finding tasty ways to serve this fish.

[Sizzling] This is, like, a fried copi, a little savory and salty, and there's bone there.

Just make sure-- OK. Oh, it smells delicious.

Because I'm on a diet, so I had a smaller piece.

Oh, OK.

Dig in.

Let's see what we got here.

So make sure that you don't see any bones on it.

Oh, that's good.

It's succulent.

Yeah.

You definitely gotta make your way around the bones, though, I see.

See, normally, the Asian, what we do is eat the whole fish in the mouth... OK. and you just move it around... Mm-hmm.

Then you work through it.

like this.

Oh, OK. You can't be uppity with somebody pulling bones out of your mouth.

Yeah.

Ha ha!

Shane, voice-over: Carp have been a staple of East Asian cuisine for centuries, and I can taste why.

It's hard to believe Americans haven't embraced this fish and that little bit of extra work it takes to enjoy it.

We're in the Midwest.

We're meat-and- potato guys, but now we have a lot of fish out there, so we have to eat it up.

Oh!

Oh, nice save.

Ha ha ha!

Nice save.

Shane, voice-over: Invasive species like carp are a problem-- don't get me wrong-- but they're here to stay, and it seems to me, there's a solution staring us in the face, but somehow we just can't be bothered to pull a few bones out of our teeth, so instead, we're stuck spending almost a billion dollars on a technological solution to a very human problem.

I'd order copi at a restaurant, but some invasive species just aren't on the menu.

Some species we love so much that we've actually convinced ourselves that they belong.

[Horse whinnies] [Bird screeches] The West is a symbol as much as it is a place... [Whip cracks] and like so many things, our relationship with the West, the story we tell ourselves about it, is full of contradictions.

No species is more emblematic of that tangled relationship or more likely to get you in a shouting match with a stranger... [Horse whinnies] than the horse.

[Insects chirping, creatures howling] Shane: It's like when you think about, you know, like, things that are like quintessentially American, right, you think, like, bald eagles and, like, bison.

Horses just seem to be one of those quintessentially American, but they're not native.

They're not native.

Shane, voice-over: This is Kate Schoenecker.

She's a biologist who studies free-roaming, feral horses.

When she isn't out on the range, she's playing Wordle, very, very badly.

Kate: So, the history of horses is actually really fascinating.

OK.

So, and I-- some of the confusion is because they did evolve in North America.

Shane, voice-over: Horses first appeared in North America about 5 million years ago and spread across the land bridge into Asia, Europe, and Africa.

Then, about 10,000 years ago, they went extinct here, and the Americas were horse-free until 1493, when Spanish explorers brought them across the Atlantic.

Kate: They were artificially selected to be what we needed them to be.

We selected them for high reproduction, we selected them for speed, for long legs.

Shane, voice-over: After thousands of years of selective breeding, modern horses can double their population every 4 to 5 years.

Kate: With feral horses, they get bred when they're 1 and start to have their first foal at 2.

They're like baby machines.

So, they're waiting.

Yeah, exactly.

Shane, voice-over: Despite their numbers, wild horses can be surprisingly elusive.

Kate: Yeah, this is a good spot.

Shane, voice-over: Today Kate's checking on a herd of horses that she's been radio tracking.

This can be the boring part or the exciting part.

[Laughing] OK!

[Static] So, we'll stop and try again later.

OK. Kate: Their population sizes are controlled by predation, which is called top down population control, and bottom up, which is forage availability, which is resource availability.

There aren't many predators these days.

That's right.

That's exactly it.

There aren't enough predators and because horses are not native here, they don't have native predators.

Shane, voice-over: After some driving around, Kate and I finally track down the herd she's been looking for.

Kate: Oh, it's nursing.

That little one is nursing.

Aww, yeah.

See, you can't help but go "Aww..." Right.

Yeah.

It was completely involuntary.

Ha!

Right.

Shane, voice-over: In a landscape like this, water is life.

These horses were here for a drink, but everything else out here is thirsty, too.

Horses outcompete native wildlife for water, and their hooves turn precious watering holes into mud pits.

Shane: Yeah, so, how do you go about managing a population?

Well, what we're doing is, we are testing or lots of scientists, actually, are testing fertility control methods.

And so-- Birth control?

Yeah.

Birth control.

OK. Shane, voice-over: Birth control can slow population growth, but it's a gradual process.

It doesn't fix the immediate problem: all the horses that are already here.

Researchers estimate that there are 3 to 4 times as many wild horses in the West than the land can sustain, but it's not their fault.

Biologically, horses thrive on this landscape.

And culturally, legally, we decided that they belong here... in some ways, even more than our native wildlife.

Federal and state agencies often use lethal removals to manage other wildlife populations, but federal law prohibits the government from using those methods with horses.

♪ Shane: For other species, typically, like, hunting seasons are the solution.

Why not with horses?

I think it's probably like going out and shooting Fido.

It's just not palatable and-- Correct.

OK.

I think it's just not palatable.

OK. Yeah, to see them out in the wild like this, like, you experienced it also.

You know, you think, "Wow, they're beautiful, and, you know, it's so lovely to see them out here."

Yeah.

But we can't let that emotion stop us from doing the management that is necessary.

[Hoofbeats] Shane, voice-over: We call these horses wild, but we don't treat them like wildlife.

We don't let people hunt them, and there aren't enough predators to control their numbers.

So, the government's resorting to some extreme measures.

[Hoofbeats receding] Man on radio: Just make sure nobody moves at all.

[Hoofbeats approaching] Shane, voice-over: I can hear the thundering.

Definitely getting closer.

Woman: All right, everybody, do not move.

[Thundering hoofbeats, horses whinny] Oh, there they go.

[Helicopter blades whirring] It's a little nerve-wracking.

♪ Now, that is impressive.

Shane, voice-over: This is a Bureau of Land Management horse gather, where the government uses helicopters to round up feral horses into corrals.

Man on radio: You guys were good, awesome.

Tell everybody up there thank you.

Shane, voice-over: It's their way of getting these animals off the landscape.

You are welcome.

Shane, voice-over: Amy Dumas runs the Wild Horse and Burro Program for the BLM in California... and horses are her world.

Amy: BLM and the United States Forest Service are tasked by the law to manage these horses on the public land.

Shane, voice-over: In 2022, the BLM gathered 20,000 horses... more than any year since 1985, but that's less than 10% of the total population.

And managing them isn't cheap.

In 2022 alone, the BLM spent $138 million managing wild horses and burros.

Where does the money come from to fund all of this?

It actually comes from me and you, the taxpayers.

[Horses nicker] Now that there are horses penned here, what are the next steps of this process?

We'll take them to temporary holding.

We'll ship them to one of our prep facilities.

Then they are prepared for adoption.

[Horse whinnies] Shane, voice-over: But less than half of the horses are actually adopted or sold.

The rest remain in BLM care or are released back onto the landscape.

Amy: We're trying to do our jobs out here with like one-- hog-tied, right, with one hand behind our back and the other hand "ham strung," because we have to work within our regulations and within our budget.

Shane, voice-over: Watching these beautiful, iconic animals driven into pens by a helicopter, it felt wrong.

At the same time, letting them continue to multiply, to ravage the fragile landscape, to outcompete native species, that doesn't feel great either.

[Horses whinnying] I'm not the only one who's felt conflicted after witnessing a gather.

[Phone ringing] Man: It was the greatest contradiction I'd ever seen, and I thought like, OK, how the heck did we get into this fix in the first place?

Shane, voice-over: This is David Philipps.

When he's not running with his dog on the trail, he's winning Pulitzer prizes writing for the "New York Times."

Watching a BLM gather in 2013 sent him down a wild horse rabbit hole.

The result?

A bestselling book.

Americans, really, we look at things as native and non-native.

You know, what was here before Columbus and the Spaniards arrived, and what did we bring over after?

And a lot of the stuff that came over after we don't give any protection at all: you know, tumbleweed, kudzu, wild hogs, stray cats.

You know, all of that is seen, you know, oftentimes as a problem.

The wild horse is different.

It changed the Plains tribes.

It was the engine of the explorers and the cowboys.

And it just wove its way, you know, very deeply into our idea of who we are ourselves.

Shane, voice-over: But our attachment to horses has gotten us into an impossible situation.

And I think if you told the average person on the street that we have already spent a billion dollars as a people to store wild horses, and we're probably gonna spend a billion more in the next several years, they would look at you like you're crazy.

Wow!

Right?

It's a system that from no perspective makes any sense.

But if there was an easy solution, someone would have already done it.

Yeah.

Ultimately, we're still a bunch of cavemen sitting around a campfire, right?

Ha ha ha!

Story to us...matters, and, you know, what we value and what we do has real effects.

Shane, voice-over: At the end of our call, David asked me, "Is culture biology?"

And I'm starting to realize that it's often hard to tell the difference.

Our desire to keep wild horses in the West might be rooted in our culture, but the outcome is biological.

The consequences of wild horse management and mismanagement are right in front of us.

So what should we make of horses?

Is our love for a species enough to make it belong?

And at some point, does an invader deserve amnesty?

To find answers, I had to look further west and deeper into the past.

♪ [Birds chirping] ♪ Millions of people flock to Hawaii every year to immerse themselves in nature.

[Thunder] Man: So, the beauty in Hawaii is extravagant.

Another myna bird.

They're such beautiful birds.

And I like to keep a daily total sometimes.

Shane, voice-over: Being here, it's hard not to feel like you're in an untouched paradise.

Man: Birds are-- first of all, they're beautiful.

And I would not be good studying mosses.

OK!

You know?

Shane, voice-over: Dan Lewis is an author, historian, and rare book enthusiast.

He's also a bird fanatic.

Dan: Birds are awesome because they don't obey geopolitical boundaries.

They go where they want and need to go.

Shane, voice-over: With all the birds and lush tropical vegetation, this place feels, well, natural.

Dan: It's like a big warm hug.

Mmm.

It's green, it's lush, it's beautiful.

And one of the things that people are struck by is how many different forms of life there are, but they're from other places.

Everything in Hawaii is from somewhere else.

Shane, voice-over: Here on Oahu, it's not just the birds that are non-native.

The plants we passed on our walk, most of the island's insects, and all of its amphibians and reptiles are recent arrivals.

The Hawaiian islands are home to more than 5,000 introduced species.

Dan: Pineapple?

Not endemic to Hawaii.

Pineapple came from South America in the early 19th century.

So you're saying Hawaiian pizza has been a lie this entire time.

Dan: Hah!

It's so funny.

Shane, voice-over: But just like with horses in the West, judging the nativeness of species here in Hawaii is complicated.

[Birds chirping] Shane: So, the myna bird, that is here, is it a native species, or is it an invasive species?

So, there you go.

There's the million- dollar question.

So, the myna bird is considered an invasive species because it comes from somewhere else and it does things that people don't like.

Shane, voice-over: So, they're not from around here, but just as importantly, they get on people's nerves.

Verdict: invasive.

Dan: My mom used to try to run them down in her Corvette.

Run them down literally?

Oh, yeah, she would gun it.

I mean, she would be coming down Halaulani Place in Hilo and she would hit the gas, man.

Shane, voice-over: But once an invasive species has spread and multiplied as much as it can in a new ecosystem, in other words, when it stops "invading," what then?

Dan: You have plants that were pollinated by native birds that now the native birds are extinct so the original pollinators are gone.

Shane, voice-over: But sometimes a non-native steps up.

Dan: The Japanese white-eye pollinates some of the Clermontia, a small flowering plant.

They're a species that are native to Hawaii here.

Shane: Sounds like even these introduced species, they get actually interwoven into the native ecosystems in a way that's hard to pull them apart.

Dan: That's exactly right, Shane.

And in Hawaii, everything is from somewhere else.

[Slide projector advancing] Shane, voice-over: Dan was born in Hawaii and grew up on the islands, but his personal identity?

It's complicated.

Dan: So, you know, I was born here in Hawaii, but I was born as a white person, and I felt like an outsider in a lot of ways here.

You know, I went to a boarding school for 6 years in Hawaii.

It was brutal 'cause I was beat up constantly and that's why, it got me to thinking about how much I belonged here.

You know, to say that you're Hawaiian is a very-- it seems like it'd be relatively concrete, but it is not.

Yeah.

And by the same token, to say something is a native might be easy, but it's not.

Shane, voice-over: Still, there's no question that each time a new wave of species made themselves at home here, more of Hawaii's original flora and fauna disappeared.

Dan: You know, it's the extinction capital of the world.

Shane, voice-over: Hawaii is one of the smallest states, but a quarter of all the species on the U.S.

Endangered Species list live here.

♪ A record of what's already been lost is kept in the collections of the Bishop Museum in Honolulu.

Dan: So, every one of these is a species of Hawaiian endemic birds, and every one of these is extinct.

I want to point out one particular specimen here: the Lana'i hookbill.

And it's the only one.

So, just to be clear, when you say "This is the only one," w-what do you mean?

Like, this is the single, only individual that we know that's representative of the species?

Dan: That's correct.

That is both the first of its kind and the last of its kind.

It's the only one that survived.

I wish you'd told me that before you had me pick it up and hand it to you.

[Chuckling] Shane, voice-over: Over the last thousand years, the Hawaiian islands have seen multiple waves of humans arriving on their shores.

And with each wave of humans came new species of plants and animals.

One of the animals that arrived with the first Polynesians is still thriving in Hawaii's forests.

[Insects chirping] Shane: I took a karate class in 3rd grade, so I'm pretty sure I'm ready for whatever.

Ha!

But, I mean, once you hear the firearm go click, just be ready, there might be a loud boom.

It's game time.

Yeah, so... We're gonna try to do a quick little stalk pass through.

If I can, I'll give you guys a signal, like I'll let you know, you know, "Come up for it," "Stay back."

Should be a good day.

That's good.

Take it easy, easy.

Shane, voice-over: This is Iokepa Paty-Miner... Man: ♪ Uh, ...

I heard they checking for me ♪ ♪ No one checking on me, so I had to go ♪ Shane, voice-over: a native Hawaiian hunter, farmer, and conservationist.

Man: ♪ My attorney gone... put all their egos in check ♪ Iokepa: It's a kind of smell, like when you're in a house of pigs, you can kind of smell them, you know?

Shane, voice-over: Today Iokepa has brought me along on a pig hunt.

Pigs were first brought here by Polynesians as domesticated livestock almost a thousand years ago, but some of them went feral.

[Birds calling] By digging and rooting in the soil, pigs harm native plants, destroy bird nests, and create pools of water where invasive mosquitoes can breed.

So, many people see pigs as a destructive, invasive species and support their full-scale eradication from the islands.

This is a touchy subject for many Hawaiians.

Iokepa: Some places you can see places they've kind of been foraging around trying to dig stuff up.

Shane, voice-over: Pigs have had almost a thousand years to integrate into the ecosystem and into Hawaiian culture, where the pig is embodied in one of their gods.

♪ Iokepa: You know, we're all trying to find home, we're all trying to find our habitat here, you know, wherever we are, and pigs are no different.

Kamapua'a was a creator of land.

He destroyed forests but he also built forests.

♪ That chain that connects us from who we are today, who we were, and who we come from when all this started.

Shane, voice-over: I was learning a lot about Hawaii's pigs, but after a long morning, we came up emptyhanded.

Before giving up, we checked a few traps Iokepa had set in the forest.

Jackpot.

Iokepa dispatched the unlucky pig quickly.

[Gunshots] [Pig rustling] Shane: You know, obviously, you know, there are very quantifiable negative impacts that introduced species can have on habitats, but to see, you know, a life going from is to was is always an intense experience.

Shane, voice-over: On the other side of the property, one of Hawaii's top chefs was waiting for this pig.

Yo, boots on, guys, come on!

Shane, voice-over: This is Kealoha Domingo, a famous Hawaiian chef who's raising his sons to honor Hawaiian traditions, including how to enjoy what the islands have to offer.

Kealoha has been working with Iokepa and dozens of other volunteers to restore an ecosystem and a way of life on a swath of land in northwest O'ahu called Kako'o 'Oiwi.

I was brought up singing "The Star-Spangled Banner" and the "Pledge of Allegiance."

And, you know, these days, you know, my children are singing a different song.

Shane, voice-over: European settlers systematically erased Hawaiian culture, and as a child, Kealoha wasn't even allowed to learn the Hawaiian language.

But here, folks like Kealoha are dedicating their lives to bringing back the language, the culture, and a way of living on the land that honors their ancestors.

While I was hunting with Iokepa, dozens of people spent the day collecting taro, yams, and banana leaves to prepare for a ceremonial meal.

Shane: I notice a lot of folks came out.

Is this typically a community affair?

Kealoha: Yes.

Always, always a community affair.

Almost always.

Shane: Where I come from, like in the Deep South, you know, like, Sunday dinner is the big thing that brings family together.

You know, everybody cooks a meal, you come together, you pray together.

Shane, voice-over: The pig we killed today will be used in a traditional Hawaiian ceremony where they'll be honoring the aina, or land.

Kealoha: What we're building is an imu.

Uh, imu is an underground oven.

Shane, voice-over: Everything that's going into the imu, from the banana leaves to the taro used to make the poi, to the pig we hunted, was harvested right here.

It's tempting to see Kako'o 'Oiwi as a throwback to ancient traditions, but Kealoha explained that their work here is a fusion, combining what's still known of the old ways with the necessities of the present.

Man: ♪ So many speak on the bottom and never know the feel ♪ ♪ Or how it looks at the top or if it's even real ♪ ♪ We ain't selling dreams but we live in some ♪ ♪ No arms license and still we stick to our guns ♪ Woman: ♪ I'm gonna live my life ♪ ♪ I'm gonna live my life, oh, yeah ♪ Man: ♪ We here to live for ourselves first ♪ ♪ And if in doing that it helps you, so be it ♪ ♪ Let it drop, let's go ♪ Kealoha: I don't think we can turn back the hand of time and remove all of the different things that took the place of our natural resources, but it's critical for us to look back into the past to learn for the future.

Shane, voice-over: While the pig cooked, Dan joined us, and the 3 of us sat down over some awa to discuss the idea of nativeness.

Dan: I mean, one of the things that, in thinking about this a lot over the last few years, is that I think people confuse belonging with purity.

Kealoha: I mean, for myself, I'm 3/4 Chinese.

I also have European blood.

And I identify with Hawaiian the most because of the way I was raised.

Dan: Nativeness is a spectrum.

I'm Kama'aina because I was born here, you know?

I'm not Kama'aina in the same you're Kama'aina.

It's a different thing.

I can tell it's a different thing.

I'm, you know, from a European background and I have no Hawaiian blood in me, but I am from here.

I don't think you can deny that I'm from Hawaii.

Shane, voice-over: I'm starting to realize that our perspectives about nativeness are shaped by our own sense of belonging as much as anything biological, whether we're talking about our own species or another.

Kealoha: And for me, the issue with invasive in a setting of natives is when the invasive displaces the native, you know, when you have a weed that grows 25 times faster than a native plant and that plant can no longer thrive.

Dan: At the same time, they're just doing what plants and animals do.

You know, there's no agency to them.

As Mark Twain said, "Nature knows no indecencies.

Humans invent them."

Kealoha: Yeah, it kind of boils down to perception, the personal perception on value.

[Flames crackling] Shane, voice-over: So, how should we value pigs?

They've been in Hawaii as long as people have.

If we call them invasive, what does that mean for the Hawaiians who don't want to see another part of their culture erased?

Kealoha: You know, the pua'a has been a part of our oral traditions, of our history, of our genealogy.

It is an integral part of our story.

Dan: Yeah.

I would have no problem with someone saying, "I vote for the pua'a to be considered a native."

I'd be like, "I'm in."

It belongs here 'cause it's been here for so long and it's been so embedded in Hawaiian culture.

It belongs here.

Do you consider humans an invasive species?

Dan: Oh, my first response is absolutely the most invasive of all species, the most out of all species.

I think there's no doubt about that.

I think it'd be harder for someone to argue that humans were not the most invasive species.

[Laughing] [Wind blowing] [Singing in Hawaiian language] Shane, voice-over: Maybe the reason we have such strong feelings about invasive species is that we see part of ourselves in them.

Because invasions start with us.

They get out of control when we're slow to take responsibility.

And they highlight the uncomfortable truth that humans are quite capable of doing things we can't undo, but that's nothing new.

[Hoofbeats] [Birds chirping] Man: In Hawaiian, we have a saying.

It goes... [Continues in Hawaiian language] When someone would come visit you, they're a stranger for one day.

And after that, you're well acquainted already.

Kama'aina is like, very familiar.

So you're only a stranger for one day, and after that... [Speaking indistinctly] So.

Thank you.

♪ Shane, voice-over: On our hike, Dan shared an old quote with me: "No man ever steps in the same river twice, for it's not the same river and he's not the same man."

What I think Dan was getting at is that even if we could somehow get rid of all the invasive species, we still wouldn't end up with the ecosystems we had at the start.

We can't turn back the clock.

But what makes our species special is that we can see what lies ahead.

And we can protect the things we care about.

We just have to decide what we value, and in the world we want to live in, what belongs.
