---
title: "Human Footprint: Vanishing Act (S2E6)"
---

## Online Access

[Link to PBS Series](https://www.pbs.org/show/human-footprint/)

:::{.column-screen-inset}

<div class="pbs-viral-player-wrapper" style="position: relative; padding-top: calc(56.25% + 43px);"><iframe src="https://player.pbs.org/viralplayer/3102372628/" allowfullscreen allow="encrypted-media" style="position: absolute; top: 0; width: 100%; height: 100%; border: 0;"></iframe></div>

:::

## Transcript

("Ready or Not" by Fugees plays) (Shane) The story of our planet is a tale of equal and opposite forces: Life... (female singer) ♪ Ready or not, here I come ♪ (Shane) ...and death.

We've never known one without the other.

(female singer) ♪ And take it slowly ♪ ♪ Ready or not ♪ (Shane) From the first primordial cell, to the loftiest tree, to beasts we've never known, each species walks its own path... ♪ ...but they all end in the same place.

(female singer) ♪ Ready or not ♪ (Shane) Extinction is Mother Nature's way of pruning the Tree of Life.

(female singer) ♪ Ready or not ♪ (Shane) And she is a tireless arborist.

Ninety-nine percent of all the species that ever existed no longer do.

(female singer) ♪ I play my enemies like a game of chess ♪ (thunder, explosions) (Shane) Of Earth's eight million living species, one has become a force of nature in its own right.

And, ironically, we humans-- the only species that can fathom extinction-- are driving it faster than any other species in our planet's history.

♪ What fate awaits the Tree of Life in the Age of Humans?

And can we change course before putting our future in peril?

♪ Welcome to the age of humans, where one species can change everything, and what we do reveals who we truly are.

This is Human Footprint.

♪ (serene music) For most of our history, the world was a pretty scary place.

Colossal predators hunted massive herbivores.

And we were definitely on the menu.

(roaring) ♪ Today, there aren't many places where the land still pulses with the ancient rhythms of giants.

(animals grunting) Where you're grateful for the safety of a safari vehicle.

People travel thousands of miles to experience Africa's megafauna, yet these iconic animals are dwarfed by the titans that roamed North America in the not-so-distant past.

♪ ("To Live & Die in L.A." by Tupac Shakur plays) (engine revving) The sprawl of L.A. feels a world apart from the Serengeti... (Tupac) ♪ It never rains in Southern ♪ ♪ To live and die in L.A. ♪ (Shane) But if you want to meet the giants that once ruled this continent, this is the place to do it.

(chorus) ♪ To live and die in L.A. ♪ (vocalizing) (Emily) This is my favorite critter here.

This is a giant ground sloth.

(Shane) Yeah, what makes this your favorite?

(Emily) It's a sloth and it was giant.

(laughter) (Shane) Need you say more?

(bicycle bell rings) Meet paleontologist Emily Lindsey.

Her commute through L.A.'s urban jungle helps her connect with the present... (relaxing music) ...but when she gets to the La Brea Tar Pits, her thoughts turn to the ancient world.

♪ (Emily) This is called a short-faced bear.

(Shane) The idea that there was an animal this large is deeply disturbing to me.

How much bigger is this than, like, a polar bear?

(Emily) A lot.

(laughter) ♪ (Shane) Today, La Brea is almost as iconic as Disneyland or Hollywood, drawing visitors from around the world.

But at the start of the 20th century, people flocked here for another reason.

(Emily) The L.A. basin is the richest oil basin of its size in the world.

In the early 20th century, we were producing about a quarter of the world's oil.

(Shane) In those days, Rancho La Brea was a rich source of the densest form of crude oil: asphalt.

(Emily) They were digging it up and shipping it up to San Francisco, where it was being used to pave the roads.

(Shane) In some places, finding asphalt didn't even require digging.

(Emily) And because the other thing we have a lot of in L.A. is earthquakes, there are places where these fissures occur in the ground.

(Shane) Here, the asphalt seeps up to the surface in shallow, sticky pools.

Before long, miners noticed bones-- a lot of them.

They assumed the bones belonged to cattle from the ranch they were digging on until a traveling geologist took a closer look.

(Emily) And he was like, "That's not a cow bone."

It was the saber of the saber-toothed cat.

Exactly what part of the cow do you think this came from?

(laughing) (Emily) Over time, plants, animals, big, small, get stuck in there.

(Shane) At La Brea, the miners had stumbled onto the world's largest deposit of Pleistocene fossils-- an entire ecosystem sealed in an asphalt time capsule.

Soon, a new kind of excavation was underway.

(Emily) In about two and a half years, they collected about a million fossils.

Whoa.

(rhythmic music) Is, like, this density, like, normal for the pits?

(Emily) Yeah, it's just bone on bone, on bone, on bone, on bone.

It makes them really challenging to excavate.

♪ So, imagine playing, pick-up sticks.

But every stick is, like, a different size and shape and also fragile and also priceless.

And then, somebody has dumped a bunch of cement on top of it.

(Shane) In the last century, scientists have excavated over five million fossils here, representing 40,000 years of ecological history.

(Emily) This is our dire wolf wall.

So, there's 400 skulls of dire wolves on this wall.

That represents maybe 10% of the dire wolves that we've discovered so far at the tar pits.

(serene music) (Shane) Thousands of apex predators died in the pits, along with the massive herbivores they hunted.

Then, suddenly, mysteriously... the megafauna stopped getting stuck.

(Emily) Through intensive radiocarbon dating, we were able to figure out exactly when they stopped getting stuck, which is a proxy for when they stopped being on the landscape.

So, these are the very last animals of their kind that we know of at La Brea, and in many cases, in all of North America.

This is the last dire wolf.

(Shane) Like, the last.

The last one that we know of.

(Shane) Wow.

(Emily) 13,000 years ago.

The last saber-toothed cat that we know of, 13,000 years ago.

This is a piece of the last American lion.

-13,000 years ago?

-Yeah.

13,000 years ago was a bad year.

So, what happened 13,000 years ago?

Gosh.

(Emily) So, this is a Columbian mammoth and these are one of the species here that we know overlapped with and interacted with the first humans in the Americas.

We find a lot of mammoth kill sites.

(Shane) It takes a brave person to point to one of these things and say, "You hungry?"

(Emily) Yeah.

(laughter) (Shane) Humans are brave.

We're also smart, social, and skilled at making and using tools, which is why, in the late 1960s, paleontologist Paul Martin proposed an idea to explain these extinctions: the "overkill hypothesis."

(dramatic drumming music) (Emily) We know that humans are perfectly capable of hunting species to extinction.

(Shane) Before the overkill hypothesis, experts attributed the loss of North American megafauna to the end of the last Ice Age.

But Martin questioned how these animals had survived so many previous warming periods, only to vanish when humans arrived.

Overkill had an intuitive appeal amidst the growing environmental movement.

It was easy to envision us hunting species to extinction.

(Emily) One of the counterarguments is, well, you know, these small bands of hunter gatherers couldn't possibly have, like, driven all the mammoths to extinction.

(Shane) Megafauna kill sites do exist, but they're rare.

And it's not just species that ancient humans hunted that vanished, lots of other plants and animals disappeared in the same timeframe.

So, what really happened?

(Emily) The problem is that when you have two things happening at pretty much exactly the same time, you need a really high-resolution understanding.

(Shane) La Brea provides that high-def view of a long-gone ecosystem.

Emily and her team used radiocarbon dating to determine the precise timing of each species' disappearance, then compared those dates with data gathered from lake-bottom sediment cores, which record climate and vegetation before and after the megafauna disappear.

(Emily) For about the 2,000 years leading up to that, we were going through some pretty substantial climate change.

(Shane) As the Ice Age ended and the ice sheets receded, the climate got warmer and drier.

(Emily) We have multiple mega-droughts that last decades at a time.

We see half of the tree species start to die off.

So, the landscape is becoming more open and drier.

Megafauna populations are decreasing, and then, about 13,200 years ago, something really remarkable happens.

Everything catches on fire.

(flames hissing) (Shane) How do they know this?

Because fire leaves behind charcoal.

So, the amount of charcoal in any layer of a sediment core is a good indication of how much fire was happening.

(Emily) The first 20,000 years of that core record, there's, like, essentially no evidence of fire.

There's very, very little charcoal in that record.

(Shane) But over time, more and more charcoal appears in the cores.

(Emily) And then we see an order of magnitude increase in the charcoal, right around 13,200 years ago.

(flames hissing) (Shane) For 400 years, fires engulfed California again and again, burning its forests into charcoal we would discover 13,000 years later.

(Emily) And when we come out of it, we are in a completely new ecosystem.

The large mammals are gone.

This is when we see the modern flora of coastal Southern California, the chaparral, which is an assemblage of fire-adapted species.

And humans are common on the landscape.

(Shane) So, what caused the fires?

(Emily) We don't really get lightning here.

We don't really have naturally occurring fire, and in fact, 97% of wildfires in Southern California today are caused by humans.

The most powerful tool that humans have ever invented is fire.

We use it to cook our food, we use it to keep warm, to have light in the dark.

So, humans are spreading in an ecosystem that is really prone to fire.

It's ready to go, but there isn't an ignition source until humans bring it into the ecosystem.

That is a plot twist I was not expecting.

It's really shown me the degree to which humans can have really large-scale impacts on ecosystems, unanticipated impacts, especially when combined with climate change.

(flames hissing) (Shane) That combination sounds uncomfortably familiar today.

(haunting music) (Emily) Extinctions didn't stop happening at the end of the Pleistocene.

Scientists usually define a mass extinction as 75% or more of all species going extinct.

Okay.

(Emily) And there have been five of these so far.

And the most recent one was 66 million years ago.

There's a lot of discussion about whether the biodiversity crisis that we're experiencing today will result in the sixth mass extinction.

(Shane) If it does, it'll be the first mass extinction caused by a single species.

In the past 200 years, we've pushed more than 900 species over the brink--a rate up to a thousand times faster than the natural pace of extinction.

♪ Nearly 50,000 other species are considered threatened by the IUCN.

And few animals are at greater risk today than the megafauna that survived the end of the Pleistocene.

(birds chirping) The story of one of those species starts where you'd least expect.

(serene music) With more than 650 species-- many rare or endangered-- the San Diego Zoo offers a window into our planet's living diversity.

But behind the public exhibits, there's another zoo with specimens found nowhere else.

(Marlys) So, these are our cryo tanks, this is where we keep the samples, living dividing cells from all of the 11,000 individuals and 1,300 species and subspecies, all in primarily three tanks.

("Got 'Til It's Gone" by Janet Jackson, Q-Tip, and Joni plays) (Shane) If the Frozen Zoo had a zookeeper, it would be Marlys Houck.

♪ Her bespoke beaded wine glass charms keep her guests from mixing up their drinks.

(female singer) ♪ Don't it always seem to go ♪ (Shane) And that attention to detail pays off at work, too.

♪ (Marlys) So, in there is the liquid nitrogen.

Each one of these vials contains about one to three million living cells.

(Shane) Oh, wow.

Today, the Frozen Zoo is the largest, most diverse, and longest-running cryobank in the world.

But when it started in the 1970s, its ambitions felt like science fiction.

(Marlys) It was started by Dr. Kurt Benirschke in 1975.

He had the idea that because we had this new technology where you could grow cells from skin biopsies that we should do this and bank them because we don't really know how technology will evolve in the future and what those cells could be used for.

(Shane) The samples here aren't just on ice.

While many of the animals they came from are dead, the cells stored here are very alive.

(Marlys) If you just take a skin biopsy and throw it in the freezer, it will form ice crystals.

And the ice will pierce the cell membrane, destroy the cell, it will no longer be living.

So, we have to go through this process of adding a cryoprotectant.

It's kind of like an antifreeze... and then they have to be frozen at -196 °C in liquid nitrogen.

And they're just resting there without aging.

And then, when we pull them back out, they start growing and dividing again.

That's incredible.

Marlys joined the Frozen Zoo because of her concern for one species in particular.

(Marlys) When I came, there were probably 60 northern white rhinos.

I never would have thought when I first came that I would be watching the extinction of one of the animals I was working with.

(Shane) But that's exactly what happened.

So, this box is really special.

Maybe you can read what species?

(Shane) Northern white rhino.

(Marlys) Right, and these are not just any northern white rhino, they are Sudan, the last male of the species.

(downbeat music) Put that on... and then you can just go like that.

♪ You are holding living cells of Sudan, the last male northern white rhino of the species.

What does that feel like?

Really intense, actually.

Wow.

(sighs) -Thank you.

-Yeah.

♪ (Shane) His cells may still be alive, but Sudan, the rhino, died on the other side of the globe, with the whole world watching.

♪ (Zach) I've been looking after these northern white rhinos for 16 years now.

I consider these rhinos as my second part of my family.

("Guess Who's Back" by Rakim plays) (male singer) ♪ Yeah ♪ (male singer 2) ♪ Once again, back is the incredible ♪ (male singer) ♪ It's the return of the... ♪ (Shane) Meet Zach Mutai.

(male singer) ♪ Smashin' hits, make it hard ♪ He started here as a fence builder, but soon became a ranger, and eventually, a caregiver to the last northern white rhinos.

(male singer 2) ♪ Incredible, the incredible ♪ (Shane) The day Sudan died, Zach was by his side.

(Zach) I spent, like, nine years taking care of Sudan until he passed away on 19th of March day of 2018.

(camera snaps) (melancholic music) (Shane sighs) That must have been a really intense experience.

Yeah...it was such a difficult day.

It was really sad.

Losing a rhino to me is more like losing one of my family members, and it was really such sad news by losing the last male of its kind.

It really shook the whole world.

(news anchor) The world's last surviving male northern white rhino has died.

(dramatic music) (Shane) Ol Pejeta is one of the world's most important wildlife conservancies.

Yet even here, under constant surveillance, rhinos aren't always safe.

(clicking sound) ♪ At the turn of the 20th century, half a million rhinos roamed Africa and Asia.

But wars, habitat loss, and most of all, poaching for their horns caused catastrophic declines.

Driven by false beliefs of rhino horn's healing powers and its luxury status, illegal markets have fueled a deadly trade.

Today, only 5% of rhinos that existed a century ago remain.

The last wild northern white rhinos were killed in the early 2000s.

In a desperate attempt to keep the species alive, conservationists transported the final captive individuals from a zoo in the Czech Republic to create a breeding program here.

Among them were Sudan and two females.

(Zach) So, this is Najin, uh, the mama, and her daughter Fatu is the other one.

And this is their friend, a southern white rhino.

-Okay.

-Yeah.

She's a good friend and a trainer for them because these two, they were raised in captivity and they never know how to do all natural things like grazing, socializing, and all other natural activities.

Hi, good girl.

I know.

Have you ever feel and touch a rhino?

(Shane) No.

(Zach) You can just come closer to me, you can just feel.

(serene music) Kind of here, just.

♪ It's quite soft behind the ears but the rest part of the body is quite rough and thick skin.

(Shane) Yeah.

♪ (Zach) Fatu, no.

I think I just fell in love.

♪ (Zach) Fatu, good girl, Fatu.

♪ (Shane) This is one of the most incredible experiences.

(Zach) Could you imagine that you are watching the last two of their kind?

(Shane) Yeah, that's... (Zach) And they are being killed only for the two horns and nothing else.

(Shane) Yeah.

(Zach) We have got only the last two in the whole entire planet.

If anything happens and they are gone, there will be no more northern white rhinos species.

I've come to realize that extinction is something real, and we have just learned that we are the most dangerous creatures on this planet, yeah.

(rhino grunts) ♪ Man, this... this is intense.

And... you can't help but look at these... just big, beautiful animals and just... like, what... what do we do?

How did we get here?

♪ We are a hell of a conundrum as a species.

One hell of a conundrum.

♪ Just like, we've had so many opportunities to correct our actions, like-- (rhino farting repeatedly) (farting continues unabated) Wow.

That's impressive.

(soulful music) Even if there were a male of their kind, Najin and Fatu aren't healthy enough to have babies.

But that's not stopping scientists from trying this species alive.

(Dr. Florence) Every experience I have is so surreal.

It's so amazing to be working with such big animals.

So, you basically have the coolest job in the world.

(Dr. Florence) Mm-hmm.

(laughter) (Shane) As one of Ol Pejeta's resident veterinarians, Dr. Florence Kang'ethe has a big job.

From health check-ups with the conservancy's anti-poaching dogs, to wound care with a blind and very grumpy black rhino, her to-do list is long.

At the top of it is saving the northern white rhino.

("If I Ruled the World" by Nas playing) (Dr. Florence) Today, I had to be here early to do stimulations.

So, that involves me injecting a hormone.

(Shane) Dr. Florence is part of a groundbreaking initiative that aims to bring baby northern white rhinos back into the world.

Using cryo-preserved sperm from deceased males, researchers fertilize eggs collected from the last females to create embryos, which they can implant into surrogate females of the closely related southern white rhino.

♪ (Dr. Florence) It's sad that we have come to that point where we have to do such efforts, but we're quite hopeful that soon we shall be talking about a northern white rhino baby running around, yeah.

(Shane) If, for whatever reason, the northern white rhino were to go extinct without a baby coming to be, what will we have lost?

We would have lost the chance to redeem ourselves.

(soulful vocalizing) (Shane) The people fighting to save these rhinos embody humanity's compassion for wild species, yet this species' story also reveals our capacity and willingness to destroy them.

♪ And while losing a rare species like the northern white rhino is a tragedy... ♪ ...losing an abundant species can unravel the fabric of an ecosystem.

(percussive hip-hop music) ♪ (Sara) You always like it when you can't get your arms all the way around it, right?

(assistant) I know, that's a good sign.

(Sara) Beautiful.

(Shane) This is Sara Fern Fitzsimmons.

Her love of spreadsheets-- used for everything from planning family weekends to tracking her hikes-- is matched only by her passion for a tree whose ghost still haunts Eastern forests.

(Sara) The American Chestnut Foundation is a nonprofit organization dedicated to restoring the American chestnut back to its original range.

(serene music) (Shane) American chestnuts once numbered in the billions.

They sustained wildlife-- from deer to turkey, and black bears to passenger pigeons-- and they were the foundation for an entire subsistence culture in Appalachia (Sara) So, I grew up in southern West Virginia, and they called it a cradle-to-grave species because it could be used for cribs, coffins, and everything in between.

(Shane) But the American chestnut can't do any of those things anymore.

The chestnut blight put an end to all that.

(Sara) The chestnut blight is a fungus.

Um, and it was brought over in the 1800s.

(Shane) The blight hitchhiked here on another chestnut species imported from Asia for landscaping.

And exactly what does the blight do to the tree?

(ripping sound) (Sara) The cambium tissue of a tree is its living layer; a fungal spore can get in, germinate in that tissue.

It completely strangles the tree by eating the tissue around it.

It's pretty gruesome, actually.

(Shane) It sounds like a horror movie.

It really is.

(Shane) The fungus was discovered in 1904, and it spread fast.

(Sara) By 1950, pretty much the entire range from Maine to Georgia had become infected and all the big trees had--had succumbed.

(Shane) Today, the scale of that loss is hard to comprehend.

(Sara) It's approximately 180 million acres.

And, in some locations, especially Southeastern Pennsylvania, some areas of Massachusetts and Virginia, it was as much as 50% of the forest.

(Shane) Today, some of those places are still covered in trees... but without the chestnut, it's not the same forest.

No one alive remembers the forest that was.

Some of its parts remain, but the ecosystem is gone.

For the chestnut as a tree, it's more complicated.

(Sara) So, the American chestnut is not technically extinct.

But, it's functionally extinct.

There's an estimated 400 million sprouts out there on the landscape.

(Shane) But Sara's using the word "sprouts" in the same way that a zombie "sprouts" from its grave.

(Sara) So, this is a pretty classic oak-hickory forest type.

Back in the day, chestnuts would have covered this forest.

(Sara) Here's a perfect example of an American chestnut that has died back and then is sending up these new re-sprouts.

(Shane) This definitely isn't a normal sapling.

(Sara) So, the roots are probably older than the blight.

(Shane) Because chestnut blight doesn't attack the roots.

(Sara) So, this is still original genetics from when the blight first swept through.

It'll die back, it'll re-sprout.

This will continue forever, I imagine.

(Shane) It's like a very sickly phoenix that keeps rising.

(Sara) There you go.

I like that.

-Okay.

-Yeah.

(birds chirping) (Shane) This little tree-- through a series of past lives, each cut tragically short-- might have been here longer than the blight has.

(Shane) God, this is weird to look at.

The sprouts rarely get large enough to produce nuts because the blight is never far away.

(Sara) Even when the tree dies, the fungus is still around, just, you know, spewing spores into the, into the atmosphere.

(Shane) But that doesn't mean the American chestnut is doomed.

Sara and her colleagues are trying to breed a better chestnut-- one that can hold its own against the blight.

(Sara) You say, "Well, this tree looks really good, it has really good resistance.

This tree looks really good, it has good resistance."

And then you have to put that together and see if you can build that up in the population.

(Shane) So, where can you find these genes for resistance?

One strategy is to look for the rare American chestnut that's doing more than just sprouting and dying.

A new find in Central Pennsylvania might be the biggest chestnut tree in the state.

(Sara) There we go.

Ha ha!

Look at that.

That's awesome.

So, these two are good and then that one's, that one's a dud.

(cameraman) That's exciting.

It's very exciting.

We grow the tree up, we take the fungus, we put it in the tree and we say, did it survive?

(Shane) It's painstaking work, made possible by an army of volunteers.

(man) .3, Sara.

(Shane) Another source of potential blight-resistant genes are Chinese chestnut trees, which evolved with the fungus and are naturally resistant.

Scientists are hybridizing the two species, trying to breed trees that are mostly American, but have the disease resistance of the Chinese species.

Some chestnut researchers are even using genome editing, although the exact genetic causes of resistance are still mostly unknown.

(smooth bass music) The chestnut's allies aren't taking anything off the table.

(Sara) It's not that it's an American chestnut and it's got, uh, you know, waving an American flag and has eagles flying over, you know, it's not that which we are trying to, you know, restore into this tree.

It's its ecological function.

Can it feed the insects?

Can it produce the nuts that all of our wildlife wants to eat?

(serene music) (Shane) Sara knows that American chestnuts won't reclaim their former glory in her lifetime.

That kind of success could still be generations away.

But that doesn't make her, or the chestnut's other champions, any less devoted to the cause.

(Sara) In this world of instant gratification, I think having something that's more of a slow movement, I think that that's kind of refreshing.

(Shane) And it's the least we can do for a species that's fighting so hard to keep going.

(Shane) Are there any American chestnuts that existed before the blight that are still, like, adult trees now?

(Sara) We think we know of about four that survived the original pandemic.

Four?

Oh, God.

(Sara) It's not, so, from an estimated four billion, I mean, those aren't great odds.

(Shane) But one of those one-in-a-billion trees-- surviving despite the fungus growing under its bark-- stood alone in a farmer's field, not far away.

What are we all here for, if not to serve a function?

So, to be functionally extinct, to be around but serve no function... somehow seems sadder to me than just being gone.

You think about forests that contained billions of these trees, and now this is one of a handful of this age.

♪ I mean, yeah, one of four.

♪ When chestnuts vanished from Eastern forests, a whole ecosystem was lost to human memory.

An interdependent web of life, built around a single "keystone" species.

♪ For generations, humans have played a similar "keystone" role on the lands they call home.

♪ But with Earth's cultures disappearing as fast as its biodiversity... these fading connections leave some species in even greater peril.

(deckhand) To the right of that shiny spot.

Making giant splashing-- look at that!

(Giles) Yeah, that's whales.

Good eyes.

Okay.

Everybody hang on.

(Shane) This is Deborah Giles, or as most people know her, Giles.

She's been studying orcas, also known as killer whales, for nearly 20 years.

But it's her newest assistant who might just be the team's MVP.

♪ (dog barks) (Giles) She's trying to orient to smell.

(Shane) Okay.

(Giles) And then, as we're coming into the scent cone, she'll move to the front of the bow, she'll start maybe whining.

(Shane) Okay, but she's basically your poop compass.

(Giles) She is our poop compass.

The tip of her nose is gonna point us at that smell.

(Shane) Okay.

(Giles) And then she's working for playtime, that's her reward, is playtime.

(Shane) Aww.

You heard that right.

The hero of Giles's research is an Orca-poop-sniffing pooch named Eba.

(quirky music) ♪ (Giles) We go in and we collect the scat sample off the water.

♪ (Shane) Whale poop can yield a smorgasbord of data with minimal disturbance.

DNA identifies the pooper, while other tests paint a detailed picture of the whale's diet, hormones, and overall health.

Giles is monitoring these orcas, a distinct population known as the southern resident killer whales-- because they're in deep trouble.

(Giles) So, 70% of the females in this population who are getting pregnant are unable to bring their calves to term.

So, they're miscarrying or the baby is born alive and dies right away, 70%.

How long is an orca pregnant before she gives birth?

Seventeen months.

(Shane) Wow.

Long time.

(grim music) (news anchor) A mother orca whose calf died after birth is still carrying her baby, 17 days later.

♪ (Shane) The southern residents aren't the only orcas in the Salish Sea, but they are the most endangered.

(Giles) By far the biggest problem is the lack of prey.

(Shane) Most orcas hunt other mammals, but the southern residents prefer fish.

(Giles) The fish eaters are dictated by what mom says, what grandmother says.

These are matriarchal societies.

(Shane) The southern residents are particularly reliant on Chinook or King salmon, which have declined by more than 90% in the last century.

Without the salmon, orca mothers are starving and many can't carry their babies to term.

Despite legal protection, the population is still dwindling.

(melancholic music) When I visited, there were just 73 left.

(Ellie) We're a perfect triangle.

We call orca Quahamitchdon.

So, us, Quahamitchdon, and salmon, we need all three to be able to survive.

(Shane) Quahamitchdon are more than neighbors.

(Ellie) We believe they've just put on their underwater regalia and they've become Quahamitchdon.

Hmm.

(Ellie) So, they are just members of our family.

(Shane) Ellie Kinley is a member of the Lummi Nation.

(mellow music) When she's not working on a beautiful flower arrangement, you might find Ellie on her boat-- fishing in waters that the Lummi, the orca, and the salmon all call home.

(Ellie) I just love the fact that there is no word for famine or starvation in our language, because we never starved.

(Ellie) A lot of our stories talk about all our creeks and rivers being so full of salmon, you could walk across their backs.

(Shane) Whoa.

(Ellie) We've always had plenty from the Salish Sea.

(solemn music) (Shane) But in the past century, dams, pollution, development, and overfishing have decimated the salmon runs, while many Lummi fishers have been displaced from their traditional fishing grounds.

And the Lummi's underwater relatives faced another threat.

(news anchor) The so-called "killer whale" was the first of the whale family to be successfully kept in captivity.

(Shane) In the 1960s and '70s, amusement parks and aquariums were stocking up, and the southern residents proved easy to catch.

At least 50 orcas, including babies, were captured for aquariums around the world.

A female named Tokitae was kept in a tiny tank at the Miami Seaquarium, mostly alone, for more than half a century.

For the Lummi, the story is painfully resonant.

(Ellie) The aquarium was the residential school.

She was taken there, and the savage was taken out of her.

She was taught to perform.

It's the same thing our children went through.

(Shane) Like other indigenous children in the U.S. and Canada, Lummi children were often sent to boarding schools with the explicit goal of forced assimilation.

(teacher) Now, let's pick up where we left off yesterday, with the English lesson.

(Shane) As Ellie sees it, the Lummi and their underwater family have both suffered the same trauma.

And it's only by repairing that trauma and restoring their connection to the Salish Sea that both can thrive again.

(Ellie) Family takes care of family.

So, it's our job to make the Salish Sea healthy enough to provide for us all again.

(Shane) That means rebuilding the legendary salmon runs that once sustained the orca and the Lummi.

(tranquil music) (Ellie) We're still the biggest tribal fishing fleet in the nation, but we were once twice the size.

♪ What you see is people that aren't fishing.

There's a lot of broken people.

♪ -I know where home is.

-Mm-hm.

And when I get there, I know it.

I can just stand on the bow of my boat, and I just feel it.

♪ There has never been a generation in my family that hasn't fished.

(Shane) Mh-hm...never.

♪ Yep.

♪ (Shane) In the Salish Sea, a culture was born of this place and the creatures who share it.

The erosion of that culture puts species at risk just as surely as the loss of those species diminishes the culture.

Our ties to other life run deep.

It might be why extinction feels so wrong.

But look around, and it kinda feels like humans are just getting started.

Whether by ignorance, apathy, or greed, we don't have any trouble ending another species' journey.

Which is why, for some, preventing extinction just isn't enough.

(Beth) We get drawings from kids every week of pictures of mammoths and dodos and thylacine.

Some of them are good, some of them are not.

(laughter) (Shane) This is Beth Shapiro.

She's trying to put the pieces of lost ecosystems back together using biotechnology to undo extinction.

Beth is chief science officer of Colossal Biosciences, a startup that's captivated the world with their goal of reviving extinct animals from ancient DNA.

Sound familiar?

("Jurassic Park" soundtrack plays) (Beth) There's no DNA in dinosaurs, we can't do that.

(Shane) I'm never gonna get Jurassic Park?

-No, I'm sorry.

-Okay.

A flesh-and-blood T. rex is still firmly in the realm of sci-fi.

But Colossal is working on species that disappeared more recently.

(news reporter) At Colossal Biosciences in Dallas, the mission is clear.

(researcher) We are less than five years away from seeing mammoths back on the planet.

(Shane) When Beth wrote her first book in 2015, she was...ambivalent about de-extinction.

(Beth) I thought that... it's a little far-fetched.

Probably too hard, probably too many technical, ethical, ecological hurdles that need to be overcome.

(Shane) But her perspective has evolved.

(Beth) As we make these advances, we are creating new tools that can be applied to stop extinctions from happening today.

(Shane) High on Colossal's list is a species I got to know at the La Brea Tar Pits.

(wolf howling) In April 2025, Colossal announced the birth of three puppies, which they described as the first living dire wolves in 10,000 years.

They hailed the achievement as "the world's first de-extinction."

But a lot of scientists cried foul.

Were these really dire wolves?

(Beth) It is never going to be possible to bring back a species that is 100% identical in every way, genetically, physiologically, behaviorally, to a species that is extinct.

(Shane) In this case, the team created the so-called dire wolves by cloning cells from modern gray wolves, with DNA edited to give them dire wolf-like traits.

The goal isn't so much to bring back lost species as it is to create new ones to do the same job.

(Beth) I think it's about interactions in ecosystems, so, I don't care what species is there that's doing this really important role, as long as it's there.

(Shane) Some of Colossal's critics say, "Okay...then why dire wolves?"

Their Pleistocene ecosystem is long gone.

(wolf howling) But Beth points out that it's big flashy species like the dire wolf that make this work possible.

(Beth) It is incredibly hard to raise money to do conservation work.

(Shane) Yet Colossal is doing exactly that.

(Beth) That is new money, tech money, that's directly going to develop tools that we can use to stop species from becoming extinct, and that is really what I think an incredible benefit of the idea of de-extinction is.

It's energizing.

(Shane) But not everyone is convinced that de-extinction is a goal worth chasing.

(phone ringing) (Christopher) If we bring them back, can we ensure that they stay alive this time?

There's no good evidence that we can do that.

("Born to Roll" by Masta Ace plays) (Shane) This is Christopher Preston.

When he isn't prepping for mountain bike season, Christopher teaches environmental philosophy at the University of Montana.

He's thought a lot about extinction and why it matters.

(Christopher) In some ways, what you're losing when you lose a species is you-- you're losing a thread.

You're losing a DNA thread that goes back in time over tens of millions of years, sometimes.

If you put an end to that continuous chain back into the past, you've lost something really that has philosophical value, and arguably, something that has moral value, too.

(Shane) Our species has proven all too capable of breaking those chains, but we can't necessarily repair them.

(Christopher) To make restitution to a species, that thing has to be around, but it's not around anymore.

So, what exactly are you making restitution to?

I don't think we're making things right again.

(Shane) But even skeptics understand why de-extinction has gotten so much attention.

(dark music) (Christopher) That word "extinction" has such a central place in the whole environmental discussion.

♪ It's the worst of all environmental sins, and we all know extinction is forever, right?

And so, if someone walks in the room and says, "Hey, extinction, it's not forever," we're gonna look up, and we're gonna get excited.

(moody music) (Shane) Will de-extinction become part of our conservation toolkit?

I honestly don't know.

But what would it look like if it did?

What if someone really did bring back a mammoth?

♪ African elephants are among the woolly mammoth's closest living relatives.

And a big reason why they're endangered is that they're not so easy to live with.

Just ask folks in Kenya who have them as neighbors.

To me, they are good animals,1000 (Shane) David Mwiti has been farming on the edge of Kenya's Lewa Wildlife Conservancy for 30 years.

("Jamboree" by Naughty by Nature feat.

Zhané plays) (male singer) ♪ I want to see y'all who wanna plan with me ♪ ♪ Wave your hands across the land ♪ ♪ If we family ♪ ♪ Say hot damn ♪ (Shane) Most of his neighbors rely on their farms to make a living.

So, when elephants raid their fields, the results can be devastating.

(Shane) Whoa.

(Shane) And hungry elephants aren't just destructive, they're dangerous.

-Okay.

-Yeah.

(Shane) But everything's different now.

(serene music) (Shane) Okay.

(Shane) This electrified fence keeps most elephants out of the village and out of harm's way.

(Shane) Nearby, an elephant underpass prevents deadly vehicle collisions on the highway.

These huge infrastructure investments are part of a bigger strategy to make human-elephant coexistence possible.

("Fight the Power" by Public Enemy plays) (male singer) ♪ Let's get down to business ♪ ♪ Mental self defensive fitness ♪ (Shane) Meet John Pameri, head of general security at Lewa Conservancy.

The way John takes care of himself, you'd never know he's been working here for 30 years.

♪ As human and elephant populations have grown, managing conflict between the two has gotten more demanding.

(Shane) Some elephants cause more problems than others.

(elephant trumpeting) GPS collars allow the team to monitor the habitual troublemakers 24/7.

(Shane) Yeah.

(calm music) (speaking foreign language) That monitoring effort is just one part of a comprehensive security operation that John oversees.

(phone beeping) (Shane) When the call comes in, a human-wildlife conflict team deploys to defuse the situation before it escalates.

The ops room can also rapidly mobilize anti-poaching units.

But Lewa's strategy isn't just reactive, it's proactive, too.

The Conservancy has spent decades building goodwill with the surrounding communities-- digging wells, constructing schools, and creating good, reliable jobs, all funded by conservation.

(Shane) It's been really successful, but also hugely expensive.

If the elephants were gone, do you think farmers, like, would they be upset about it?

Would they be happy about it?

(Shane) It all makes me think again about mammoths.

(deeply percussive music) If we brought them back, could we coexist with them?

-Mmm.

(Shane) Here in Kenya, people are keeping megafauna alive in a fast-changing world.

But it means doing things differently.

(Christopher) I think behavioral change is difficult.

If someone comes along and says, "Hey, I can fix that for you, and you don't have to change a thing," that is going to be very appealing.

(Shane) And that might be why de-extinction gets so much attention.

The same day Colossal made its "dire wolf" announcement, critics of the U.S.

Endangered Species Act claimed that de-extinction-- not regulations that protect wildlife-- could become the bedrock of species conservation.

Could the promise of a techno-fix for extinction change how we value our fellow species?

(Beth) It's a good question, and I think it assumes both something beautiful about humanity, but also something that's wrong.

And that is that most people value biodiversity now.

I think most people don't value biodiversity or think about extinction, and I worry that that's a problem.

(solemn music) ♪ (Shane) Beth might be right about a lot of folks, maybe even most.

♪ But everywhere I've gone, I've met amazing people taking extraordinary measures to keep species from disappearing.

♪ (Christopher) Humans, unlike other species, can choose to do differently.

If we can put empathy at the center of our world, I think that helps in human relations and it helps in our relationships with the natural world.

So, let's choose to do something differently.

(Shane) We're living in a new age of extinction, one crafted by our own hands.

It might be the first time one species has snuffed out so many others.

♪ But we're also the first of this planet's creatures to grasp the consequences of our actions and to consider changing our ways.

I want to believe that we can turn the tide, that we can keep wild species from going over the brink, or maybe even bring them back.

If we act thoughtfully, empathetically, and urgently, maybe our species will redefine the legacy we leave on all the others that share our one incredible planet.

