---
title: "Nature WILD HOPE: Road Warriors"
---

## Online Access

[Link to PBS Series](https://www.pbs.org/show/nature/)

:::{.column-screen-inset}

<div class="pbs-viral-player-wrapper" style="position: relative; padding-top: calc(56.25% + 43px);"><iframe src="https://player.pbs.org/viralplayer/3096575801/" allowfullscreen allow="encrypted-media" style="position: absolute; top: 0; width: 100%; height: 100%; border: 0;"></iframe></div>

:::

## Transcript

♪ (birds chirping) ♪ ♪ (Fernanda speaking Portuguese) ♪ (birds chirping) ♪ (truck horn honking) (Fernanda speaking Portuguese) (horns honking) ♪ (Fernanda speaking Portuguese) ♪ ♪ (cars driving by) (Fernanda speaking Portuguese) (birds chirping) NARRATOR: Worldwide, roadways are a lethal threat, killing hundreds of millions of animals each year.

The crisis intensifies when rapid development hits biodiversity hotspots like Brazil.

Today, more than a million miles of roads stretch across the country, and that human connectivity comes at a high cost to wildlife.

♪ (Fernanda speaking Portuguese) (car driving by) NARRATOR: On Brazil's roads, vehicles kill nearly 9 million mammals every year.

10 years ago, biologist Fernanda Abra decided to do something about it.

(Fernanda speaking Portuguese) ♪ (traffic) (Fernanda speaking Portuguese) NARRATOR: When Fernanda's team finds a fatality, they do what they can to find a silver lining.

(Fernanda speaking Portuguese) NARRATOR: The samples are sent to research partners who analyze the animal's DNA, providing insights into the genetic diversity and health of the puma population.

More importantly, they're taking steps to prevent these deaths from happening in the first place.

(Fernanda speaking Portuguese) ♪ NARRATOR: This proactive approach is key to their mission.

(traffic) (traffic) The goal: to provide safe passage for animals looking to cross.

For more than a decade, Fernanda's team has been plotting where animals are most frequently hit.

Then they work with the government and private sector to create wildlife crossings in the danger zones.

(Fernanda speaking Portuguese) ♪ NARRATOR: They've built more than 300 underpasses, many of which get tricked out with camera traps.

(Fernanda speaking Portuguese) ♪ (grass rustling) ♪ NARRATOR: Findings show that underpasses like these can cut road deaths in half for medium and large-sized mammals.

♪ (Fernanda speaking Portuguese) (trickling water) ♪ NARRATOR: In just seven years, they've documented about 50,000 safe crossings by a wide range of creatures, including ocelots, porcupines, and pumas.

(crickets chirping) ♪ (crickets chirping) ♪ ♪ That's a lot of lives saved, but in some spots, it's not just about preventing death by collision.

Many animals here like howler monkeys, tree sloths, and kinkajous rarely descend to the ground.

For these tree dwellers, the roads act as barriers, trapping them in fragments of forest.

♪ (Fernanda speaking Portuguese) NARRATOR: That leaves them cut off from food and mates, making them more vulnerable to inbreeding and disease.

Today, nearly 40% of Brazil's primates are at risk of extinction.

(birds chirping) But Fernanda is proving that her animal crossings can help here too.

(truck engine rumbling) ♪ (Fernanda speaking Portuguese) ♪ NARRATOR: Fernanda's team has developed treetop overpasses from affordable local materials, anchored securely to concrete poles.

They test different designs side by side.

(birds chirping) ♪ (Fernanda speaking Portuguese) (birds chirping) ♪ ♪ NARRATOR: There's no question the animals are enjoying the fruits of her labor.

(capuchin monkey breathing and chirping) (truck horn honking) (Fernanda speaking Portuguese) ♪ NARRATOR: She's not alone.

Around the world, communities are collaborating and advocating for all kinds of crossings that allow animals to find safe passage.

♪ (Fernanda speaking Portuguese) ♪ ♪ ♪ ♪ ♪ ♪