---
title: "Nature WILD HOPE: Seabird Sanctuary"
---

## Online Access

[Link to PBS Series](https://www.pbs.org/show/nature/)

:::{.column-screen-inset}

<div class="pbs-viral-player-wrapper" style="position: relative; padding-top: calc(56.25% + 43px);"><iframe src="https://player.pbs.org/viralplayer/3089471188/" allowfullscreen allow="encrypted-media" style="position: absolute; top: 0; width: 100%; height: 100%; border: 0;"></iframe></div>

:::

## Transcript

♪ JAY: Before humans came here, there were so many.. that they would blacken the skies.

You could not see the stars.

But these days, we have changed all the habitat, and their numbers are greatly reduced now, but they're still here.

(bird squeaking) ♪ ♪ There's been a huge number of people coming t.. to figure out how can we benefit all of these species.

(bird calls) ♪ ♪ (bird calls) JENNI: Seabirds are often referred to as ecological engineers.

They feed on small fish, and squid, which are really high in nutrients, and then when they return to land to breed, they deposit these nutrients back into the environment.

NARRATOR: Seabirds live along coastlines and open oceans all over the world.

They've pioneered volcanic islands like Hawaii, since the land first rose from the sea, helping life take hold by depositing mineral-rich guano that became the first soil.

JENNI: They were the first ones here to bring the nutrients to help the plants grow, to start the whole island ecosystem.

NARRATOR: Seabirds continue to provide a critical link between land and water, but today, these oceangoing travelers are under threat.

JENNI: Populations have declined almost 70% since the 1950s, and this is a result of many different threats that seabirds face, both at land and at sea.

NARRATOR: Every year, commercial fishing kills hundreds of thousands of seabirds by accidentally hooking them, or entangling them in nets.

But it's during their short but critical time on land, that the birds are most vulnerable, when they return to breed at the sites where they were born.

On the island of Maui, one seabird, the 'ua'u kani, or wedge-tailed shearwater, lost a beachfront rookery to human encroachment.

JENNI: This was historically always a nesting site for the 'ua'u kani and through human development, it turned into the resort center with condos and other development, and the 'ua'u kani were not present there for many years.

NARRATOR: Humans brought other threats as well: invasive hunters.

JAY: Originally, habitat change was the most significant change for the bird's environment, but now the predators are the major .. for these birds when they're on the land.

All of these birds evolved over their entire millennia of life without having predators to deal with.

(rat rustling) ♪ NARRATOR: Non-native predators like rats and mongooses have decimated seabird populations.

They dig into the birds' burrows, and eat their eggs and chicks.

♪ JAY: All of these predators were introduced by people.

The very early ships came, and rats ran off of the ships when they were tied to shore.

Cats came.

The mongoose were actually introduced to control rats in the sugarcane fields.

♪ JENNI: In 2001, there were very few 'ua'u kani burrows out there.

NARRATOR: The nesting site that once supported thousands of birds was down to just 16 nesting pairs.

Then, one local resident decided to do something about it.

JENNI: There was a local fisherman that had noticed carcasses of the 'ua'u kani turning up when he would go out to fish, so he contacted the State Department, and they implemented a predator control program.

NARRATOR: Government agencies teamed up with volunteers from the community to target non-native predators.

JENNI: We bait these live traps and we check them every day, and then when the free-ranging cat, or the mongoose gets captured in the trap, we remove it from the colony.

NARRATOR: They also installed signs and fencing to steer people away from the nesting site.

Over the years, Jenni and her team have seen the impact of their efforts.

JENNI: When we come back year after year, we're able to see that this is the same pair that was here last year and the year before.

And so we see in this area it's very dense.

We see burrows just right on top of one another.

You get more and more burrows every year.

NARRATOR: But not all seabirds on Maui can find the natural habitat they need to nest.

Critically endangered 'A'o or Newell's shearwaters, prefer burrows beneath ferns and tree roots on steep slopes.

So Jay Penniman and his team at the Maui Nui Seabird Recovery Project are taking an innovative approach, creating a custom-made refuge tailored to the birds' needs.

♪ Here on the northwest slopes of Maui, at a place called Makamakaole, they've transformed land previously used for cattle grazing into a seabird safe haven.

JAY: The major predator control effort here is this predator-proof fence.

The enclosures have a hood, that prevents animals from being able to climb over them.

They have mesh that's small enough that the mice and the rats cannot get through.

It has a skirt that goes under the ground.

(birds chirp) NARRATOR: But guarding against invasive predators is just the first step.

The team also works to restore native plants the birds depend on.

JAY: The fences went up, and then we immediately started working on rehabilitating the habitat, trying to take out the invasive plants and to encourage the native plants that were remaining to continue to grow.

NARRATOR: Most critically, they hope to reestablish the iconic 'Ohi'a tree.

Its roots provide structure for the seabirds' nests, and its high tops are perfect takeoff spots.

JAY: The birds will actually climb the 'Ohi'a trees and get up to where they can leap off and just catch the wind underneath their wings.

(birds chirping) NARRATOR: Today, volunteers help restore this critical native habitat.

MARTHA: I've been working with a group called the Native Hawaiian Plant Society.

This morning I started working with clearing and making space for the native 'Ohi'a lehua to grow.

NARRATOR: Until the 'Ohi'a trees mature, clearings leave room for takeoff and artificial burrows stand in for the trees' roots providing an ideal place to nest.

The refuge just needs one more thing: seabirds.

And nothing works better to draw them in, than birds of a feather.

♪ JAY: Seabirds are social animals.

They want to be near others of their same kind, and if they see a decoy, a bird that looks like themselves or another seabird, then they're more likely to come in.

NARRATOR: They enhance the con with a siren's call for the 'A'o - the sounds of other Newell's shearwaters.

(bird calling) MARTIN: They hear those vocalizations as they fly by, and they see the decoys on the ground.

We find that the nests that are occupied first are the ones that are most adjacent to the speakers, and if they find those suitable, and start breeding there, you have a colony.

NARRATOR: That new colony is taking hold in the enclosure where a couple dozen birds now return to breed.

(bird calling) Jay and his team have gotten to know one pair in particular.

JAY: An adult in here been sitting on that egg, for about 52 days.

The egg is pipping.

It has a cracked open part of the shell, and we could hear the chick peeping within there.

(bird chirping) MARTIN: Sweet.

JAY: It's pipping.

MARTIN: Did you hear it?

JAY: Yes.

MARTIN: Awesome.

JAY: I hear it chipping.

MARTIN: Ni.. JAY: This pair that has been breeding in here, this will be their third chick raised in this colony.

(bird calling) This is definitely a sign of hope.

This is exactly why we are here, is to have these birds being able to successfully breed and build their population.

(bird calling) NARRATOR: In time, these chicks may also return here to raise another generation.

(bird calling) ♪ Thanks to this newly fashioned habitat on the mountains, and one reclaimed along the highly developed coast, both of these shearwaters now have safe harbor on the very islands they helped bring to life.

JENNI: 20 years ago, walking through Hawea, there wouldn't have been any seabirds here.

We wouldn't have had any nesting 'ua'u kani in their burrows.

And now 20 years later, there are now over 3000 nesting burrows at Hawea.

There are literally thousands of seabirds underneath.

NARRATOR: These efforts here aren't just local successes.

They're also models for how communities elsewhere can make space for wildlife.

JENNI: Seabirds can be very successful and coexist in areas where humans also are very successful.

We just have to pay attention to where they are, give them their space so they can set up their burrows and raise their chicks.

In return, the seabirds provide us with the joy that comes from being part of this native ecosystem.

We can use it as an example to show people how just a little bit of effort can result in such a huge success.

(bird chirping) ♪ ♪ ♪ ♪