here::i_am("helpers/render_syllabus_figures.R")

course <- str_extract(params$course, "\\w+(?=_)")

learning_outcomes(params$course) %>% gtsave(here(paste0(course, "/figures/syllabus/learning_outcomes.png")))
grade_breakdown(params$course)   %>% gtsave(here(paste0(course, "/figures/syllabus/grade_breakdown.png")))
resources(params$course)         %>% gtsave(here(paste0(course, "/figures/syllabus/resources.png")))
logistics_card(params$course)    %>% save_html(file = here(paste0(course, "/figures/syllabus/logistics.html")))
instructor_card()                %>% save_html(file = here(paste0(course, "/figures/syllabus/instructor.html")))
resource_card(params$course)     %>% save_html(file = here(paste0(course, "/figures/syllabus/resources.html")))
project_details(params$course)   %>% save_html(file = here(paste0(course, "/figures/syllabus/project_details.html")))
missed_exams(params$course)      %>% save_html(file = here(paste0(course, "/figures/syllabus/missed_exams.html")))
exam_format(params$course)       %>% save_html(file = here(paste0(course, "/figures/syllabus/exam_format.html")))
prep_quizzes()                   %>% save_html(file = here(paste0(course, "/figures/syllabus/prep_quizzes.html")))
activities()                     %>% save_html(file = here(paste0(course, "/figures/syllabus/activities.html")))
class_culture(value_list)        %>% save_html(file = here(paste0(course, "/figures/syllabus/class_culture.html")))
engagement()                     %>% save_html(file = here(paste0(course, "/figures/syllabus/engagement.html")))
late_work()                      %>% save_html(file = here(paste0(course, "/figures/syllabus/late_work.html")))
accommodations()                 %>% save_html(file = here(paste0(course, "/figures/syllabus/accommodations.html")))
plagiarism()                     %>% save_html(file = here(paste0(course, "/figures/syllabus/plagiarism.html")))
titleix()                        %>% save_html(file = here(paste0(course, "/figures/syllabus/titleix.html")))
inclusion_office()               %>% save_html(file = here(paste0(course, "/figures/syllabus/inclusion_office.html")))
other_notices()                  %>% save_html(file = here(paste0(course, "/figures/syllabus/other_notices.html")))
