---
title: "A New Inferno"
profile:
  - "film"
  - "hhe"
categories:
  - "film"
  - "ENVN4320"
---

**Jonathan Pickett**, *09-13-2026*

## Documentary Film (00:15:42)

<iframe title="vimeo-player" src=https://player.vimeo.com/video/1226433979?h=016606b872 width="640" height="360" frameborder="0" referrerpolicy="strict-origin-when-cross-origin" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share"   allowfullscreen></iframe>

## Description

Filmed during the hottest days of Phoenix, Arizona’s summer heatwave, A NEW INFERNO follows paramedics as they race to save the lives of heatstroke victims using a radical new treatment: ice immersion therapy.  As featured on the NY Times Op Docs — We Are Living in a New Inferno  World Premiere SXSW Film Festival, 2026  Featuring Jason Smith, Jake West, Roy Lewis, & Colter Fosdick Directed & Produced by Nita Blum-Reddick & Jonathan Pickett Executive Producers Sam Osborn, Alejandra Vasquez, & Jesse Ray Sheps Cinematographer Ryan Dent  Editor Jonathan Pickett  Composer Jack Gillette Production Sound Mixer Daniel Reddick  Grips Stephane Strande & Brian Osback Sound Design & Mix Hansdale Hsu Colorist Keyhan Bayegan Production Assistant Camden Smith Title & Poster Designer Jason Cryer Weather Consultant Jorge Torres Advisors Dr. Charles Finch, Medical Director, Phoenix Fire Department & Maki Lloyd, Deputy Chief, Phoenix Fire Department  For The New York Times Op-Docs: Associate Producers Ingrid Homquist & Rebecca Shaid Producer Yvonne Ashley Kouadjo Senior Producer Andrew Blackwell Executive Producer Alexandra Garcia  Please consider supporting the ongoing work of Circle the City: www.circlethecity.org  Festivals: • Tribeca x NYT Op-Docs • Mountainfilm • Rooftop Films • Palm Springs International ShortFest • Indy Shorts Film Festival • HollyShorts Film Festival • Nashville Film Festival • Bend Film Festival • Mill Valley Film Festival • Sidewalk Film Festival • deadCenter Film Festival • Ouray International Film Festival • Cinema Columbus • AfterImage Film Festival • Coast Film Festival

## Transcript

