---
title: "The Urban Jungle"
profile:
  - "film"
  - "hhe"
categories:
  - "film"
  - "ENVN4320"
---

# Human Footprint  The Urban Jungle  Season 1

>Episode 5 of Human Footprint (Season 1)
>- *Released: 2023-08-02*
>- *Duration: 00:54:41*

[***More details on pbs.org***](https://www.pbs.org/video/the-urban-jungle-7grk9d/)

<iframe width="560" height="315" title=Human Footprint  The Urban Jungle  Season 1 allow="autoplay; encrypted-media; fullscreen" allowfullscreen="" src=https://player.pbs.org/portalplayer/the-urban-jungle-7grk9d/?uid=2486c076-d951-436d-bf82-bac59b0b60f5&amp;userPassportStatus=yes&amp;callsign=KUON&amp;station_id=b107784d-680c-48d5-8d48-ccb870cbb9dc&amp;unsafeDisableUpsellHref=true&amp;autoplay=true&amp;unsafeDisableContinuousPlay=true\></iframe>

## Description

Shane explores three thriving urban species and envisions a wilder future for our cities.

## Transcript

Shane, voice-over: Once upon a time, the Lenape called this place "Manahatta."

A land of densely forested hills and slow-flowing streams... ...it was, as Henry Hudson wrote in 1609, "as pleasant a land as one need tread upon."

Today, all that remains of that place is the ground I'm standing on.

Rakim: If you was born in New York City Let me year you say, "You know that" Crowd: You know that!

In just a few hundred years, we cut down the forests, rerouted the streams, and leveled the hills.

In their place, we constructed a labyrinth of tunnels and pipes beneath a grid of asphalt streets lined with towers of concrete, glass, and steel.

In the blink of an eye, "Manahatta" became Manhattan.

Nas: Yeah, yeah Nas: Yo, black it's time word?

Today, half of all humans-- more than 4 billion people-- live in cities.

But they're not just a place to live.

Cities are a new ecosystem spreading across our planet.

One made by us, for us.

So how is this purpose-built human habitat treating us?

And what will it take to keep these urban jungles wild?

Nas: To the New York state of mind [Horns honking] Welcome to the Age of Humans... where one species can change everything and what we do reveals who we truly are.

This is "Human Footprint."

The idyllic Manhattan of yesteryear was shaped by beavers, hydrological engineers whose vast earthworks transformed the entire ecosystem.

We humans alter the landscape, too.

We just do it bigger.

Humans have been called the ultimate ecosystem engineers.

And here in New York City, our talents are on full display.

Chorus: In Napoli where love is king When boy meets girl Simmering beneath this iconic skyline is a melting pot of more than 8 million people who speak 200 different languages and eat at over 1,400 pizzerias.

Man: As a New Yorker, I always lean towards pepperoni.

Shane: I can respect that.

Shane, voice-over: Bobby Corrigan is one of those 8 million New Yorkers.

He loves everything about this place: a good slice of pepperoni, the city lights, and, oh, yeah...rats.

In college, I had to save money, so I took a job as an exterminator.

They put me in the sewers right away... and I thought, "Oh, this is cool."

Literally working your way from the bottom up.

Exactly.

Shane, voice-over: Bobby spends his free time writing poetry on the street, but by day, he's a world-renowned urban rodentologist.

Are rats the scourge that people make them out to be?

I admire them.

I respect them.

However, they live in dirty areas.

Shane, voice-over: And, uh, that dirt got cooties.

It's viruses, bacteria, fungi, protozoans.

55 different diseases.

55?

55.

Wow.

OK. And think of the plague, Shane.

You know, I mean, 25 million people go down with the black rat and their fleas.

Yeah.

Shane, voice-over: No place needs Bobby's expertise more than New York, where it seems like rats are pretty much everywhere.

Here we are, sitting at a restaurant.

If that door over there is not pest proof into the pizza shop, across the kitchen counter, and urinates and defecates and leaves a film, and then someone touches the film the next morning, and then, you know, boom.

This pizza's tasting a little less good now.

Ha!

Yeah.

Shane, voice-over: It was time to walk off that pizza on what Bobby calls a rat safari.

We're gonna cross over here, Shane.

There's a park here.

Here we are, almost at the end of June.

You know, their breeding season is in full swing.

Love is in the air.

Love is totally in the air, and families are growing.

Narrator: We know that rats are the most prolific of all mammals.

A single pair of rats would become 360 million in the short space of 3 years.

As the sidewalks begin to deteriorate, the rats will move below the sidewalks for their burrows.

You're literally sometimes walking right over the tops of the heads of rats.

Sometimes, rats will go right up the tree if there's a bird nest up there.

They're predacious on those birds.

Is the reason why you're wearing the hard hat because a rat might jump out of the tree onto you, and is that something I need to worry about?

Actually, that would be cool if they would jump onto me.

I'd like that a lot.

[Laughs] Shane, voice-over: The longer rats live in our cities, the better they get at it... and the harder we try to keep them out.

Here we have something that's very common: the bait box.

The rats will go inside that box and find the poison bait.

And 8, 9, 10 days later, they die.

Shane, voice-over: But no matter how much poison we throw at the problem, we're also throwing rats a lifeline.

Bobby: The rats are gonna be where the food is easy to get to.

All they have to do-- 50 feet away, right there.

Shane, voice-over: New York City has 25,000 restaurants-- not counting the pizzerias-- and millions of home chefs.

3 nights a week, every one of them puts their trash not in a dumpster, not in a can with a lid, but right on the curb.

Bobby: Food in a big city of high-density humans?

Extremely reliable.

So this becomes, like, basically the rat buffet.

It does.

Shane, voice-over: They say if you can make it here, you can make it anywhere.

And rats...well, they made it.

But how did they get here in the first place?

[Squeaking] Man: If we want to know the story of rats in New York City, we have to know what were they doing before they got here.

Shane, voice-over: This is Jason Munshi-South.

He's a biologist who loves New York City almost as much as he loves rats.

[Ships' horns blare] When the brown rat made it here, it sort of hit the jackpot.

Shane, voice-over: The brown rat, or Rattus norvegicus, probably originated in East Asia, where it was first drawn to human settlements by agriculture.

But as people around the world moved into dense cities full of trash, human waste, and safe hiding places, rat populations soared.

Without meaning to, we built a rat paradise.

Narrator: Rats don't have to go to much trouble to find homes because we provide these for them, made to order, everything but the welcome mat.

It's like, "Oh.

There's this massive free food here now, and all I gotta do is hang around these people."

Shane, voice-over: At the height of European imperialism, rats were already entrenched in cities and ports across the Old World.

So when European explorers sailed west into the unknown, rats did what they've always done and came along.

Where we are now is where the Dutch bought the island or stole the island.

I put my money on stole, but go ahead.

But the original... Shane, voice-over: By the early 1900s, it wasn't just white human settlers who'd colonized all of North America.

It was also rats.

But not all rat habitat is created equal.

I'm gonna show you some different pressures in different parts of the city.

OK. We're gonna go get that New York City tour.

Yeah, let's do it.

All right, awesome.

[Engine revving] [Woman singing indistinctly] Jason: Yeah, as you're driving from Battery Park, where the rats first came in, up to here, you know, this is one of the great rat neighborhoods of the world.

[Shane laughs] Shane, voice-over: But if you keep rolling north, the whole vibe changes.

And Jason's got the data to prove it.

Jason: We got basically about 70,000 points where rats have been identified.

And this is the outcome of the map, where the green areas are really good rat neighborhoods, like where we are right now, right about there, near Tompkins Square.

But then see this red area here south of Central Park?

-Uh-huh.

-That's Midtown, where there isn't a lot of residential.

The companies pay extra money to have the streets cleaned up.

And it seems to create this almost, like, dead zone for rats.

Shane, voice-over: Jason can predict the size of rat populations in different neighborhoods by looking at data on humans.

Jason: Areas that are highly residential and mixed commercial that have a lot of restaurants, super predictive of rats, not surprisingly.

And older neighborhoods with older buildings, they really like that.

Shane, voice-over: The places where rats have food to eat and places to hide are the places they thrive.

On the flip side, take those things away and the rats disappear, too.

It seems so simple.

And yet, somehow... Bobby: Go to any city around the world and it's plagued with rats.

We are not winning this war.

Shane, voice-over: Rodenticides, or rat poisons, have become a go-to weapon in the war on rats.

But rats are becoming resistant, pushing people to switch up the formula and apply even more rodenticides to keep rat populations in check.

And it's not just poisons.

Our campaign against rats has grown into a $3 billion-a-year effort, involving legions of people around the world.

We've even conscripted other species into the war effort.

[Indistinct chatter] All right.

So this is our service center.

Shane: It's like the gym, playhouse, sauna, exercise room, all together.

OK. All together, all together.

Shane, voice-over: When Scott Mullaney and his wife Angie aren't cruising down a scenic highway... [Revving] ...they're training little dogs to do a big job.

[Engine revs, tires squeal] Instead of poison or traps, their company uses dogs to kill rats.

It's actually nothing new.

As cities grew bigger and denser in the 19th century, rat populations exploded, and people created whole new dog breeds just to kill them.

We've worked them on top of 12-story buildings.

We've worked them in supermarkets.

We've worked them on airplanes.

We've worked them on trains, on trains, planes, and automobiles.

I mean, really, any environment you can think of.

Shane, voice-over: Over the years, Scott and Angie's small team has killed more than 30,000 rats.

Scott: All right, you're gonna leash up.

Here ya go, kid.

There ya go.

Dogs always give 100%.

They just love what they do.

We're just gonna finish up so we can close up and go.

Last but not least.

[Engine starts, revs] [Distant siren] [Squeaking] OK, guys, so what we're gonna do is, we're just gonna take the leashes off the dogs.

I want to start right over here.

And you can see his kinetic energy.

He just-- he's on point right now.

He knows what the deal is.

Take the leash off and unleash them now.

Shane: It's game time.

Scott: OK, we got something over here!

[Growling] Angie: Wooo!

Shane: Wow!

Scott: Good job.

This is bananas.

Shane, voice-over: It looks like chaos, but this is actually highly coordinated.

The dogs find the rats with their keen noses.

The handlers move dumpsters and pallets to expose them, and the dogs finish the job.

Yep.

Inside the bait box.

Shane, voice-over: Oh, and the hockey sticks?

Those are for cutting off escape routes.

Angie: Wooo!

Ohh!

Shane, voice-over: The dogs look like they're having a blast.

The rats?

Well, not so much.

Scott: It's still alive.

Hold on for a second.

Shane: Oh, my God!

Angie: Hey!

Scott: Yep.

Yeah, just make sure that nothing takes off the other way.

Angie: Good job, guys!

Scott: OK, we've got something over here, I think.

[Soft crunching] There are things that I have seen that I cannot unsee, and I will be having a whole different kind of nightmare from now on.

[Both laugh] What do you think our situation with rats says about us?

I think it's pathetic.

As long as human beings continue with their sanita-- poor sanitation habits, OK, and their lack of concern, we will never get rid of rats.

They're here to stay.

Shane, voice-over: When people come together to live in cities, we create the perfect environment for rats.

They've been living with us for centuries.

When European settlers brought them to the New World, rats just had to keep doing what they were best at to thrive here, too.

But further south, in the Caribbean, another species is evolving before our very eyes to fit into an ever-more-urbanized world.

[Horn blares] Juan Ponce De Leon founded the settlement that became San Juan, Puerto Rico, in 1508, making it one of the oldest colonial cities in the Americas.

500 years later, that tiny colony has grown into the third-largest city in the Caribbean Islands.

But amazingly, you can still see native wildlife here.

If you walk through the city, you'll just see them on everything.

Shane, voice-over: Kristin Winchell is an expert in urban evolution.

She studies lizards called anoles, which live all over the American tropics.

For Kristin, anoles aren't just a scientific inspiration.

They're also her artistic muse.

[Foamer sputtering] So for you, I guess first of all, what is the greatest animal, and why is it anoles?

Ha ha!

I don't know.

They're just fantastic, little critters.

They're so expressive and so charismatic.

And, I mean, they're also great for scientific study.

Shane, voice-over: If you can't tell, I'm a big anole fan, too.

I used to catch them as a kid in South Carolina and I've been studying them since grad school.

In fact, Kristin and I actually work together on anole research here in Puerto Rico.

So of all the places to study these lizards, why cities?

But I feel like most people, they're like, "OK, I want to study them, like, in forests," and things like that.

You decided to go study them in the city.

It was because I was looking for a species that might be adapting to urban environments.

I came across anoles and started reading about their rich evolutionary history and rapid change after you modify the environment.

Shane, voice-over: Anoles might seem like unlikely science heroes, but biologists have been studying them for decades and published literally thousands of papers on them.

There are more than 400 species of anoles that live throughout the Caribbean, Central and South America, and the Southeastern U.S. And I just had this moment where I was like, "If this is happening, it's in these guys."

Shane, voice-over: Once you know what you're looking for, anole adaptations can be easy to spot.

You see, species that live in different habitats have different traits: big toe pads that help them stick to leaves in the treetops; long legs that allow them to run fast on the ground; short legs that help them climb without falling on the tiniest twigs; and so on.

Kristin's question was, which of these traits, if any, would help anoles survive in the city?

Kristin: All right, let's find some lizards.

Shane, voice-over: Kristin and I study the Puerto Rican crested anole.

Step one is to find out whether urban and forest anoles are different from one another.

Kristin: Say it, and the lizard gods will deliver.

Yeah, there's a female right there.

Shane, voice-over: So we hit the streets to catch some lizards.

Kristin: Oh, she's squirrely.

Shane: You're too slow, K. Stop embarrassing yourself on TV.

I had one and then I let--yeah, OK.

Thanks, Shane.

Ha ha ha ha!

That's real nice.

Invite me on your show and then make fun of me.

Shane: Ha ha ha ha!

Shane, voice-over: Catching anoles is a delicate scientific process involving a fishing pole and some string.

Luckily, I came prepared... maybe a little too prepared.

Who comes out catching anoles in flip-flops?

This is how you catch urban anoles!

You don't need those big boots.

[Laughs] You go out in your hiking boots and your field clothes, well, you're gonna get a lot of looks.

You dress casual like you're going out on-- for a little walk, even bring a little boom box with you.

That helps a lot, 'cause no one walks around doing sketchy stuff listening to reggaeton.

Kristin: Got him first.

Shane: Ha ha ha!

Hey, bud.

We measure with a digital X-ray the--all the bones in the body.

And you can see that they have these enlarged toe pads on the fore and the hind feet.

And so if you were to zoom way in on those, you'd be able to see these tiny scales, and those let the lizards cling to the smooth surfaces.

Shane: So for the Puerto Rican crested anole, what did you find?

One of my initial findings was that in the city, the lizards had longer limbs relative to their body length, larger toe pads with more of these specialized scales on the toe pads.

OK. Shane, voice-over: These are exactly the kinds of adaptations you might expect to see in cities, based on what we already know about anoles living elsewhere.

Kristin: They're clinging to things like glass and metal and even painted concrete, which is a lot smoother than anything you find in the forest.

And so there's kind of this combined selective pressure on toe pads, making them able to cling better, and limb length, making them able to navigate the structural environment better.

OK. Shane, voice-over: The urban lizards were different, but the real test was whether they could actually outperform their forest-dwelling counterparts when facing a uniquely urban challenge.

So I set up a lizard racetrack, and I fitted the racetrack with different surfaces.

One was tree bark, one was metal, like fence post metal, and then one was painted concrete.

And then I took high-speed video of these lizards racing up the racetracks.

And what I found was-- or what I expected, rather, I should start there, is that the urban lizards would be able to run faster on the concrete and the metal and the urban substrates.

Those are the environments that they were living in.

Yeah, exactly.

And so they'd be better at doing that than the forest lizards.

What I found, though, was that the urban lizard's just faster overall.

On anything.

On anything.

Even, like, bark and stuff that's in forests.

Yeah, even bark, no matter what angle, no matter what structure we put on the track surface, they were faster.

They're just hot rods.

Mm-hmm.

Shane, voice-over: In grad school, I studied how anoles in Texas-- where the Polar Vortex causes rare but intense cold snaps-- were adapting to the cold.

When I found out about Kristin's work in cities, I realized her urban anoles could be facing a different kind of extreme.

Kristin: When I came down and tried out this big idea of "are anoles adapting to cities," one of the things that I measured was body temperature and air temperature.

Shane, voice-over: Cities create what scientists call "urban heat islands," areas with much hotter temperatures than the surrounding landscape.

So a few years ago, Kristin and I decided to find out how urban and forest anoles responded to extreme heat.

Sure enough, urban anoles could take the heat better than forest anoles, and we even found a few of the genes that affect heat tolerance.

These adaptations aren't unique to any one city.

We found the same differences between urban and forest anoles again and again, all over Puerto Rico.

We can think of cities as the big Petri dishes that are replicated on a much larger scale.

Shane, voice-over: No two cities are exactly alike.

But for anoles, all cities have some things in common.

To survive on the streets, crested anoles evolved longer legs, bigger toe pads, and better heat tolerance than their forest relatives.

And it happened fast.

Some of our urban study locations have only been cities for 30 years.

That's evolution in overdrive, even in lizard time.

So is this a feel-good story of animal adaptability?

Kristin: I think it's a big mistake for us to think that all animals are gonna be able to adapt their way out of this.

We still are going to lose a lot of species as urbanization progresses.

OK. Shane, voice-over: Only two of Puerto Rico's 10 anole species are found in cities, and just one, the crested anole, is really thriving.

So yes, some species can adapt, but the ones that don't get squeezed out.

Kristin: I mean, that's another reason why we should be studying the plants and animals that are doing well here, so that we can maybe engineer cities to be a little more favorable to wildlife.

Shane: So typically, when we think of ecosystems, right, we think of things like forests or deserts.

Should we consider cities as ecosystems as well?

Yes, absolutely.

And we should consider them as distinct ecosystems, just like we do all those others.

Shane, voice-over: Some folks aren't as comfortable as Kristin with calling cities ecosystems.

But the more I learn about urban biology, the harder I find it to think of them as anything else.

Still, San Juan is no Serengeti.

For one thing, I don't see any big predators in the streets.

But in major U.S. cities, that's beginning to change.

With the second-highest population density in the U.S., right after New York City, San Francisco doesn't seem like the ideal place for a large, wild predator.

But coyotes are full of surprises.

Just ask Officer Stephanie Pone.

One of the many things that I really love about this job is that every single day is a surprise.

Yeah.

It's different.

There's never a shortage of ways for animals to get themselves into conundrums.

OK. Nate Rose: Don't you ever come up out the cracks And try to tell me how to get it Shane, voice-over: Stephanie's sopapillas are the stuff of legend.

Rose: Spending any time just talking with me Shane: When she isn't practicing her culinary craft, Stephanie patrols the streets for San Francisco's Department of Animal Care and Control.

Rose: Tell me how to get it poppin' really Stephanie: The most succinct way to describe it is that we are responsible for public safety as it relates to animals.

One time, I had a coyote call at Fisherman's Wharf where the coyote was just chilling but being kind of a weirdo.

And I tried to approach to see if maybe there was something wrong, and the coyote got so scared that it jumped into the bay.

Oh, wow.

And then I had to do a boat rescue to rescue the coyote out of the bay.

And I was like, if I had just stayed out of it, the coyote would've been fine.

So it wasn't like, "You'll never get me, copper!"

And then he jumps into the-- I mean, maybe.

I wouldn't blame him.

[Laughter] Shane, voice-over: Stephanie's department gets quite a few calls about coyotes.

I get it.

There's something about seeing a predator walking down your sidewalk that would be very alarming.

Shane, voice-over: Coyote sightings are becoming increasingly common here, and not just in the city's green spaces.

We see a lot of coyotes here.

We get a lot of reports in this area, but also in the neighborhood, which is part of the issue.

Shane, voice-over: It's rare that a coyote actually harms a human or pet.

Still, public opinion of these predators is... let's just say mixed.

Just like our beautiful city, the response is very diverse.

We get people that on one end, love animals, but they treat them like dogs, and that is terrible for the coyotes and it's terrible for public safety.

And then we have the complete other end, where people think that they have no business being here and that they should all be killed.

Most people are somewhere in the middle.

Speaking as myself and not as a representative of the city, I'm quite fond of them.

I think it's magical.

I never get tired of seeing them.

I also am a dog owner, and I have a teeny-tiny little dog who would be the perfect size for a coyote snack.

Shane, voice-over: For many people, it's fear for their pets that tips the scales against coyotes.

It was 2015 when we started having coyote attacks.

Shane, voice-over: Karin Hu has lived in this neighborhood for 30 years.

I understand why people want coyotes in the city.

We love to look at wildlife, you know?

Maybe teaching people to appreciate the other types of, you know, things we have, like...

This last winter, I saw over 25 species of mushrooms.

I mean, that's fascinating!

Shane, voice-over: When Karin isn't teaching a course on psychoactive drugs at the local university, she's out walking her dog.

And where coyotes are concerned, Karin's vote is a "no."

At least, not in her neighborhood.

Is your main concern the safety of your dog, or do you have other concerns as well?

Oh, yeah.

Oh, it's-- It's all--OK.

If I didn't have little dogs, I wouldn't-- this wouldn't be my issue at all.

How do you go about deciding what belongs and what doesn't belong?

It's all values.

So my pets, the small dogs in this neighborhood, the cats in the neighborhood, are very high value.

And, yeah, there is value to having, you know, wildlife like coyotes around, but that's a lower value, as soon as you start being a risk to our family members.

Some people feel uncomfortable and they try to, like, make a rationalization.

I just say, "No, that's how we are."

It just is what it is.

Yeah, we're speciesists, you know?

We value some species more than others.

OK. Shane, voice-over: Historically, we've never valued coyotes much in the U.S. To this day, we kill almost half a million of them every year.

But it doesn't seem to faze them.

Today, coyotes inhabit more of the continent than ever, including thriving populations in major cities.

So researchers want to know, what's the secret sauce?

Why are coyotes so good at living in the habitat we've built for ourselves?

Woman: A big part of what I've done is walk around the city looking for coyote scat.

Scat, which is poop, just to be clear.

It is poop, yep.

OK. When I had you to myself Shane, voice-over: This is Tali Caspi.

If she isn't playing one of my all-time favorite tunes on her upright bass, you might find her scouring the sidewalks for scientific treasure.

You ever have somebody walk by and just look at you like you're an absolute maniac?

All the time, but actually, San Francisco is full of weird people.

So a lot of people just walk by and they're just like-- Makes sense.

Normal day, yeah.

Sometimes, you just gotta pick up some poop.

Totally, but when I do have those conversations with people, what's really cool about it is everyone has something to share or contribute.

Yeah.

It's pretty hard to be a resident of this city and not have had some kind of interaction or story with an urban coyote.

It's so foggy.

Ha ha!

At this point, I've walked around 950 kilometers of urban trails in the city over the span of two years-- Your Fitbit must be lighting up!

Tali: Oh yeah, it is.

Basically walking around, trying to find signs of coyote activity to help me find scat that I then pick up and bring into the lab.

And speaking of the devil... Shane: It's coyote poop!

Tali: Fresh coyote scat right here.

Shane, voice-over: In the last two years, Tali has collected more than 1,300 scat samples.

In the scat are clues about the urban lifestyle of coyotes.

Everything they eat leaves trace evidence behind in the form of DNA.

It's the DNA of the coyote, but then everything that the coyote ate as well.

Can you tell from the work that you've done, you know, like, how much cat DNA or, you know, Chihuahua DNA is in a coyote poop?

Yeah, so unfortunately, I can't tell how much Chihuahua DNA is in a coyote poop, because coyotes and dogs are actually pretty similar, but I've definitely found some cat reads in the scat, but it is by no means the majority or most significant component of their diet.

OK.

The parts of their diet that have come out thus far as sort of the biggest contributors are pocket gophers, pigeons are pretty common, and then these livestock breeds.

so cow, chicken and turkey, pig.

And these are obviously not animals that the coyotes are hunting in San Francisco.

God, I hope not.

Yeah, these are either foods that people are giving to the coyotes or are sort of foraged from garbage bins, from trash, or from cat food and dog food that people leave out.

OK. Shane, voice-over: So coyotes are doing some hunting in the city, but like the rats I met in New York, they're also making use of what we leave behind.

It may just be that city life is easy living if you're a coyote.

From somebody who has been studying these animals, what is your take on coyotes in the city?

They're here.

They've been here.

And they're going to stay here.

Let's say, tomorrow I could snap my fingers and take all of the coyotes out of the city.

They'd come back, because in all the surrounding areas, there are so many coyotes ready to just colonize an open territory.

The best thing we can do is think about coexistence with coyotes and how can we coexist with them as neighbors in our cities.

Shane, voice-over: That can be hard, because we build cities for ourselves.

These places are supposed to be for us, but coyotes shatter that illusion.

Maybe that's why so many people have strong feelings about them, both negative and positive.

[Howling] Man: I love them to death.

I think they're-- they--yeah.

They are such a fantastic species.

Yeah.

They give us so many lessons.

Mm.

Shane, voice-over: Meet my friend Chris Schell.

This man can grill up a mouth-watering rack of ribs.

He's also a professor at UC Berkeley, where he studies how coyotes and other animals live in cities.

How do you go about studying coyotes in this kind of environment?

We use techniques that we use in traditional ecological studies.

Everything from camera traps to fecal transects to GPS collars on the animals.

Shane, voice-over: This camera trap is one of dozens that Chris and his team have placed to observe wildlife in the city.

Chris: So we want to try and put the camera in places where we know wildlife are likely going to be, even though we know people are in the general area.

So let's go ahead and just go out and view out and see, OK, did we get anything that is for us noteworthy?

Now, we're super biased.

We're always thinking about the carnivores.

OK. Chris: And here I already see we got a gray fox.

Shane: Oh, yeah!

Chris: If we continue to scroll, more skunks, another person, more deer.

Man, it's a higher density of animals than I would expect.

Like, this is just over the course of a few days.

Right.

Wow.

Shane, voice-over: Here in the lush Berkeley Hills, carnivores like foxes and coyotes flourish.

But cities aren't monoliths.

Just down the hill in Emeryville, the habitat-- if you want to call it that-- doesn't look as inviting.

Chris: There's a lot of concrete here.

Mm-hmm.

As we're driving through, I'm seeing more built structures.

I'm seeing less vegetation.

I'm seeing less ways for animals to get from point A to point B. Shane, voice-over: But Chris' team set up a camera anyway...just to see.

Shane: Are you getting coyotes in as dense a number here as you would elsewhere in the city?

So no, we're not.

And the only species we've really caught on that camera have been ground squirrels or raccoons.

OK. OK. And that's it.

So a good chunk of the wildlife that we saw up at some of the other sites up in the hills, gray foxes, for instance, they aren't here.

Shane, voice-over: Animals know good habitat when they see it, and wealthy neighborhoods can be brimming with the things wild species need-- trees, water, safe places to hide.

Chris: So property values can positively correlate with the likelihood that you're going to see a coyote or other wildlife species in an area.

And that's called the luxury effect.

Oh, OK.

So urban species trying to live bougie, too, is what you're saying?

Oh, yeah!

Right, they're trying to make it work, like, "Oh, but this neighborhood over here, though?"

So many of the historical processes that have happened in cities... think residential segregation via redlining, or urban renewal programs that then led to displacement, gentrification also, leading to socioeconomic disparities in and across this urban landscape, right?

This entire landscape is constructed, and when we understand how its construction leads to amenities and disamenities therein, we start to understand that we aren't the only organisms that are being affected by this.

Mm.

That history, right, you're talking about things, the discrimination, racism, redlining.

Basically, what you're saying is, more than social, more than economic, they're tangibly biological.

Right.

Simply put, the past is present.

Shane, voice-over: The noise, the air pollution, the heat, the toxic byproducts of industry, the impacts of urban living hit harder in some places than others.

Chris: Even cities as close as San Francisco and the East Bay or Berkeley and Oakland are so separate from each other.

And the animals, they give us these lessons through how they move, through what they do, through what they eat.

Some organisms, like raccoons, for instance, if they eat too many human foods, develop diabetes.

They develop diabetes!

Oh, wow.

Right?

Just 'cause they're there doesn't mean that they're doing well.

Yeah.

So does the way that animals interact with their environment in a city teach us anything new about how we exist in a city as a species?

They serve as the beacons.

The "bioindicators" is the term we often use.

They are the conduits to allow us to better understand that many of these disparities that hit communities of color, low-income communities really hard are also the same things that are destroying the natural world.

The policies that separate us from us are also those same policies that separate us from the natural world.

Shane, voice-over: Many animals living in our cities don't know anything else.

So they learn to survive against all odds, even if they can't really thrive.

It kind of makes me wonder: What if we humans are the same way?

We are impoverishing ourselves, and that's just the hard truth, that we are hurting ourselves and we don't know it.

Shane, voice-over: This is Peter Kahn.

When he isn't serenading the wild on his homemade flute, he studies our species' shifting relationship with nature.

Peter's interest in cities dates back to the nineties, when he asked kids in Houston, Texas a couple of simple questions.

We just asked this kind of preliminary question, "Do you know what air pollution is?"

And they said, "Yeah, yeah," all of them.

Then we asked the second question, which was, "Does Houston have air pollution?"

And the significant number of children went from, "Yes.

Yeah, I understand what air pollution is," to "No, Houston doesn't have air pollution," which completely blew us away.

Because, at the time, Houston was the most polluted city in the United States.

How could these kids growing up in the most polluted city in the United States, how could they not know about that their city was polluted?

And that's the start, for me, some 30 years ago, in thinking about this issue, about environmental generational amnesia.

That the children are coming of age, and they're constructing a baseline of what normal is.

Shane, voice-over: That mouthful of a phrase, "environmental generational amnesia," refers to the way that each generation grows up thinking that their experience of the world is normal.

So in our urbanizing world, the less nature we experience, the less we think we need.

With each generation, nature becomes smaller.

Wilderness becomes a city park and then a row of trees in a median and then...nothing at all.

And thanks to this so-called amnesia, most of us never notice.

Peter: I think we're building urban prisons.

I think we're imprisoning ourselves.

Shane, voice-over: Peter's concerns are rooted in real data.

Depression and anxiety are more common in cities than outside them.

And some studies show that exposure to nature can help, not just with mental health, but physical health, too.

It reduces stress, reduces obesity, helps eyesight, reduces depression.

I mean, the list is on and on.

Can modern cities be transformed into something that allows us to sort of reconnect in that ancestral way with our environment while still having all of the functional components of a city?

Yeah.

There's some marvelous parts of cities, and I think we both appreciate them so much.

And it's the coming together of different groups and different energies, different knowledge.

The creativity is so amazing in cities.

We can make them better and we should make them better.

Yeah.

Um... but here's the thing.

They can get a lot worse, and unless we push back, try to make them better, they will get worse.

Shane, voice-over: We haven't reached "peak city" yet, not even close.

By 2050, 2/3 of us will live in urban areas.

So as cities continue to grow, how can we create a less dystopian urban future?

Halfway around the world, architects and urban planners are pushing back and reimagining what city living can be, for us and the rest of nature.

In every city I've ever lived in, green spaces felt like an escape.

They were in the city but not of the city.

Singapore is different.

Here, nature is never more than a few blocks away.

Everywhere you look, buildings are exploding with life.

[Rooster crows] It feels like a miracle.

Woman: Is it your first time in Singapore?

Shane: It is.

Man, this place, it's-- I've never seen anything like it.

It's incredible.

Shane, voice-over: If you ask Pearl Chee, she'll tell you it's no miracle.

It's all part of the plan.

Pearl: We are challenging ourselves as architects whether we can design better.

We are creating a lot of concrete buildings, it's like a concrete jungle, but we really want to bring the jungle in.

Shane, voice-over: Pearl is the architect who designed the Kampung Admiralty, the building we're standing in now.

Pearl: Our design concept, it's a very unique combination.

We actually have elderly housing, public housing, combined with healthcare, which is a medical center, commercial and some social programs, and a food court, yeah.

Shane: Oh, wow.

So that's why it's not gated.

It's very open.

Anybody can actually come in and use the facilities here.

Shane, voice-over: Singapore is the third most densely populated city in the world.

The entire country is an island with only 281 square miles of land, but 5.5 million people live here.

In a city this dense, you wouldn't expect much room for nature.

But it's like they say: where there's a will, there's a way.

And by will, I mean law.

Legislation enables it to happen.

The building took the land.

So we need to do replacement.

The legislation actually requires a building to give back 100% landscape.

Oh!

100% of the site footprint has to be replaced into the building.

Every square inch of, like, green space that you take up, you have to put back in...

Put back in, yeah.

into the building somehow.

Into the building.

Shane, voice-over: A few years after completing the building, Pearl's firm surveyed the animal life in Kampung Admiralty's gardens.

50 different species had moved in.

Pearl: The species in this building is higher than the species on the ground park.

Oh, really?

Yeah, which is right nearby.

So...

Wait, so there's more species within this construction than in, like, a natural space of the same amount of greenery?

Yeah, correct.

That's incredible.

Thinking about an entire city built like this, basically, you're talking about reforestation and urbanization as sort of one and the same.

Correct.

[Crows] Shane, voice-over: This development is a microcosm of what's happening all over Singapore.

It's not just one building or designer or architecture firm.

The whole city is teeming with life.

Narrator: It's hard to believe that not so long ago, war surged around it and even in it.

Singapore, cosmopolis of the East.

Malays, Chinese, Indians, and British have taken time by the forelock, and the shops and market stalls dazzle the eye and make our mouths water.

As you sort of, like, move around the city now, you know, do you, you know, like, do you go to places and you're like, "Oh, this is my baby"?

Yeah, yeah.

All the time.

[Laughter] Shane, voice-over: Professor Cheong Koon Hean is a music lover and life-long Singaporean.

She's also a legendary urban planner.

A lot of folks credit her with shaping Singapore's singular urban landscape.

BAER: Raise a toast to the GOAT, yeah Cheong: This is one of my favorite neighborhood centers in a public housing estate.

Because in Singapore, 80% of the people live in public housing in estates like this.

Oh, wow.

In highly affordable housing.

Shane, voice-over: Kampung Admiralty, the building Pearl Chee designed, is public housing, too.

And these places are cush.

The apartments are modern and clean, the amenities are incredible, and most developments are a 10-minute or less walk from public transportation.

And, of course, everything is draped in greenery, from the street level to the tops of the skyscrapers.

Where I come from, when we say "public housing," basically, like, we call it "the projects."

And I was actually raised a lot in public housing.

And that public housing and this public housing are not the same thing.

Well, you can't believe it when you come to Singapore today, but, say, about 60, 70 years ago, actually, Singapore was a nation of slums and squatters.

It was also polluted and lots of traffic congestion.

Shane, voice-over: When Singapore gained its sovereignty from Britain in 1959, it was a city of 1.5 million people and massive, unplanned sprawl.

Tens of thousands of people had no place to live.

So the newly elected government created the HDB, or Housing and Development Board.

Cheong: And within 5 years, the HDB, they already built 51,000 units of flats.

It started from very basic housing, but now, of course, the quality is a lot better, as you can see around you.

Yeah.

Shane, voice-over: And public housing is just the beginning.

Singapore is a very small city-state.

It's actually only half the size of metropolitan London.

Oh, wow.

But we are a country.

We're not just a city.

So everything you need about a country, whether it's for water, power generation, ports, airports, plus housing, shops, offices, industry, all has to be built within this tiny island city-state.

And so biodiversity and ecological balance became really quite an important concept.

Now, as we developed the land, of course we start to lose space for planting.

So what did we do?

We decided to move the greenery upwards into the sky.

And so, what you did is you just created new space.

And suddenly, you bring back all the biodiversity.

Back in the States, urban areas and wildlife are sort of like oil and water.

They don't mix very well.

But what you've done here is something very, very different.

Over the years, we moved from being a garden city to a city in the garden because we started to plant so extensively.

And in the last decade or so, we moved from a city in a garden to city in nature.

In a place where you have limited space and you have this growing population that there are two very sort of competing needs.

Shane, absolutely, there's always competing needs, right?

So it's really this very important balancing act of allocating the right amount of land for different uses to create this type of an environment.

Shane, voice-over: And who orchestrates this balancing act?

It's the Singaporean government, with their comprehensive "Master Plan" for managing the city-state's ongoing growth.

By centralizing the control of urban development, Singapore paves the way-- you see what I did there-- for projects that fuse function and form.

Cheong: If you look behind us, the Punggol Waterway is actually a man-made river.

We dammed up two rivers to become freshwater reservoirs.

Now, the engineers wanted to connect the two reservoirs with a pipe-- very functional.

But then the architects and the planners say, "Why do a pipe?

Why don't we make a river?"

And so, this river connected the two reservoirs to balance and optimize the storage of water, but at the same time, it became a leisure facility.

So Punggol has a nickname.

It's the Venice of Singapore.

Oh, that's amazing.

Because we brought in water, right?

It has its aesthetics, but everything also serves... Function, yes, a function.

a very specific function.

Even the Punggol Waterway, there's a family of otters that have come back.

Oh, that's incredible.

They live on the Punggol Waterway.

Shane, voice-over: Singapore challenges a lot of what I thought I knew about cities.

No one's saying that we should all be like Singapore, or even that we could be.

This place is unique.

90% of Singapore's land is publicly owned.

The government determines what gets built and where.

And with everyone sharing the same tiny island, by definition, they're all in this together.

Most places don't have all that.

But I'm not sure we need it to re-imagine what cities can be.

I think the thing that stands out to me about Singapore is the intentionality.

I'm not sure if this specific model can be applied anywhere or everywhere, but I think they're doing things that I think other cities can learn from.

We have to get our act together to make cities effective.

Creativity, innovation, and that will to survive and to want to do well are very, very strong drivers.

That's human beings, right?

That's what we are.

Shane, voice-over: Cities might just be humankind's most remarkable invention.

Because we thought we were building ourselves a place to live, but we were really creating a new ecosystem, a place where nature has to adapt to live alongside us and some of our urban neighbors are more welcome than others.

City living brings challenges-- for us and all the species that share our urban spaces.

But we shouldn't forget that cities can also help us flourish.

In Oakland, Chris said something that stuck with me.

We are a communal species.

So for folks to think, "Well, if you just get outside the city, you'll be OK," nah, nah, nah, it doesn't work like that.

We need to be able to have connection.

Shane, voice-over: That's why cities aren't going anywhere and why we need to make them better.

With a little creativity and vision, they can deliver that connection-- to each other and maybe to the rest of our incredible planet, too.

Human Footprint is available with PBS Passport and on Amazon Prime Video.

