format:
  revealjs:
    scrollable: true
    title-slide-attributes:
      data-visibility: hidden
    css: [slides/style/timeline.css, slides/style/hex.css, slides/style/custom.css]
    progress: true
    incremental: true
    auto-animate: true
    menu: true
    preview-links: true
    show-slide-number: all
    default-image-extension: png
    width: 1920
    height: 1080
callout-appearance: simple
author: "Dr. Alicia M. Rich"



