project:
  type: website
  output-dir: "docs"
  execute-dir: project

website:
  title: "Course Information"
  favicon: images/logo_richlab.png
  description: "Courses at UNO taught by Dr. Alicia Rich"
  navbar:
    class: "navbar navbar-expand-lg bg-dark"
    data-bs-theme: "dark"
    logo-alt: "Rich Lab Website"
    left:
      - text: "Conservation Biology"
        menu:
          - text: "Course Homepage"
            href: "conbio/index.qmd"
          - text: "Current Schedule"
            href: "conbio/schedule.qmd"
          - text: "Syllabus"
            href: "conbio/syllabus.qmd"
          - text: "Slide Decks"
            href: "conbio/slides_listing.qmd"
      - text: "Human Health & the Environment"
        menu:
          - text: "Course Homepage"
            href: "hhe/index.qmd"
          - text: "Current Schedule"
            href: "hhe/schedule.qmd"
          - text: "Syllabus"
            href: "hhe/syllabus.qmd"
          - text: "Slide Decks"
            href: "hhe/slides_listing.qmd"

author: "Dr. Alicia M. Rich"
date-modified: today
date-format: "ddd MMM D, YYYY"
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: "Contents"
    theme:
      - yeti
    page-layout: article
    css:
      - styles/yeti.css
      - styles/fonts.css
      - styles/headings.css
    smooth-scroll: true
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Anaheim:wght@400..800&family=Cabin+Condensed:wght@400;500;600;700&family=Yaldevi:wght@200..700&display=swap" rel="stylesheet">

editor: source

