project:
  type: website
  output-dir: "docs"
  execute-dir: project
website:
  title: "Courses with Dr. Rich at UNO"
  favicon: images/logo_richlab.png
  description: |
    Courses at UNO taught by Dr. Alicia Rich
  navbar:
    class: "navbar navbar-expand-lg bg-dark"
    data-bs-theme: "dark"
    logo-alt: "Rich Lab Website"
    left:
      - text: Overview
        href: "index.qmd"
      - text: Conservation Biology
        menu:
          - text: Course Homepage
            href: "index_conbio.qmd"
          - text: Current Schedule
            href: "schedule_conbio.qmd"
          - text: Syllabus
            href: "syllabus_conbio.qmd"
      - text: Human Health & the Environment
        menu:
          - text: Course Homepage
            href: "index_hhe.qmd"
          - text: Current Schedule
            href: "schedule_hhe.qmd"
          - text: Syllabus
            href: "syllabus_hhe.qmd"
format:
  html:
    theme:
      - yeti
    page-layout: article
    css:
      - styles/yeti.css
      - styles/fonts.css
      - styles/headings.css
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Anaheim:wght@400..800&family=Cabin+Condensed:wght@400;500;600;700&family=Yaldevi:wght@200..700&display=swap" rel="stylesheet">
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: "Contents"
    smooth-scroll: true
editor: source

