project:
  type: website
  output-dir: "docs"
  execute-dir: project
website:
  title: "Courses with Dr. Rich at UNO"
  favicon: images/logo_richlab.png
  description: |
    Courses at UNO taught by Dr. Alicia Rich
  navbar:
    class: "navbar navbar-expand-lg bg-dark"
    data-bs-theme: "dark"
    logo: images/logo_richlab.png
    logo-href: https://rich-molecular-health-lab.github.io
    logo-alt: "Rich Lab Website"
    left:
      - href: index.qmd
        text: All Courses
      - text: Syllabi
        menu:
          - text: Conservation Biology
            href: 25f/conbio/syllabus_conbio25f.qmd
          - text: Health & the Environment
            href: 25f/hhe/syllabus_hhe25f.qmd
format:
  html:
    theme:
      - lux
    css: styles/lux.css
    toc: true
    code-links: repo
    embed-resources: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
editor: source

