execute:
  freeze: auto
  include: false
date: "August 24, 2026"
date-modified: today
date-format: "ddd MMM D, YYYY"
title: "Syllabus"
author: "Dr. Rich"
image: "graphics/commics/header-ItsInTheSyllabus2.png"
format:
  html:
    toc: false
    theme: sandstone
    page-layout: full
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <script src="https://kit.fontawesome.com/eba65c29db.js" crossorigin="anonymous"></script>
