date-modified: today
date-format: "ddd MMM D, YYYY"
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: "Contents"
    theme: sandstone
    page-layout: full
    smooth-scroll: true
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <script src="https://kit.fontawesome.com/eba65c29db.js" crossorigin="anonymous"></script>

