---
title: "Extreme Heat Is the New Normal"
profile:
  - "video"
  - "hhe"
categories:
  - "video"
  - "ENVN4320"
---

# Extreme Heat Is the New Normal  Op-Docs

**New York Times Opinion**, *08 28, 2026*

## Video (15:42)

<iframe width="560" height="315" src=https://www.youtube.com/embed/QcHuAtK_H_8 title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Description

We filmed “A New Inferno,” the short documentary above, in Phoenix, one of the hottest cities in America, through some of the city’s hottest days of 2025, during one of the hottest years on record globally. On one of our production days, temperatures reached 118 while we were filming outside.

In the face of extreme heat, we documented firefighters and paramedics of the Phoenix Fire Department saving lives in real time. We wanted to call attention to a specialized technique of ice bag immersion for people facing life-threatening heat stroke. We hope that telling their story and showcasing the efficacy of this strategy will encourage wider adoption of this protocol across the country.

Yet this procedure is ultimately a stopgap, as firefighters do their best to adapt to the climate crisis in front of them. The underlying story of heat in Phoenix is one of broader, interlocking crises: homelessness and substance use disorders that are deeply entangled with urban heat, each amplifying the other, illustrating how climate change affects the disenfranchised most brutally.

With our film, we aim to reframe how the public thinks about heat: as an invisible, silent killer reshaping the rhythms of urban life.

Documentary and text by By Nita Blum-Reddick and Jonathan Pickett

More from Op-Docs: https://www.nytimes.com/column/op-docs

Subscribe: http://bit.ly/U8Ys7n

0:00 Phoenix is only getting hotter

2:06 ‘The feedback loop of nightmares’

3:53 Ice bag immersion training simulation

7:40 How firefighters respond to heat-related emergencies

12:55 ‘He was really close. He was at that threshold.’

14:40 Facing a warming world

## Transcript

### Phoenix is only getting hotter

**0:00** · [SIREN]

**0:20** · Special call rescue 903.

**0:23** · So it looks like the male patient —— he’s on the side of the road, probably heat-related.

**0:28** · He’s not responsive at all.

**0:30** · How long has he been down?

**0:32** · Unknown downtime.

**0:34** · OK, cool.

**0:35** · We’ll be there in a minute, bro.

**0:36** · Easy.

**0:38** · [HONKING] [TENSE MUSIC] “Phoenix is known for heat, but it’s never been this hot before.”

**0:52** · “That’s a record.”

**0:53** · “Broken a record.”

**0:54** · “An all-time record.”

**0:56** · “And we’re already experiencing that human toll.”

**0:59** · “Arizona has reported over 800 heat-related deaths.”

**1:02** · “Governor Hobbs declaring a state of emergency.”

**1:05** · [SCREECHING TIRES] “They’re turning to tools that could be the difference between life or death.”

**1:19** · “Starting this year, each Phoenix fire truck will be immersing heatstroke victims in ice.”

**1:26** · Put it right over their chest and their groin.

**1:29** · Get it right on top of them.

**1:31** · It’s the evolution of our job.

**1:34** · Heat-related emergencies are definitely on the rise, and we’re on the front lines.

**1:39** · This is what we have to do.

**1:42** · So they’re kind in this little cocoon filled with ice and water.

**1:47** · “Potentially saving them before reaching a hospital.”

**1:50** · [HONKING] Another day in paradise, baby.

**2:04** · Go check him out.

**2:04** · Go check his temp.

### ‘The feedback loop of nightmares’

**2:08** · He’s overheated.

**2:09** · Sir, we’re going to take you to the hospital, OK?

**2:15** · OK, keep that arm still, OK?

**2:16** · What’s your name?

**2:19** · Do you know where you are?

**2:22** · He’s ODing.

**2:26** · K-1 fire dispatch.

**2:29** · 11,309.

**2:32** · This is where we’re at in the city of Phoenix.

**2:37** · You hang around our station long enough, you see people living a feedback loop of nightmares —— the heat, the drugs, and homelessness.

**2:54** · I know that I won’t be able to help everyone.

**2:58** · But I just want to be that relief for as long as possible.

**3:12** · Did you do any alcohol or drugs today?

**3:15** · Use any alcohol or drugs?

**3:16** · Yeah?

**3:16** · What did you use?

**3:17** · Did you use fentanyl?

**3:18** · [SIREN] Yeah, mate.

**3:29** · The heat makes people do some strange things.

**3:32** · [SINGING] When you’re strange, faces come out.

**3:38** · When you’re strange.

**3:40** · When you’re strange.

**3:46** · OK, he still has a pulse.

**3:47** · It’s just high.

**3:49** · Hypothermia alert.

**3:50** · Arriving.

### Ice bag immersion training simulation

**3:56** · It’s going to be a 40s male, altered level of consciousness.

**3:59** · We found this patient down at a bus stop.

**4:02** · His temperature was too high for our thermometer to read.

**4:04** · It just said high.

**4:05** · Can you just hand whatever she needs?

**4:07** · Let’s add some ice.

**4:08** · Let’s add some water.

**4:09** · Let’s get them on the monitor.

**4:10** · Let’s see what we’re dealing with.

**4:11** · So we can help with this.

**4:12** · Alert, five minutes out.

**4:14** · And it sounds like we got another one coming.

**4:16** · [BEEPING] We got more ice.

**4:19** · We’re going to try to get them down to under 41.

**4:21** · And under 41, we’ll get them out of the cold water immersion.

**4:25** · She had a GCS of 5 and a temperature of 107.6 on arrival.

**4:30** · Shannon, can you bring some Levophed?

**4:31** · I think his pressure’s going to tank on us.

**4:35** · Hopefully, our temp will be coming down soon.

**4:37** · Your temp is 42.6.

**4:40** · 42.6?

**4:40** · Great.

**4:40** · So we’re starting to make some progress here, guys.

**4:43** · I’ve got 42.2.

**4:45** · I love that.

**4:45** · [TRAFFIC WHIRRING] “The heat is taking a devastating toll again this summer with 44 deaths confirmed so far.

**5:08** · And with homeless shelters across the valley full, demand for those cooling center seats has been enormous.”

**5:27** · There’s a large population of unhoused people that is out in the heat constantly, right?

**5:31** · And so it compounds, OK?

**5:34** · So one of you —— I want you to come up and establish if they’re conscious.

**5:38** · Eric, I want you to take the back of your hand and touch the sidewalk.

**5:42** · OK?

**5:43** · Pull your glove back.

**5:44** · If that’s hot, that patient is really hot.

**5:47** · This is also, potentially, a patient who now has burn injuries.

**5:50** · Right?

**5:51** · They’ve been laying on the pavement.

**5:53** · That might be 170 degrees with potential first- and second- degree burns.

**5:59** · That’s it.

**6:00** · Anybody got any questions?

**6:09** · I mean, it’s so simple, right.

**6:12** · Like, OK?

**6:13** · This is kind of barbaric in a sense because it’s just a blue bag with ice.

**6:21** · But the heat is definitely not going away.

**6:25** · And this is all we have right now.

**6:35** · Engine 18.

**6:41** · K deck 9.

**6:48** · This is going to be a busy day, though.

**6:49** · It’s not really hot yet.

**6:51** · It’s probably 100 degrees, but it’s super humid.

**6:53** · It’s not a good start to the day.

**6:56** · Why do you sweat so much, man?

**6:57** · Are you watching “Cops”?

**6:58** · Man, that dumpster fire almost kicked my ass.

**7:02** · Have a good day.

**7:04** · Thank you, my friend.

**7:10** · Yeah, she’s moving too fast.

**7:14** · Exactly.

**7:14** · Tell her to slow down.

**7:15** · ’Cause I haven’t introduced my daughter to nobody.

**7:17** · Ooh, that’s crucial.

**7:19** · But, yeah.

**7:20** · So I think I’m going to pull back a little bit.

**7:24** · And fallback game is like Nick Van Exel three.

**7:26** · Dog.

**7:27** · Wet.

**7:28** · Kobe.

**7:30** · The universe will always work it out, bro.

**7:33** · [BEEPING] Fire Department.

**7:36** · What’s the address?

### How firefighters respond to heat-related emergencies

**7:40** · OK. And is she awake right now?

**7:45** · OK. OK, thank you.

**7:53** · We’ll see you soon.

**7:55** · This is where the secret is.

**7:56** · That’s that cool.

**7:58** · Engine 18.

**7:59** · Ill person.

**8:01** · Showtime.

**8:02** · [ENGINE STARTING] This is really hot out.

**8:11** · Those jalapeños didn’t help.

**8:13** · [SIREN] I do have some help on the way for you.

**8:24** · They are three minutes away, so they’ll be there in just a few minutes, OK?

**8:28** · Do what you can to stay in the shade.

**8:30** · [SIREN] “This is your homework, Larry.”

**8:45** · “Get your car out front.”

**8:46** · “This is this your homework, Larry.”

**8:48** · “I know what this ——” [RADIO CHATTER] How are you doing?

**8:59** · I’m going to check your temperature, OK?

**9:02** · Are you having a hard time breathing, dear?

**9:05** · OK. Patient is presenting lethargic, also complaining of nausea/vomiting, 20-gauge IV was administered to right hand.

**9:19** · [BEEPING] Can you ask him if they’re having a medical emergency?

**9:28** · Again, they’re completely unresponsive right now.

**9:31** · Engine 18, K dock 9 for an ill person, heat-related.

**9:35** · 23rd Avenue and Camelback.

**9:36** · Engine 18, K dock 9.

**9:38** · [SIREN] K-1 fire dispatch.

**9:43** · They’re on the sidewalk, so they’re baking for sure.

**9:47** · It’s got to be on my side.

**9:49** · Copy.

**9:49** · [SIREN] Wrong side, buddy.

**10:01** · I hope everybody good, man.

**10:04** · Turn right here.

**10:05** · [SIREN] Engine 341.

**10:18** · and Battalion 321.

**10:19** · K dock 9.

**10:25** · You want to put a carry-on underneath?

**10:28** · Ladder 273.

**10:29** · K dock 7.

**10:44** · Put him over like this.

**10:45** · And we’re going to slide this out.

**10:47** · OK?

**10:48** · [COUGHING] Zip that up.

**10:56** · Zip that up, so we don’t lose any —— capture that.

**10:58** · Uh-huh.

**11:00** · No.

**11:04** · [RADIO CHATTER] 18-gauge.

**11:17** · Right AC good.

**11:18** · I called an ambulance for four additional bags of ice.

**11:21** · [RADIO CHATTER] And his tympanic temp was 107.

**11:29** · Rescue is rolling up.

**11:30** · Have another full bag, guys.

**11:34** · We got two.

**11:34** · Now we just need the bag.

**11:35** · K dock 8.

**11:39** · [THUNK] One, two, three.

**12:01** · [SIREN]

**12:35** · OK, give us a call if you get anything else about it.

**12:37** · OK, all right.

**12:38** · All right.

**12:38** · Have a good day.

**12:43** · How’s he looking?

**12:45** · So he was real close.

**12:50** · Like, he was at that threshold to where it’s a few more minutes.

### ‘He was really close. He was at that threshold.’

**12:58** · Like, if somebody didn’t find him at that particular moment.

**13:01** · So I don’t know if they induced coma, but he was in bad shape.

**13:05** · To be intubated is —— a lot of times, that was associated with, like, they’re probably not coming out of the hospital, right?

**13:11** · [MUSIC PLAYING] Engine 18, arrived on scene, finding patient lying next to bus stop, overheating and not breathing.

**13:30** · Patient was placed in cold immersion bag with ice on top and surrounding his body.

**13:39** · Part of you knows, like, damn, we did all this stuff.

**13:44** · But even our best effort —— he might not have had a good outcome.

**13:54** · Fortunately, it’s part of life, you know.

**13:59** · But we try to do the best.

**14:00** · So I felt like we did the best we could for him.

**14:13** · It’s a nice night, bro.

**14:15** · Yeah, it is, dog.

**14:17** · But if it’s so hot out here that we got to throw people in bags, what are we doing here?

**14:24** · Maybe that’s a sign.

**14:25** · It’s the devil’s playground, bro.

**14:27** · [Expletive] It ain’t fun here anymore.

**14:30** · You know what I mean?

**14:35** · [SIREN CHIRPS] Ooh, the boys.

**14:38** · Go get some.