---
title: "Greenlining Fund Invests in Omaha’s Historically Redlined Neighborhoods"
profile:
  - "video"
  - "hhe"
categories:
  - "video"
  - "ENVN4320"
---

**The Omaha News**, *03 12, 2025*

## Video (1:32)

<iframe width="560" height="315" src=https://www.youtube.com/embed/hkibb2WLq3Q title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Description

The Omaha News streams live every Wednesday at 4 p.m. on YouTube, Facebook and The Knowledge Network (TKN) during the academic year. The half-hour newscast also airs state-wide on NET reaching all of Nebraska’s 1.9 million residents. 

Our mission is to fully immerse University of Nebraska at Omaha journalists into the business of reporting and investigating live, local stories that impact our region. Located in the Community of Public Affairs and Community Service building, our newsroom is home to state-of-the-art facilities and award-winning journalism. 

#TheOmahaNews #LocalNews #StayTuned #ThePeopleAreTheStory #Greenlining

Subscribe- https://www.youtube.com/channel/UCrtGgsQoOlVKYm2LMk8SpgQ

Website- unomahanews.com

Facebook- https://www.facebook.com/UNOTheOmahaNews

Instagram- https://www.instagram.com/unomahanews/

## Transcript

**0:02** · front porch Investments green lining fund is helping homeowners in historically Redline areas invest in their properties and enhance the community redlining is the practice of denying loans and services to minority neighborhoods which led to long-term disinvestment and though outlawed in 1968 its effects still linger Yolanda

**0:19** · Williams housing Justice and grants manager at front porch Investments says this impact is still evident today how can this impact North Omaha residents particularly the black North Omaha residents that's struggle to find affordable housing that are struggling with home ownership and just the valuations of these homes are much lower than counterparts in you know Midtown or West Omaha in 2023 the green lining fund launched a program providing 0% interest loans of up to $5,000 per property to

**0:48** · help homeowners with critical repairs These funds support Home Improvements and Renovations aiming to stabilize households and address critical housing needs etel Lopez CEO of the Latino Economic Development Council says many homeowners are forced to choose between basic maintenance and other essential costs and it's expensive I mean you talk about you know replacing a window all of this windows in my home office have not been replaced and it's really cold here do I want to replace the windows which is you know going to cost me so much or

**1:17** · do I want to pay a higher monthly bill the green Ling fund isn't just about fixing homes it's about restoring investment empowering residents and ensuring North and South Omaha communities can Thrive for generations for the Omaha news I'm marry mitoff