---
title: "Heatwave What is the urban heat island effect"
profile:
  - "video"
  - "hhe"
categories:
  - "video"
  - "ENVN4320"
---

**Sky News**, *07 15, 2022*

## Video (2:40)

<iframe width="560" height="315" src=https://www.youtube.com/embed/YX3C3eq2MJY title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Description

Extreme heat is going to be felt across the country, but it's our cities that will be worst hit, as a phenomenon called the urban heat island effect drives temperatures even higher. 

There are solutions but it takes time and investment. Sky's Science Correspondent Thomas Moore reports.

#heatwave #skynews #extremeweather 

SUBSCRIBE to our YouTube channel for more videos: http://www.youtube.com/skynews 

Follow us on Twitter: https://twitter.com/skynews 

Like us on Facebook: https://www.facebook.com/skynews 

Follow us on Instagram: https://www.instagram.com/skynews 

Follow us on TikTok: https://www.tiktok.com/@skynews

For more content go to http://news.sky.com and download our apps: 

Apple: https://itunes.apple.com/gb/app/sky-news/id316391924?mt=8 

Android https://play.google.com/store/apps/details?id=com.bskyb.skynews.android&hl=en_GB 


Sky News videos are now available in Spanish here/Los video de Sky News están disponibles en español aquí https://www.youtube.com/channel/skynewsespanol

Sky News videos are also available in German here/Hier können Sie außerdem Sky News-Videos auf Deutsch finden: https://www.youtube.com/channel/UCHYg31l2xrF-Bj859nsOfnA


To enquire about licensing Sky News content, you can find more information here:  https://news.sky.com/info/library-sales

## Transcript

**0:00** · our towns and cities just weren't built to be this hot baked by the sun with little shade urban living can be stifling at mossborne parkside academy in east london the children are well drilled the school is victorian and keeping the classrooms cool is a challenge

**0:18** · all our windows are open and as much as possible before and after school and during the day we have blackout blinds so we actually have them closed when the children aren't learning and just to try and keep those classrooms as cool as possible temperatures could top 40 degrees in parts of england early next week but in the cauldron of the concrete jungle the heat is intensified still further studies have shown the centers of london and manchester can be 10 degrees warmer than surrounding rural areas it's an effect called the urban

**0:47** · heat island and with a thermal imaging camera you can see it in action the brick the concrete the asphalt is all glowing red hot as it absorbs the sun's radiation and stores it as heat but look at the contrast of a tree it's not just the shade beneath which is a cooler blue but the leaves themselves are kind of in between on that color spectrum as they're absorbing some of the sun's energy but evaporating water

**1:13** · keeping them cool and the surrounding air data given to sky news shows how that makes a difference even in a relatively small town sensors dotted around guildford in surrey show the heat rising on monday morning by early afternoon the temperature in the built-up area was seven degrees higher than a nearby park

**1:33** · and it took longer to cool still three degrees warmer at midnight you will not feel comfortable you know the thermal comfort is an issue but if you are an elderly or having any pre-existing you know the the conditions so you are higher at risk for the heat stroke or cardiovascular or the respiratory you know the impact and that can be fatal that

**1:55** · can be fatal 90 of the uk population is expected to live in an urban area by 2050. the charity trees for cities is planting shade for the future but warns it can't do it fast enough there's never been more focus and funding for trees in general which is fantastic we should recognize that but a lot of that funding historically has been focused on on the the royal

**2:17** · environment on the countryside and we believe that we need to shift that balance in order to invest much more into our cities the government says it wants to plant 150 000 trees in urban areas but the money for this year has already run out the sooner they go in the ground the greater the shade and the even more intense heat waves of the future thomas more sky news