---
title: "How Urban Heat Impacts Communities of Color"
profile:
  - "video"
  - "hhe"
categories:
  - "video"
  - "ENVN4320"
---

**Did You See This?**, *07 21, 2021*

## Video (7:14)

<iframe width="560" height="315" src=https://www.youtube.com/embed/E6WI_RWNrCU title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Description

The urban heat island effect is a phenomenon affecting more than 100 cities across the U.S. — here’s how it works and why it disproportionately impacts communities of color.
» Subscribe to NowThis Earth: https://go.nowth.is/Earth_Subscribe
» Sign up for our newsletter KnowThis to get the biggest stories of the day delivered straight to your inbox: https://go.nowth.is/KnowThis

This video was created in partnership with Emerson Collective https://www.emersoncollective.com.

#ClimateChange #UrbanHeatIsland #Phoenix #Earth #Environment #Science #NowThis

Connect with NowThis
» Subscribe to NowThis News: http://go.nowth.is/News_Subscribe
» Like us on Facebook: http://go.nowth.is/News_Facebook
» Tweet us on Twitter: http://go.nowth.is/News_Twitter
» Follow us on Instagram: http://go.nowth.is/News_Instagram
» Find us on Snapchat Discover: http://go.nowth.is/News_Snapchat

NowThis Earth is daily news coverage of climate, sustainability, biodiversity, species extinction, environmental justice, and other planetary concerns.

NowThis is your premier news outlet providing you with all the videos you need to stay up to date on all the latest in trending news. From entertainment to politics, to viral videos and breaking news stories, we’re delivering all you need to know straight to your social feeds. We live where you live.

http://www.youtube.com/nowthisearth
@NowThisEarth

## Transcript

