---
title: "The Most Dangerous Wildfires All Have ONE THING in Common"
profile:
  - "video"
  - "hhe"
categories:
  - "video"
  - "ENVN4320"
---

**PBS Terra**, *10 30, 2024*

## Video (12:08)

<iframe width="560" height="315" src=https://www.youtube.com/embed/_uVdeK2nrrg title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Description

Check out our Patreon: https://www.patreon.com/cw/PBSWeathered?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink 

Fires are getting bigger and more homes are burning each year. In January 2025, 14 out of control wildfires tore through parts of Los Angeles and burnt over 18,000 structures and left at least 29 people dead. Firefighters are having to change tactics when it comes to the most destructive fires, but why? Jennifer Blach, Ph.D., just released a new study in the journal, Science, and her findings point to a new type of fire that is the culprit for all this destruction. 

In this episode, we dive into this groundbreaking new study to learn why fires are getting more dangerous to humans and what we can do about it. Plus we have never-before-seen animations from NASA that show us exactly how these new fires behave. So tune in to learn about the future of fires and how to protect yourself and your home as fires change. 

Get the PBS App to watch Weathered: Earth’s Extremes for free!  https://to.pbs.org/PBSAppWeathered
If you're outside of the US and want to watch the show, you can check it out on PBS.org: https://to.pbs.org/WeatheredINTL

Find free, curriculum-aligned teaching resources for Weathered on PBS LearningMedia! https://bit.ly/3YbUtef 

Jennifer Balch’s new study in Science: https://www.science.org/doi/10.1126/science.adk5737 

PBS Member Stations rely on viewers like you. To support your local station, go to: http://to.pbs.org/DonateTerra. 

Weathered is a show hosted by weather expert Maiya May and produced by Balance Media that helps explain the most common natural disasters, what causes them, how they’re changing, and what we can do to prepare.

*****
PBS Member Stations rely on viewers like you. To support your local station, go to: http://to.pbs.org/DonateTerra
*****

Subscribe to PBS Terra so you never miss an episode! https://bit.ly/3mOfd77 

And keep up with PBS Terra on: 
Facebook:  https://facebook.com/pbsdigitalstudios
Tiktok: https://www.tiktok.com/@pbsterra
Instagram:  https://instagram.com/pbsterra

Thank you Margaret A. Carghill Philanthropies for supporting PBS.

#californiawildfires #palisadesfire

## Transcript

### The new wildfire reality


**0:00** · 80% of wildfire destruction is caused by one type of fire that until recently was rare. Scientists just figured out what these destructive fires have in common, and it's not what you might guess to understand what's going on. We talked to Battalion Chief, Mike McClintock, who fought this type of fire during the summer of 2024.

**0:21** · And our conventional methods with fire engines and personnel were really ineffective. We had to get ahead of the fire and worry about life safety To understand why wildfire destruction has increased. We focus on the most obvious change in fires: they're getting bigger, but researcher Jennifer Balch says that might be a distraction. According to her new study, We've been focused on the wrong metric.

**0:43** · The number of homes burned each year is going up. The Rim fire in California was massive at over 257,000 acres, but it only destroyed 11 homes and no one died. When you compare that to the Lahaina fire in Maui, which was a hundred times smaller, burned 2200 homes and buildings and was the deadliest fire in modern U.S. history, it's obvious that we're missing something.

### Revisiting fire research

**1:09** · In this episode, we're going to look at new research that could fundamentally change how we think about wildfire risk, what to expect in the future and what we can do to prevent losses. With entire towns being wiped off the map like Paradise, California, Jennifer and her team wanted to understand why.
**1:32** · To figure out solutions, he knew that the first step was properly defining the problem, so rather than thinking about size, she approached fire from a new angle.
**1:42** · What do the most destructive fires have in common?
**1:45** · And until recently she didn't have the tools to answer this question.

**1:49** · We've had really good data on how big they are, but we're only getting to the point where the satellites are getting good enough to give us information on a much finer temporal scale on an hour by hour basis.

**1:59** · We have new high resolution data because NASA is doing a lot more than putting astronauts in space these days.

**2:06** · NASA's done a lot over the years with studying the earth. We develop technology. We eventually launch into space on satellites, and we can see processes unfold across really large scales that we often can't see from a ground-based or human perspective.

**2:17** · Jennifer looked at the time-based images of 60,000 fire events in the U.S. to analyze the way they spread and suddenly it made sense.

**2:26** · This is a new discovery that we have made by putting together all of these different data sources and looking at fire from space.

### Speed dictates destruction


**2:33** · Today, so many science discoveries don't happen in the field, but in simulations powered by enormous supercomputers that perform quadrillions of calculations each second to model our climate. I got to visit one of these supercomputers in my new show, Weathered: Earth's Extremes, where I traveled the world to find out where we are and where we're going in this moment of climate change. You can watch right now on the PBS app, but back to fire.
**2:58** · The results of Jennifer's investigation were striking. What almost all destructive fires have in common between 2001 and 2020 is speed. And this finding fundamentally changes how we approach fire management.

**3:12** · Fires that move that fast.
**3:13** · More than 4,000 acres a day account for 88% of the fire related damages that we see across the U.S. They are only 3% of the fires on record during that time. A very small number of fire events have huge consequences.

**3:28** · And fast fires themselves changed in a worrying way during the study window. We'll get to that in a bit, but first, why are fast fires so destructive?

### Firefighting in fast fires

**3:37** · And why are they so destructive in a place like Southern California with some of the most experienced firefighters in the world, backed by impressive air support?

**3:46** · The Bridge Fire was a great example, the fire activity was so significant, our conventional methods with fire engines and personnel were really ineffective.

**3:54** · When fires are moving this fast, it's virtually impossible to put them out. When Mike's crew deployed to the Mountain High Ski Resort, wind was blowing embers miles ahead of the flaming front. Smoke reduced visibility and grounded aircrafts.

**4:08** · Winds were significant at more than 50 miles an hour, we realized that the fire suppression, putting this fire out, on our side is not gonna happen and we're gonna have to move and shift our priorities.

**4:19** · The fire was spreading quickly towards the town of Wrightwood just three miles away.

**4:24** · There's a lot of similarities between the community of Paradise and the community of Wrightwood. We knew that going up there, we were gonna have a heck of a firefight.

**4:33** · The comparison to Paradise, California is significant.
**4:36** · In 2018, another fast fire burned over 18,000 structures and homes and killed almost 90 people. So the crew raced in an attempt to reach Wrightwood before the fire did.

**4:48** · We had, you know, upwards of 50 engines on their way or there. We still had over 3000 structures immediately threatened.
**4:56** · If you were to ask me at 30 minutes into this incident, where was our structure loss gonna be?
**5:01** · I would say probably in upwards of one to 200.

**5:04** · So they fought from house to house and help residents evacuate. By the end of September 10th, the Bridge Fire had exploded from 4,000 acres to over 34,000. This fire is part of a growing trend. During Jennifer's 20 year study period, fires got 249% faster across the West and 400% faster in California.

### Drivers of rapid spread

**5:26** · But what's making them faster?
**5:29** · Forest management is often regarded as a primary driver of fire behavior. But according to Jennifer, it isn't a significant factor in fast fires.

**5:38** · The fastest fires are actually in grasslands.
**5:40** · They're very flammable fuels. They're very thin, they're easy to catch on fire. They host fires that move really fast.

**5:46** · In fact, 80% of fast fires in Jennifer's study occurred primarily in grass and shrublands, not forests. It turns out that there are three elements needed for fast fire. One: ignition, two: dry, receptive fuel, and three: wind. Wind and ignition are difficult to change and control, but there's a piece of the fast fire puzzle that's a key force in their rise: dry, receptive fuel.

**6:14** · We've had fuels that have been drying out all summer long and then we just throw in a little weather and a fire. And those are mixtures and that recipe for extreme fire behavior.

**6:23** · And firefighters even have a term for this fire weather. In Canada, they call it crossover because it occurs when the temperature in Celsius reaches and crosses over the relative humidity level and it's explosive. At that point, fire can rip through dry fuels and spread extremely fast. In the U.S. we use the more general term red flag conditions.
**6:46** · So what does that mean for the future of fast fires?

### Climate change and risk


**6:50** · With increasing temperatures, we know that we're essentially pulling more moisture out of fuels, we're making them drier. And that's the big impact of climate change on fire is making fuels more available and more available throughout the year.

**7:05** · We're seeing extreme weather patterns change and and intensify across the globe. We're getting all sorts of situations in which weather patterns are driving extreme fire behavior.

**7:13** · Models predict that the number of extreme fire spread events will more than double with two degrees Celsius of global warming, plus a doubling of acres burned. And that's not far from our current level of warming. We can't have a fast fire without strong wind. But the type of wind that causes many destructive fires has a special characteristic that makes it particularly dangerous.

### The danger of wind events

**7:35** · We worked with NASA to create scientifically accurate animations of the wind and fire progressions during a handful of fast, destructive fires to illustrate what's going on.

**7:45** · I'm hard pressed to think of an event that destroyed more than a hundred homes that didn't have wind involved.

**7:51** · And the common denominator for us to make it hard to control wildfires is wind.

**7:55** · When strong winds meet or start a wildfire, they throw embers miles ahead of the flaming front, starting new fires and spreading the wildfire outward. These conditions supercharged the East Troublesome Fire. The fire was so fast, moving at 18 miles in a single day, that it jumped The Continental Divide, an area with very little fuel for fire. In the Marshall Fire, we can see a type of wind that's particularly dangerous: down slope winds.
**8:23** · As wind drops in elevation, atmospheric pressure increases, which dries and warms the air. Temperatures can increase by as much as 5.5 degrees Fahrenheit for every 1000 feet of lost elevation, drying vegetation, and eliminating the need for high temperatures with wildfire. The fire started on December 30th, just outside of Boulder, Colorado.
**8:46** · Wind gusts of up to 115 miles per hour flowed off the front range of the Rocky Mountains, sucking any remaining moisture out of the vegetation to create the most destructive fire in state history. Destroying over a thousand homes in six hours. In Lahaina, wind blew down the mountain, drying vegetation, warming the air, and knocking down power lines that ignited grasses, then houses, destroying much of the town.
**9:13** · During the Labor Day fires, river canyons turned into wind tunnels with speeds reaching 100 miles per hour. Wind blew over power lines and ignited fires in and around small communities, fanning existing fires to create one of the most destructive fire seasons in state history. These aren't just regular wildfires, they're wind events with fire in them.

### Preparing for future fires


**9:36** · In those situations where you have an extreme wind event, basically the fire becomes uncontrollable. You know, fire suppression efforts are extremely ineffective in that situation. 'cause basically, for safety reasons, the firefighters just have to get out of the way. And so there's, there's really no stopping it.

**9:50** · And that's probably the most important lesson about fast fires. Once they've started, there's no stopping them until the wind dies down. Firefighters can only evacuate people and wait. And as we face a hotter, drier, future fire prone places are going to become far more challenging places to live.
**10:08** · So how do we reduce the destruction?
**10:11** · We prepare ahead of time. Let's go back to the Bridge Fire, where Mike expected hundreds of houses to be lost.

**10:19** · I feel like the Bridge Fire in Wrightwood is a success story.

**10:21** · The Wrightwood community did everything right to prepare their homes for fire. The result? Only about 10 homes burned rather than one to 200 that Mike expected.
**10:31** · So how do we prepare our homes for fire?
**10:34** · To answer this question, I ask the Chief of all fire chiefs.

**10:37** · Understanding how to live with the fire that's inevitable is absolutely key to our survival of the communities across the Nation.

**10:45** · The research shows that we can significantly reduce the chance that homes will ignite in fast fires by taking simple steps focused on our home and its immediate surroundings.

**10:56** · So it is incumbent on community planners, on individuals who purchase the properties on builders that they also build to code. Codes that are based on science: fire resistant materials, proper roofing materials, proper windows, not having wood fences. These are key pieces of the puzzle here.
**11:16** · If we're going to continue to build communities in the path of fire, then we must build them according to the science and the codes to make people saveable in their own homes, in their own communities.

**11:28** · If you wanna learn more about the ways you can prepare your home for fire, tornadoes, or even hurricanes, check out our new series Weathered: Earth's Extremes by downloading the PBS app today.
**11:38** · And we'd love to hear from you in the comments: Do you live in fire country?
**11:43** · Have you survived a fire yourself?
**11:45** · What are you doing to prepare your home?
**11:47** · Let us know and we'll see you next time on Weathered.