---
title: "Are We Living In the Sixth Extinction"
profile:
  - "video"
  - "conbio"
categories:
  - "video"
  - "BIOL4120"
---

**Be Smart**, *11 17, 2014*

## Video (9:11)

<iframe width="560" height="315" src=https://www.youtube.com/embed/z9gHuAwxwAs title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Description

This time, we're the asteroid.

Viewers like you help make PBS (Thank you 😃) . Support your local PBS Member Station here: https://to.pbs.org/PBSDSDonate

Subscribe to It's Okay To Be Smart: http://bit.ly/iotbs_sub 

Read "The Sixth Extinction by Elizabeth Kolbert: http://amzn.to/1xGKn0K 

Rodolfo Dirzo et al. "Defaunation in the Anthropocene" http://bit.ly/1H7JQdw 

Stuart Pimm et al. "Biodiversity of Species and Their Rates of Extinction" http://bit.ly/1A5UZJM 

Get to know an endangered species: http://discover.iucnredlist.org/ 

Half of world's wildlife has died off in past 40 years: http://bit.ly/1BHl8jR 

Have an idea for an episode or an amazing science question you want answered? Leave a comment below!

Produced for PBS Digital Studios 

Joe Hanson - Host/Writer

Joe Nicolosi - Director

Amanda Fox - Producer, Spotzen Inc

Kate Eads - Associate Producer

Katie Graham - Director of Photography

Andrew Matthews - Editing/Motion Graphics

Dalton Allen - Post-production intern

John Knudsen - Gaffer 

Theme music:

"Ouroboros" by Kevin MacLeod

Stock images by Shutterstock

-----------
Join us on Patreon! 

https://patreon.com/itsokaytobesmart

Twitter 

http://www.twitter.com/DrJoeHanson

http://www.twitter.com/okaytobesmart 

Instagram 

http://www.instagram.com/DrJoeHanson 

http://www.instagram.com/okaytobesmart 

Merch

https://store.dftba.com/collections/its-okay-to-be-smart

Facebook

https://www.facebook.com/itsokaytobesmartpbs/

## Transcript

### The history of extinction

**0:02** · [MUSIC] The California Golden Bear The Great Auk The Passenger pigeon The Tasmanian tiger The Pinta Island tortoise The Golden toad All dead. And the killer is right there in the room with you.

**0:22** · [MUSIC] The walls of France’s Lascaux cave hold some of humankind’s earliest art, almost mythical species: a wooly rhinoceros, enormous-antlered Megaloceros elk and massive aurochs. The artists lived on, became us, but those cave walls are the last place that those animals still run. They’re gone. Extinct.

**0:51** · We all pretty much understand extinction, it’s when a species kicks the proverbial bucket, it rides off into the great biological sunset, bites the dust from whence it came and shall return, which is all just a pretty way of saying that every last one of them dies.

**1:05** · Even kids are used to the idea that sometimes groups of living things just… don’t exist anymore. Okay, mostly don’t exist.

### Discovering mass events

**1:13** · But extinction, as a thing, is a surprisingly new concept. In the 1790’s, by studying various fossils, naturalist Georges Cuvier was the first to show that they were not from living, yet undiscovered creatures, as many thought, but from what he called “lost species”.

**1:29** · In the decades to come, scientists like Charles Lyell and ol' Chuck Darwin began to popularize the idea that Earth’s processes, like geology, evolution, and even extinction, did occur, just very, very, verrrry slowly. So slowly that we’d surely never actually see something go extinct. The idea of so-called catastrophic change was just impossible… It wasn’t until the 1980’s that scientists were able to shake that idea. Geologist Walter Alvarez was puzzled by the sudden disappearance of tiny aquatic fossils between two rock layers that dated from about 66 million years ago, the same age as the last dinosaurs.

**2:01** · With the help of his Nobel Prize winning father, he analyzed the chemistry of that boundary and found iridium levels that were off the charts. Now, there’s usually not much iridium in Earth’s crust, but it’s very common in asteroids. So Alvarez’s theory? A 10-km wide rock collided with Earth, wiping out 75% of Earth’s plants and animals. To be honest scientists kinda laughed at it… until the 1991 discovery of the Chicxulub crater near the Yucatan peninsula finally settled it.

**2:36** · Everything alive today is a descendent of a survivor of that terrible, horrible, no good, very bad day, the so-called Cretaceous-Paleogene mass extinction event, the most recent of the Big 5.

### The big five extinctions

**2:50** · You should feel pretty lucky. When we look at all of Earth’s fossil record together, 98% of the species that have ever lived are extinct,. Only they haven’t always disappeared at a constant rate.

**3:02** · In the history of life on Earth, we know of 5 different mass extinctions, when a majority of life on Earth at the time disappeared in the blink of a geologic eye.

**3:13** · Besides the most recent dino-killer, there’s the Triassic-Jurassic, Late Devonian, Ordivician-Silurian, and the worst of all, the End Permian. This was the mother of mass extinctions, it wiped out as many as 96% of Earth’s species, so it got the best nickname: The Great Dying.

**3:34** · We’ve learned about all these just in time to get some bad news: We are in the 6th mass extinction, and this time, we are the asteroid.

### The sixth mass extinction

**3:46** · The hard facts of life mean that even when things are going pretty well on Earth, there’s a background rate of extinction. Among mammals, for instance, we’d expect to see one species go extinct every 700 years, or maybe one amphibian every thousand years.

**4:00** · Studies of current extinction rates say we’re roughly one thousand times past that, and in some groups, like amphibians, are disappearing forty-five thousand times faster than normal.

**4:13** · And since there are so many species still unknown or uncharacterized, all of those numbers are probably underestimates.

**4:19** · Goodbye, gastric brooding frog, Pyrenean ibex, the Fomosan clouded leopard. We could have been friends.

**4:29** · So how do we know we’re to blame?

**4:32** · Around 13,000 years ago, as Earth thawed from its most recent big freeze, all of our favorite weird megafauna like the wooly mammoth, Smilodon, and our old friend Megatherium disappeared from the Earth, thanks to a changing climate and the invention of sharp stabby hunting tools. I really wish we had saved the 8-foot long beaver though. That would be awesome.

**4:53** · Along the way, through hunting and farming, humans have been altering ecosystems in small but significant ways, but since the Industrial Revolution, man we have really kicked it into overdrive.

**5:05** · With the exception of maybe the first bacteria to breathe oxygen into the air, no living thing has ever altered life on Earth to the degree that we have, which is why scientists now refer to current epoch as the Anthropocene.

### Drivers of species loss

**5:18** · "We are the ultimate problem. There are 7 billion people on the planet, we tend to destroy critical habitats where species live, we tend to be warming the planet, we tend to be very careless about moving species around the planet."

**5:32** · According to a 2014 paper by Stuart Pimm in Science (link in the doobly do), the main cause of the current extinction is human population growth and increased consumption. But those two things lead to a whole mess of threats: The most obvious are climate change and habitat destruction. Scientists found that most land species have very small ranges, so they can’t just pack up and move when we cut down their forest or turn it into a desert.

**5:55** · Ocean species have more freedom to move to better waters, unless they’re coral reefs, but thanks to the highest atmospheric CO2 concentrations in 800,000+ years turning the oceans more acidic, anything with a calcium based shell has nowhere to run… or swim. If current trends hold up and the ocean hits pH 7.8 by end of century, it could wipe out ⅓ of the species in the ocean.

**6:23** · Then there’s the invaders! Thanks to a species of snake hitching a ride on military cargo in the 1940s, Guam has lost all of its native birds. "I have had it with these (invasive) snakes on this (Guam-bound cargo) plane" In Africa’s Lake Victoria, 100s of species of cichlid fish species vanished after fishermen introduced the Nile Perch. Go us! We’re erasing species faster than we can even name them.

**6:50** · Stanford’s Rodolfo Dirzo says that in the past 40 years, invertebrate populations, which might make up 97% of species on Earth, have declined 45% worldwide, and that’s just the ones we know about. (Link in the doobly do to that one too) You have to feel worst for the amphibians. Over the past 350 million years, they’ve survived multiple mass extinctions, but this time we’re giving them all we’ve got.

**7:17** · Dirzo gives this loss of animal life a rather harmless sounding name: Defaunation. But there is nothing cute about it. There is not a group of living things on Earth today that is not threatened by the current and coming extinction. That includes us.

### Why saving species matters

**7:34** · Extinction is about more than gorillas, tigers, polar bears, and rhinos, and the dozens of other “famous” or “charismatic” species out there. Those are all important and worth saving, but we need to care just as much about the humble beetles, the ugly little worms, and the slimy frogs.

**7:52** · Every species, big or small, panda or protozoa, is important and worth saving, whether or not we understand exactly why it’s worth saving.

**8:02** · John Muir once said, “When we try to pick out anything by itself we find that it is bound fast by a thousand invisible cords that cannot be broken, to everything in the universe.”

**8:15** · I’ve put some links down in the description where you can get to know some of Earth’s less-loved endangered species. Go make friends with one.

**8:23** · Our knowledge and understanding of the planet’s ecosystems may be incomplete, but our effect on them knows no bounds. I hope the same tools and technology that we’ve used to push life on Earth to the edge might also give us power to bring ‘em back.

**8:39** · So what are we gonna do? Let’s talk about it down there.

**8:43** · Stay curious.

**8:44** · If you want to read more about the brilliant and tragic stories of extinction in this age of humans, check out "The Sixth Extinction" by Elizabeth Kolbert, link in the description.