---
title: "How poaching is changing the face of African elephants"
profile:
  - "video"
  - "conbio"
categories:
  - "video"
  - "BIOL4120"
---

**Vox**, *03 15, 2017*

## Video (5:21)

<iframe width="560" height="315" src=https://www.youtube.com/embed/K8EVQdIUWBE title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Description

It's "natural" selection.

Subscribe to our channel! http://goo.gl/0bsAjO

Many thanks to Dr. Joyce H. Poole, Dr. Tammie Matson, Andrew Parker, and African Parks. To learn more about their ongoing work in elephant conservation, visit their websites below:

https://500elephants.org/

https://www.african-parks.org/

https://www.elephantvoices.org/

https://matsonridley.com/

And for a little pick-me-up…

Cute Baby Elephants

https://youtu.be/SNggmeilXDQ

https://youtu.be/JHlWvn_RCQI

https://youtu.be/UeTmE71uEaw

https://youtu.be/gAYCbnEZ4p8

https://youtu.be/t2kAPfUEaZM


Elephants and their ancestors have roamed the African continent for millions of years. They are the largest land animals on earth and can live up to 70 years. Elephants are profoundly intelligent and social creatures. They have trunks that serves as their nose, arm, and fingers. But elephant populations have taken a massive hit to their populations. Despite an international ban on the ivory trade and other laws to protect elephants, their overall populations continue to fall due to habitat loss and rampant poaching for their tusks. Because of that, a once rare trait is being passed onto more African elephants. The trait is tusklessness, The loss of tusks is only the beginning. The real devastation occurs with the loss of a groups matriarch. The oldest and most experienced grandmothers are the family’s living memory of migration routes, friendly elephants, food and water sources, etc. Matriarchs are also, the first in line to protect their families and without them an entire group of elephants can fall apart. But with China banning ivory in 2017,  providing stronger incentives to protect elephants, and sustained conservation efforts from organizations like ElephantVoices, African Parks, and others, elephants may stand a chance to roam the continent as their ancestors once did.



Vox.com is a news website that helps you cut through the noise and understand what's really driving the events in the headlines. Check out http://www.vox.com to get up to speed on everything from Kurdistan to the Kim Kardashian app. 

Check out our full video catalog: http://goo.gl/IZONyE

Follow Vox on Twitter: http://goo.gl/XFrZ5H

Or on Facebook: http://goo.gl/U2g06o

## Transcript

**0:00** · Elephants are one of the most iconic creatures on this planet.

**0:04** · They’re the largest land animals, the only surviving members of their order, and they’re highly intelligent, social beings.

**0:10** · Reporter #1: "They're a lot like human babies, actually."

**0:12** · Reporter #2: "These elephants in Thailand can even paint."

**0:14** · Reporter #3: "It is the matriarch who guides the herd. It's the older females vast life experience that gives them these skills."

**0:23** · African elephants have been here for a million and a half years. And now, human intervention is literally changing the face of this incredible creature.

**0:31** · During the 1500s, an estimated twenty-six million elephants roamed the African continent.

**0:39** · Today, it’s less than 500,000.

**1:03** · In the 1970s and 80s, elephant poaching reached crisis-levels, so in 1989, an international agreement banned the global ivory trade.

### CITES (Convention on International Trade in Endangered Species of Wild Fauna and Flora)


### 1989 1990 Ban goes into effect

**1:13** · But in the past several years, poaching has returned to high levels. This chart shows the percentage of african elephant deaths caused by poaching since 2003.

**1:21** · Their ivory tusks are basically just large teeth, but for centuries, they’ve been used in artworks, ornaments, jewelry -- even piano keys.

**1:28** · Ivory’s value has been compared to diamonds -- it’s a status symbol.

**1:33** · And the rise of China’s middle class has pushed up demand for ivory there, where it sells for around $1100 per kilogram.

**1:48** · One-third of an elephant's tusks are in its skull which contains a pulpy cavity of tissues, blood vessels, and nerves.

**1:55** · That means they can’t be preemptively removed by conservationists, an approach that has been applied to rhino horns, which aren’t ivory but are also sought after in Asia.

**2:07** · Conservationists can safely remove up to 93% of a rhino’s horn, but it’s not possible to remove that much from elephants.

**2:15** · But in recent decades there’s been an increasing trend of elephants being born tuskless.

**2:30** · While most African elephants of both sexes have tusks, around 2 to 6 percent are naturally born tuskless.

**2:37** · Now, decades of heavy poaching have made that trait more common.

**2:41** · This chart shows that elephant populations subject to poaching have higher rates of tusklessness compared to undisturbed populations.

**2:49** · Let’s use Gorongosa National Park as an example.

### Gorongosa National Park


### The Mozambican Civil War

**2:57** · Of the older female elephants who survived the war, over half were tuskless.

**3:03** · And of the younger females born after the war, 33% were tuskless.

**3:09** · Because tuskless elephants were less likely to be killed by poachers, the tuskless trait became more common in the next generation.

**3:16** · Scientists have also found that on average, tusks are smaller than they were a century ago.

**3:41** · Like tusklessness, smaller tusks provide a survival advantage against poaching. But it comes at a cost.

**4:10** · Tusklessness is not likely to save the species from poaching and habitat loss.

**4:17** · Yet, there is some hope.

**4:19** · Through determined conservation efforts, some African national parks are seeing growth in their elephant populations.

**4:27** · And China has announced that by the end of 2017, they will end domestic sales and processing of ivory.

### BBC China announces ban on ivory trade by end of 2017

**4:34** · Those steps, along with stronger incentives to protect elephant habitats and support local anti-poaching programs, might give elephants the leg or tusk up they need to secure their future on this planet.

**4:50** · A big thanks to African Parks and the experts I got to interview for this video.

**4:59** · If you wanna learn more about their work in elephant conservation, links to their web sites are in the description box.

**5:06** · And if you need a little pick-me-up, don't worry I got you covered.

**5:10** · Links to baby elephant videos are in there too.