---
title: "This Is Martha, the World's Last-Known Passenger Pigeon"
profile:
  - "video"
  - "conbio"
categories:
  - "video"
  - "BIOL4120"
---

**Smithsonian Channel**, *05 27, 2016*

## Video (2:48)

<iframe width="560" height="315" src=https://www.youtube.com/embed/wx-cGnvKsvo title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Description

Smithsonian's National Museum of Natural History houses one of largest bird collections in the world. One of their most prized birds, Martha, was the last passenger pigeon to ever fly.

From: SERIOUSLY AMAZING OBJECTS: Trailblazers

http://bit.ly/1XCulD1

## Transcript

**0:00** · Hi. Hi. I'm Chris. Lucia. Nice to meet you.

**0:05** · Welcome to the Division of Birds.

**0:06** · Thanks. The Smithsonian has one of the largest collections in the world, open to scientists from all over. Anyone who wants to come and study birds. They can either come here and work with us or we can loan the specimens to them.

**0:22** · One specimen stands out above the rest.

**0:26** · What are you going to see today? Oh my god. You're kidding me. That's Martha.

### Where is Martha the passenger pigeon?

**0:28** · This is Martha. For a pigeon fan like Lucia, this is like seeing a movie star, the very last passenger pigeon. She died in the Cincinnati Zoo at 100 p.m. on the 1st of September, 1914. She was literally alone for about 4 years before she died. And and we knew at that time that there were no other ones in the wild. So this is one of the rare cases when you can actually place an exact time and date on an extinction.

**0:59** · Today, Martha sits for posterity beside her companion, appropriately named George, a fellow passenger pigeon who died long before her.

**1:10** · Hundreds of years ago, passenger pigeons were estimated to be about a quarter of the total bird population of the United States. A flock a mile wide, flying 60 m an hour, could take days to pass overhead. So where did they go? The story really is not a simple one. There are there are a lot of factors involved with any extinction. In this case, there was a lot of market hunting.

**1:36** · They were easy targets because they occurred in these large flocks of over a billion birds. A hunter could go and collect thousands at a time without, you know, really having to try that hard.

**1:48** · Passenger pigeons became a staple of the American diet. By the end of the 1800s, millions were being shipped back to cities in the east. Another natural factor sealed their fate. They didn't lay as many eggs as other pigeons, so it was easier to wipe them out that way, right? Yeah. The the biology of the passenger pigeon was such that they really relied on those large flocks for a couple of reasons. One was protection from predators. you know, there's safety in numbers and they didn't have to lay a whole bunch of eggs to reproduce.

**2:18** · So, in a matter of just a few decades, we're just all gone.

**2:24** · Once a species is gone, no amount of wishful thinking can bring it back.

**2:31** · Birds still go extinct, but the loss of the passenger pigeon made people take notice. It prompted the very first legal protections for migratory birds.

**2:42** · [Music]