---
title: "Nature: Running with the Beest (S41E1)"
---

## Online Access

[Link to PBS Series](https://www.pbs.org/show/nature/)

:::{.column-screen-inset}

<div class="pbs-viral-player-wrapper" style="position: relative; padding-top: calc(56.25% + 43px);"><iframe src="https://player.pbs.org/viralplayer/3072828671/" allowfullscreen allow="encrypted-media" style="position: absolute; top: 0; width: 100%; height: 100%; border: 0;"></iframe></div>

:::

## Transcript

♪♪ NARRATOR: In East Africa, there is a spectacle of nature that can be seen from space.

It's an event that supports an entire ecosystem.

But the world is changing.

Poaching and growing tourism have also had an impact.

A delicate balance has been upset.

♪♪ ♪♪ ♪♪ [ Wind blowing ] ♪♪ NARRATOR: The grasslands of the Maasai Mara in Kenya, East Africa... and northern destination to over a million wildebeest... [ Wildebeest lowing ] ...the most successful and abundant antelope in Africa.

This is the largest land migration on Earth.

A force of nature that drives a complex circle of life.

[ Wildebeest lowing ] The Greater Mara ecosystem.

Vast, open plains are still homeland to many Maasai people.

♪♪ Evalyn Sintoya and Derrick Nabaala are professional wildlife guides.

And the migration is part of their cultural heritage.

Making this journey with Evalyn and Derrick brings a new perspective to this great migration... [ Elephant trumpets ] ...and a fascination for the wildebeest themselves.

♪♪ [ Wildebeest lowing ] Swarm intelligence allows them to systematically overcome obstacles in their path as one superorganism.

[ Flies buzzing ] Guided by the seasons and rainfall patterns... [ Thunder rumbles ] ...their circular journey travels thousands of miles across East Africa, from the grasslands of the Serengeti National Park in Tanzania, to the plains of the Maasai Mara National Reserve in Kenya, where we join them... On a never-ending search for greener pastures.

As the wildebeest move towards Kenya, Evalyn and Dereck will spend four months following their migration through the Mara's ecosystem.

[ Wildebeest lowing ] [ Hyena trills ] ♪♪ This short leg of their journey is especially fraught with danger.

♪♪ [ Wildebeest lowing ] ♪♪ They will have to run for their lives, facing predators who depend on their arrival.

♪♪ ♪♪ [ Wildebeest grunting ] ♪♪ ♪♪ Some threats are as old as the migration itself.

Others are more recent.

[ Thunder rumbles ] [ Rain falling ] ♪♪ July is when the wildebeest are due to arrive in Kenya.

The Maasai Mara National Reserve is a crucial refuge for water and grazing.

For a beast that lives on grass, life revolves around rain.

[ Thunder rumbles ] They chase distant storms to find new pastures.

It is thought that they can sense damp earth on the air 30 miles away.

Evalyn and Derrick wait eagerly for them in the Maasai Mara.

But their arrival is never certain.

Erratic weather, influenced by global warming, is beginning to impact their migration patterns.

If there is no rain here, there is no fresh grass.

But too much rain in one area can also be a problem.

In 2020, the migration didn't arrive in its usually large numbers, which shocked the local Maasai elders.

[ Wildebeest lowing ] Typically, the migration is in the Mara for four months, from July to October.

And they don't travel alone.

♪♪ Hundreds of thousands of zebras... elands... and gazelles accompany them.

A mixed mega herd, consuming four and a half thousand tons of grass in a day.

The herds move on after grazing so the grasslands can replenish even stronger than before.

♪♪ They churn the soil with their hooves... ♪♪ ...and nourish it with their urine and dung.

♪♪ Even their saliva has been found to stimulate grass growth.

It's a stampede that transforms this landscape.

♪♪ ♪♪ As they approach the northern border of Tanzania, they face a human threat.

♪♪ An invisible web of wire snares.

[ Flies buzzing ] ♪♪ KIJAPE: We are the patrol teams.

We normally do our intensive patrol.

NARRATOR: Daniel Kijape heads up a team of 43 rangers who patrol the Kenya-Tanzania border.

The poachers sneak across the fenceless border to hunt animals for bush meat using wire snares.

This is their busiest time, with huge numbers of migrating animals crossing the border from Tanzania into Kenya.

[ Dog barks ] Large numbers of animals on the move are an easy target for communities living on the edges of protected areas.

Poverty and a growing hungry population drives them.

But it is illegal.

Tens of thousands of animals are poached every year across this region.

If mortality continues to increase as human population increases, these numbers may become unsustainable, and the wildebeest population could crash.

[ Wildebeest lowing ] Leaving the border behind them, they enter the northern stretch of their journey -- the Maasai Mara.

Pungent secretions from the glands in their front hooves leave a trail of hormones that helps the wildebeest follow each other by scent.

♪♪ ♪♪ ♪♪ The light of dawn reveals the aftermath... [ Lions grunts ] ...of a battlefield.

A glut of morning kills covers the plains.

[ Hyenas trill ] [ Vultures screeching ] The vultures may spot the kill, but they have to wait their turn.

Hyenas are one of the most feared predators of wildebeest.

A huge clan of 75 individuals terrorize this stretch of the Mara plains.

The matriarch always feeds first.

[ Vultures screech ] Adult hyenas will eat a third of their weight in one meal, far more than most mammals.

[ Vultures screeching ] ♪♪ She heads off with her prize, leaving the carcass to everyone else.

[ Vultures screeching ] With a 9-foot wingspan, endangered lappet-faced vultures are one of the largest scavengers in the sky.

♪♪ ♪♪ This might look like an unruly mob... [ Vulture squawks ] ...but vultures have a strict feeding hierarchy.

♪♪ The lappet-faced bully their way to the best spots on the kill.

[ Vulture squawks ] Their large, powerful beaks pull tendons from the bones that are too coarse for the smaller vultures to manage.

[ Vultures screeching ] It can take just half an hour for a wildebeest carcass to be stripped to a skeleton.

♪♪ Eventually, the vultures have eaten so much, they struggle to fly.

A bit of early morning yoga helps digestion.

The horaltic pose.

Stretching their wings out with their backs to the sun gives them an energy boost on chilly mornings and helps rid them of any parasites in their feathers.

♪♪ [ Hyenas trilling ] Wildebeest takeaway.

Back at her den, the matriarch is greeted eagerly by her clan.

[ Hyenas trilling ] A daily supply of wildebeest meat brings vital nutrition to her growing family.

[ Hyena trilling ] She has an 8-week-old cub.

His birthright ranks him second to her above the entire clan of 75 hyenas.

[ Hyenas trilling ] Timing his birth with the arrival of the migration has given him a much greater chance of survival.

♪♪ ♪♪ She's not the only animal raising a family with the tides of the herds.

♪♪ The lappet also has a large, hungry chick to feed at this time of year.

[ Wildebeest lowing ] ♪♪ Her chick will spend four months in this nest.

Plenty of time to get some practice in for the big day.

♪♪ Mom is kept busy bringing in a daily feast of fresh wildebeest meat, which she regurgitates for her chick.

[ Vulture chick chirping ] The wildebeest migration is a massive force that keeps all life thriving on these plains.

There is another bird living here that is pleased to see them.

[ Wildebeest lowing ] Crowned lapwings rely on the wildebeest's grazing to keep the grass short.

♪♪ ♪♪ They follow the herds, snapping up insects in their wake and pecking grubs from their dung.

♪♪ The migration's arrival also heralds their mating season.

[ Lapwings call ] ♪♪ ♪♪ ♪♪ ♪♪ ♪♪ ♪♪ Perfectly camouflaged eggs are laid on open ground.

Wildebeest dung is often used as nesting material.

♪♪ Guarded constantly, the eggs are still vulnerable here.

[ Lapwing chirps ] ♪♪ ♪♪ [ Lapwing squawks ] [ Lapwing squawks ] [ Wildebeest grunts ] [ Wildebeest lowing ] The wildebeest continue north, through the Mara reserve, where they will face the most dangerous part of their journey.

♪♪ They must cross the Mara River.

♪♪ Over 200 miles of life-giving water cuts through the reserve across the migration route.

♪♪ This is the only permanent water source available to the wildebeest on their journey through Kenya.

And they must cross it to reach new grass on the other side.

♪♪ ♪♪ It's a vital water source to all the animals living here.

♪♪ [ Hippo grunting ] [ Wildebeest grunts ] Predators and prey have no choice but to exist side by side here.

[ Hyenas trilling ] [ Crocodile grunts ] [ Hyenas trill ] Battle-scarred Nile crocodiles move towards these crossing points at this time of year and wait for the big arrival.

These are some of the largest crocs in Africa.

Up to 20 feet long and can weigh five times more than a wildebeest.

Living up to 80 years, they bring decades of hunting experience to this river.

Plenty of time to learn those favorite crossing spots.

There's danger for any animal that wants to cross this river.

♪♪ [ Monkey chittering ] But the crocodiles are holding out for a more substantial meal.

♪♪ As the wildebeest approach the river, they pick up their pace.

♪♪ Instinct to reach grass on the other side drives them on.

♪♪ ♪♪ Like battleships, the crocodiles move into position.

Thousands of sense organs around their jaws and body scales are able to detect low-frequency vibrations.

A stampede of hooves approaching.

♪♪ The wildebeest will mass on the banks building up the courage to cross.

[ Wildebeest lowing ] ♪♪ ♪♪ ♪♪ [ Wildebeest lowing ] They know there is danger.

Many have made this crossing before.

♪♪ Finally, one will leap.

♪♪ ♪♪ ♪♪ ♪♪ [ Water splashing ] [ Wildebeest grunting ] Wildebeest are not the only herds that cross.

There is safety in numbers.

♪♪ ♪♪ The crocodiles slide in... ♪♪ ...and pick off one victim at a time.

♪♪ [ Water splashes ] [ Wildebeest lowing ] ♪♪ Without the mass crossings, these ancient predators would struggle to survive.

♪♪ ♪♪ ♪♪ Crocodiles are cooperative feeders.

[ Water splashing ] Working together, their death roll breaks the prey into bite-sized chunks.

[ Water splashing ] ♪♪ This meal will sustain the crocodiles for many months to come.

It's a drama that's become Kenya's premier tourist attraction.

♪♪ [ Wildebeest lowing ] [ Truck horn honks ] ♪♪ [ Body thuds ] ♪♪ ♪♪ ♪♪ [ Wildebeest lows ] ♪♪ Tourism is vital to wildlife conservation, but vehicles in these numbers disorient and intimidate the wildebeest's behavior.

[ Water splashes, wildebeest grunts ] Rangers try hard to police the chaos.

But controlling vehicles in these numbers is not an easy job.

Sheer numbers mean that most will make it across to embark on the final stage of their journey in Kenya.

♪♪ [ Wildebeest lowing ] The National Reserve is not enclosed, and the wildebeest travel wherever the quest for food takes them.

When they move outside the reserve, the animals are confronted by people.

♪♪ Maasai pastoralists have lived here peacefully with the wildebeest for hundreds of years.

But the human population has exploded in recent decades.

[ Cattle lowing ] It has had a drastic effect on a local wildebeest migration.

♪♪ Up until the late 1970s, up to 150,000 wildebeest came from the Loita plains in the Northeast, to join the main herd north of the Mara River in the dry season.

♪♪ [ Children panting ] [ Wildebeest lowing, grunting ] [ Children panting, calling ] ♪♪ Competition for land means that this vital migration corridor has been completely blocked by fencing.

And in the last five years, the Loita migration has virtually collapsed.

♪♪ ♪♪ It's a tragic change Derrick and Evalyn have seen happen in their recent lifetime... and a warning for the future.

♪♪ ♪♪ ♪♪ During the last few years there has been a seed of change, which might provide a way forward for both the Maasai Mara and the Maasai people living here.

In recent years, landowners are being persuaded to take down their fences and open up the land to allow free movement of people, livestock, and wildlife, forming a network of protected areas called conservancies.

Hundreds of individually owned plots of land are pooled together to make large wildlife areas that are leased to tourism.

In return, the landowners receive guaranteed monthly payments.

Many can still graze their cattle on their land in a managed rotation.

Wildlife habitats are improved.

Tourist densities are kept low to avoid overcrowding.

There is greater control over numbers of vehicles around animals.

It's a win-win for people and wildlife.

Today, there are 15 conservancies located in private lands surrounding the National Reserve and almost 15,000 landowners all benefiting from this scheme.

Communities themselves lead the effort and can see wildlife as a beneficial asset to their livelihoods.

And the wildlife also benefits.

Towards the end of October, the Mara's tall grasses have been grazed short.

[ Thunder rumbles ] Distant storm clouds beckon the wildebeest southwards.

They begin their long march to Tanzania's short grass plains where they will give birth to the next generation.

[ Lion roaring ] ♪♪ O0 C1 ♪♪ ♪♪ ♪♪ To learn more about what you've seen on this "Nature" program, visit pbs.org.